Globk Analysis

 +++++++++++++++++++++++++++++++++++++
 + GLORG                 Version 5.19 +
 +++++++++++++++++++++++++++++++++++++


 Stabilization with  20.0% constant,  80.0% site dependent weighting.
 Delete sites with   3.0-sigma condition.
 Height variance factor      10.00 Position,     10.00 Velocity
 For Position: Min dH sigma 0.0050 m;    Min RMS 0.0030 m,    Min dNE sigma 0.00050 m
 For Velocity: Min dH sigma 0.0050 m/yr; Min RMS 0.0030 m/yr, Min dNE sigma 0.00010 m/yr
 Sigma Ratio to allow use: Position   3.00 Velocity   3.00

====================================================================================================
 Starting Position stabilization iteration   1 L0601161200_thss.glx
 For   18 sites in origin, min/max height sigma       7.39     12.56 mm; Median        8.76 mm, Tol      15.00 mm L0601161200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)    -1.50539 +-    0.89280 Iter  1 L0601161200_thss.glx
 Y Rotation  (mas)    -0.61311 +-    0.92320 Iter  1 L0601161200_thss.glx
 Z Rotation  (mas)    -2.40585 +-    0.99885 Iter  1 L0601161200_thss.glx
 X Translation (m)    -0.09647 +-    0.02746 Iter  1 L0601161200_thss.glx
 Y Translation (m)     0.01016 +-    0.02677 Iter  1 L0601161200_thss.glx
 Z Translation (m)    -0.05403 +-    0.02857 Iter  1 L0601161200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   1.00  REYK_GPS   1.00  CRO1_GPS   1.00  AREQ_GPS   1.00  YELL_GPS   1.00  TRAK_GPS   1.00 
HOB2_GPS   1.00  TOW2_GPS   1.00  GUAM_GPS   1.00  USUD_GPS   1.00  DAV1_GPS   1.00  POL2_GPS   1.00 
KERG_GPS   1.00  KIRU_GPS   1.00  MATE_GPS   1.00  WTZR_GPS   1.00  NYAL_GPS   1.00  ZIMM_GPS   1.00 
 For   54 Position Iter  1 Pre RMS    0.0871 m; Post RMS   0.07476 m L0601161200_thss.glx
 For   18 sites in origin, min/max NE sigma       1.22      3.99 mm; Median        2.14 mm, Tol       2.76 mm L0601161200_thss.glx
Deleting AREQ_GPS Position error   0.5731 m, relative variance     2.29 Nsigma     5.06

====================================================================================================
 Starting Position stabilization iteration   2 L0601161200_thss.glx
 For   17 sites in origin, min/max height sigma       7.39     10.12 mm; Median        8.74 mm, Tol      15.00 mm L0601161200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)     0.32465 +-    0.08126 Iter  2 L0601161200_thss.glx
 Y Rotation  (mas)     0.08230 +-    0.09208 Iter  2 L0601161200_thss.glx
 Z Rotation  (mas)     0.08957 +-    0.09215 Iter  2 L0601161200_thss.glx
 X Translation (m)    -0.01006 +-    0.00268 Iter  2 L0601161200_thss.glx
 Y Translation (m)    -0.01084 +-    0.00247 Iter  2 L0601161200_thss.glx
 Z Translation (m)    -0.00011 +-    0.00253 Iter  2 L0601161200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   0.80  REYK_GPS   0.81  CRO1_GPS   1.07  YELL_GPS   0.90  TRAK_GPS   1.01  HOB2_GPS   1.01 
TOW2_GPS   1.07  GUAM_GPS   1.15  USUD_GPS   1.04  DAV1_GPS   1.16  POL2_GPS   0.89  KERG_GPS   1.33 
KIRU_GPS   0.73  MATE_GPS   0.83  WTZR_GPS   0.77  NYAL_GPS   0.75  ZIMM_GPS   0.76 
 For   51 Position Iter  2 Pre RMS    0.0117 m; Post RMS   0.00638 m L0601161200_thss.glx
 For   17 sites in origin, min/max NE sigma       1.03      3.71 mm; Median        1.82 mm, Tol       2.38 mm L0601161200_thss.glx
Deleting REYK_GPS Position error   0.0214 m, relative variance     0.65 Nsigma     4.15
Deleting USUD_GPS Position error   0.0258 m, relative variance     1.19 Nsigma     3.70

====================================================================================================
 Starting Position stabilization iteration   3 L0601161200_thss.glx
 For   15 sites in origin, min/max height sigma       7.75     10.12 mm; Median        8.74 mm, Tol      15.00 mm L0601161200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)     0.26250 +-    0.05786 Iter  3 L0601161200_thss.glx
 Y Rotation  (mas)     0.07809 +-    0.06755 Iter  3 L0601161200_thss.glx
 Z Rotation  (mas)     0.14751 +-    0.06875 Iter  3 L0601161200_thss.glx
 X Translation (m)    -0.00777 +-    0.00194 Iter  3 L0601161200_thss.glx
 Y Translation (m)    -0.01078 +-    0.00176 Iter  3 L0601161200_thss.glx
 Z Translation (m)     0.00370 +-    0.00186 Iter  3 L0601161200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   0.76  CRO1_GPS   1.23  YELL_GPS   0.91  TRAK_GPS   1.06  HOB2_GPS   0.97  TOW2_GPS   1.09 
GUAM_GPS   1.24  DAV1_GPS   1.27  POL2_GPS   0.88  KERG_GPS   1.52  KIRU_GPS   0.72  MATE_GPS   0.78 
WTZR_GPS   0.73  NYAL_GPS   0.75  ZIMM_GPS   0.71 
 For   45 Position Iter  3 Pre RMS    0.0098 m; Post RMS   0.00434 m L0601161200_thss.glx
 For   15 sites in origin, min/max NE sigma       0.95      3.86 mm; Median        1.76 mm, Tol       2.42 mm L0601161200_thss.glx
Deleting GUAM_GPS Position error   0.0229 m, relative variance     1.68 Nsigma     4.06
Deleting POL2_GPS Position error   0.0117 m, relative variance     0.77 Nsigma     3.09

====================================================================================================
 Starting Position stabilization iteration   4 L0601161200_thss.glx
 For   13 sites in origin, min/max height sigma       7.91     10.12 mm; Median        8.74 mm, Tol      15.00 mm L0601161200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)     0.21619 +-    0.04729 Iter  4 L0601161200_thss.glx
 Y Rotation  (mas)     0.10022 +-    0.05658 Iter  4 L0601161200_thss.glx
 Z Rotation  (mas)     0.13945 +-    0.06146 Iter  4 L0601161200_thss.glx
 X Translation (m)    -0.00840 +-    0.00159 Iter  4 L0601161200_thss.glx
 Y Translation (m)    -0.01069 +-    0.00144 Iter  4 L0601161200_thss.glx
 Z Translation (m)     0.00454 +-    0.00162 Iter  4 L0601161200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   0.74  CRO1_GPS   1.24  YELL_GPS   0.89  TRAK_GPS   1.02  HOB2_GPS   0.89  TOW2_GPS   1.05 
DAV1_GPS   1.30  KERG_GPS   1.55  KIRU_GPS   0.71  MATE_GPS   0.75  WTZR_GPS   0.71  NYAL_GPS   0.74 
ZIMM_GPS   0.70 
 For   39 Position Iter  4 Pre RMS    0.0095 m; Post RMS   0.00354 m L0601161200_thss.glx
 For   13 sites in origin, min/max NE sigma       0.91      3.77 mm; Median        1.53 mm, Tol       1.86 mm L0601161200_thss.glx
 Removing KERG_GPS from orgin condition, NE sigma       3.77 mm, Ratio Tol  3.000 L0601161200_thss.glx
Rotating into local coordinates for equates
 Checking covariance matrix after equate and force
Globk Analysis


---------------------------------------------------------
 GLOBK Ver 5.29, Global solution
---------------------------------------------------------

 Solution commenced with: 2006/ 1/16  0: 0    (2006.0411)
 Solution ended with    : 2006/ 1/16 23:59    (2006.0438)
 Solution refers to     : 2006/ 1/16 11:59    (2006.0425) [Seconds tag  45.000]
 Satellite IC epoch     : 2006/ 1/16 12: 0  0.00
 GPS System Information : Time GPST Frame J2000 Precession IAU76 Radiation model BERNE Nutation IAU00 Gravity EGM08 EarthRad NONE  AntThrust NONE 
 MODELS Used in Analysis: SD-WOB  | SD-UT1  | IERS10  | E-Tide  | K1-Tide | PoleTide| OC-Load | MPT2010 |  
 ATM Delay Models Used  : GP25    | GP25    | GP25    | GP25    | 2nd Order Ion     | NONE    | UNKNOWN | 
 Reference Frame        : IGb08           
 Run time               : 2015/12/17 15:14 46.00

 There were         1 exps from          1 global files in the solution
 There were       250648 data used,       0 data not used and       250648 data total
 There were          144 global parameters estimated
 There were    18 Sites,   18 Used Sites,    0 radio sources, and   29 Satellites

 The  prefit chi**2 for      54 input parameters is     0.000

 LIST file      : L0601161200_thss.glx
 COMMON file    :  
 GLOBK CMD file : globk_comb.cmd
 GLORG CMD file : glorg_comb.cmd
 APRIORI file   : ../tables/itrf08_comb.apr
 APRIORI file   : ../tables/itrf08_comb.apr (glorg)
 NUTATION file  :  
 PLANETARY file :  
 SD ORIENT file :  
 PMU file       :  
 BACK SOLN file :  
 OUTGLOBAL file :  
 SVS EPHEM file :  
 SVS MARKOV file:  

* RENAME REPORT (RNRP option)
*   Sites             dN        sN       dE       sE     dU         sU  Units Compare date  EQ Dist EQ Name
* EARTHQUAKE LOG FITS
*  Sites             dN        sN       dE       sE     dU         sU   mm

 Summary of GLOBK command file globk_comb.cmd
-------------------------------------------------------------------------------
* GLOBK command file to generate daily time series and to combine
* h-files over 2 to 30 days.
* For combination, set COMB as a globk command-line option to
* invoke the saving of the output h-file
* Last edited by rwk 130701
* << column 1 must be blank if not comment >>
* This group of commands must appear before any others:
 srt_file @.srt
 srt_dir +1
# Optionally add a second eq_file for analysis-specific renames
* End commands that must appear first
* ITRF2008 augmented by now-defunct sites and recent IGS solutions;
# matched to itrf08_comb.eq
 apr_file ../tables/itrf08_comb.apr
# Optionally add additional apr files for other sites
* Set maximum chi2, prefit coordinate difference (m), and rotation (mas) for an h-file to be used;
 max_chii 13 3 100
# increase tolerances to include all files for diagnostics
# Not necessary unless combining h-files with different a priori EOP
 in_pmu ../tables/pmu.usno
* Invoke glorg
 org_cmd glorg_comb.cmd
* Print file options
 crt_opt NOPR
 prt_opt NOPR GDLF CMDS MIDP
 org_opt PSUM CMDS GDLF MIDP FIXA RNRP
# sh_glred will name the glorg print files
* Coordinate parameters to be estimated and a priori constraints
 apr_neu  all 10 10 10  0 0 0
* Rotation parameters to be estimated and a priori constraints
 apr_wob  5 5 0 0
 apr_ut1  5 0
# If combining with global h-files, allow EOPS to change
# between days
# EOP tight if translation-only stabilization in glorg
* Write out a combined H-file
# Can substitute your analysis name for 'COMB' in the file name below
COMB out_glb  H------_COMB.GLX
* Optionally put a uselist and/or sig_neu and mar_neu reweight in a source file
* Turn off quake log estimates if in the eq_file
 free_log -1
* Remove scratch files for repeatability runs
  del_scra yes
* Correct the pole tide when not compatible with GAMIT
  app_ptid all
* If orbits free in GAMIT (RELAX) and you want them fixed, use:
* but if you are combining with globk h-files, better to leave them
* on but, if the models are incompatible, turn off radiation-pressure parameters,
* When using MIT GLX files which have satellite phase center positions
* estimated use:
  apr_svan all  F F F     ! Fix antenna offset to IGS apriori values.
-------------------------------------------------------------------------------

 Summary of GLORG command file glorg_comb.cmd
-------------------------------------------------------------------------------
* Glorg command file for daily repeatabilities or combinations
* Last edited by rwk 130701
* Parameters to be estimated
 pos_org  xtran ytran ztran xrot yrot zrot
#   or if translation-only
* Downweight of height relative to horizontal (default is 10)
#   Heavy downweight if reference frame robust and heights suspect
* Controls for removing sites from the stabilization
#   Vary these to make the stabilization more robust or more precise
 stab_it 4 0.8 3.0
* A priori coordinates
#  ITRF2008 may be replaced by an apr file from a priori velocity solution
 apr_file ../tables/itrf08_comb.apr
* List of stabilization sites
#   This should match the well-determined sites in the apr_file
 stab_site clear
 source ../tables/igb08_hierarchy.stab_site
SOURCE ># Sites in IGb08 network hierarchy from ftp://igs-rf.ign.fr/pub/IGb08/IGb08_core.txt
SOURCE ># Created with core2stab_site.sh by Mike Floyd on 2014-08-08
SOURCE > stab_site AREQ
SOURCE > stab_site CRO1
SOURCE > stab_site DAV1
SOURCE > stab_site GUAM
SOURCE > stab_site HOB2
SOURCE > stab_site KERG
SOURCE > stab_site KIRU
SOURCE > stab_site MATE
SOURCE > stab_site NYAL
SOURCE > stab_site POL2
SOURCE > stab_site REYK
SOURCE > stab_site TOW2
SOURCE > stab_site TRAK
SOURCE > stab_site USUD
SOURCE > stab_site VILL
SOURCE > stab_site WTZR
SOURCE > stab_site YELL
SOURCE > stab_site ZIMM
SOURCE > 
SOURCE > 
-------------------------------------------------------------------------------

 EXPERIMENT LIST from L0601161200_thss.srt
     #  Name                               SCALE Diag PPM  Forw Chi2 Back Chi2 Status
     1 ../glbf/h0601161200_thss.glx     1.000000   0.000     0.000    -1.000   USED        

 SUMMARY POSITION ESTIMATES FROM GLOBK Ver 5.29        
    Long.       Lat.        dE adj.   dN adj.   dE +-     dN +-   RHO        dH adj.   dH +-  SITE
    (deg)      (deg)         (mm)      (mm)      (mm)      (mm)               (mm)      (mm)
  356.04802   40.44359       1.97      2.95      0.73      0.85  0.008       13.88      3.21 VILL_GPS*
  338.04451   64.13878     -19.25     12.54      1.05      1.24 -0.064      -34.03      3.74 REYK_GPS 
  295.41568   17.75690       1.71     -6.04      1.95      2.10  0.213        0.99      6.87 CRO1_GPS*
  288.50720  -16.46552    -626.44   -443.40      2.92      4.31  0.216       -2.22     11.14 AREQ_GPS 
  245.51930   62.48089       5.56      5.36      1.11      1.27  0.073       19.32      3.81 YELL_GPS*
  242.19657   33.61793      -7.23      3.04      1.46      1.50  0.136       -8.81      5.12 TRAK_GPS*
  147.43873  -42.80471       0.62     -6.89      0.99      1.17  0.310       14.87      5.14 HOB2_GPS*
  147.05569  -19.26928      -2.03     -4.61      1.17      2.12  0.291       -3.88      5.38 TOW2_GPS*
  144.86836   13.58933      -2.39    -23.52      2.05      3.14 -0.028      -15.82      7.75 GUAM_GPS 
  138.36204   36.13311      -0.18    -28.03      1.60      2.87 -0.150      -46.90      4.78 USUD_GPS 
   77.97261  -68.57732      13.74      2.73      2.77      1.30  0.200       13.22      5.38 DAV1_GPS*
   74.69427   42.67977      -2.31     11.86      1.38      1.68 -0.122        1.69      3.35 POL2_GPS 
   70.25552  -49.35147       5.10     -1.22      3.14      2.09 -0.354       16.31      6.54 KERG_GPS 
   20.96845   67.85735      -2.16      5.06      0.68      0.83  0.046       -1.54      2.93 KIRU_GPS*
   16.70446   40.64913      -0.38      0.99      0.84      0.85 -0.116        2.96      3.12 MATE_GPS*
   12.87891   49.14420      -1.54      0.35      0.69      0.74 -0.016       -5.07      2.85 WTZR_GPS*
   11.86509   78.92958      -0.92     -2.23      0.78      0.95  0.007        5.49      3.83 NYAL_GPS*
    7.46528   46.87710      -0.09     -2.03      0.61      0.67 -0.017        1.65      2.69 ZIMM_GPS*
POS STATISTICS: For   12 RefSites WRMS ENU   2.59   3.38   8.85  mm    NRMS ENU   2.92   3.41   2.40 L0601161200_thss.glx
POS MEANS: For   12 RefSites: East  -0.26 +-   0.75 North   0.44 +-   0.98 Up   3.80 +-   2.55 mm L0601161200_thss.glx

 PARAMETER ESTIMATES FROM GLOBK Vers 5.29        
  #      PARAMETER                            Estimate       Adjustment     Sigma
Int. VILL_GPS  4849833.68541  -335049.02412  4116014.92373   -0.01055    0.02001    0.01155 2005.002
    1. VILL_GPS X coordinate  (m)          4849833.68322      0.00880      0.00246
    2. VILL_GPS Y coordinate  (m)          -335049.00191      0.00137      0.00073
    3. VILL_GPS Z coordinate  (m)          4116014.94698      0.01122      0.00224
Unc. VILL_GPS  4849833.68322  -335049.00191  4116014.94698   -0.01055    0.02001    0.01155 2006.042  0.0025  0.0007  0.0022
Apr. VILL_GPS  4849833.68322  -335049.00191  4116014.94698   -0.01055    0.02001    0.01155 2006.042  0.0025  0.0007  0.0022  -1.0000 -1.0000 -1.0000
Loc.   VILL_GPS N coordinate  (m)          4502160.23131      0.00295      0.00085
Loc.   VILL_GPS E coordinate  (m)         30163503.96976      0.00197      0.00073
Loc.   VILL_GPS U coordinate  (m)              647.34286      0.01388      0.00321
     NE,NU,EU position correlations          0.0076       0.1032       0.0881
pbo. VILL_GPS ----------------  2006 01 16 11 59 53751.4998   4849833.68322  -335049.00191  4116014.94698 0.00246 0.00073 0.00224 -0.126  0.871 -0.118 |    40.4435934734  356.0480210470  647.34286      7.6     8.6    0.00321 |   4502160.23131 30163503.96976  647.34286 0.00085 0.00073 0.00321  0.008  0.103  0.088

Int. REYK_GPS  2587384.32846 -1043033.51334  5716564.04602   -0.01961   -0.00176    0.00895 2005.002
    4. REYK_GPS X coordinate  (m)          2587384.27654     -0.03149      0.00186
    5. REYK_GPS Y coordinate  (m)         -1043033.52324     -0.00806      0.00110
    6. REYK_GPS Z coordinate  (m)          5716564.03026     -0.02508      0.00345
Unc. REYK_GPS  2587384.27654 -1043033.52324  5716564.03026   -0.01961   -0.00176    0.00895 2006.042  0.0019  0.0011  0.0035
Apr. REYK_GPS  2587384.27654 -1043033.52324  5716564.03026   -0.01961   -0.00176    0.00895 2006.042  0.0019  0.0011  0.0035  -1.0000 -1.0000 -1.0000
Loc.   REYK_GPS N coordinate  (m)          7139896.81752      0.01254      0.00124
Loc.   REYK_GPS E coordinate  (m)         16413892.67079     -0.01925      0.00105
Loc.   REYK_GPS U coordinate  (m)               93.01516     -0.03403      0.00374
     NE,NU,EU position correlations         -0.0642       0.0935       0.1562
pbo. REYK_GPS ----------------  2006 01 16 11 59 53751.4998   2587384.27654 -1043033.52324  5716564.03026 0.00186 0.00110 0.00345 -0.300  0.697 -0.331 |    64.1387843821  338.0445139633   93.01516     11.1    21.6    0.00374 |   7139896.81752 16413892.67079   93.01516 0.00124 0.00105 0.00374 -0.064  0.093  0.156

Int. CRO1_GPS  2607771.21531 -5488076.69905  1932767.78997    0.00742    0.00906    0.01252 2005.002
    7. CRO1_GPS X coordinate  (m)          2607771.22578      0.00274      0.00344
    8. CRO1_GPS Y coordinate  (m)         -5488076.69139     -0.00177      0.00574
    9. CRO1_GPS Z coordinate  (m)          1932767.79756     -0.00545      0.00325
Unc. CRO1_GPS  2607771.22578 -5488076.69139  1932767.79756    0.00742    0.00906    0.01252 2006.042  0.0034  0.0057  0.0033
Apr. CRO1_GPS  2607771.22578 -5488076.69139  1932767.79756    0.00742    0.00906    0.01252 2006.042  0.0034  0.0057  0.0033  -1.0000 -1.0000 -1.0000
Loc.   CRO1_GPS N coordinate  (m)          1976688.87549     -0.00604      0.00210
Loc.   CRO1_GPS E coordinate  (m)         31319027.49926      0.00171      0.00195
Loc.   CRO1_GPS U coordinate  (m)              -31.95001      0.00099      0.00687
     NE,NU,EU position correlations          0.2135       0.2704       0.1383
pbo. CRO1_GPS ----------------  2006 01 16 11 59 53751.4998   2607771.22578 -5488076.69139  1932767.79756 0.00344 0.00574 0.00325 -0.778  0.709 -0.719 |    17.7568982880  295.4156803195  -31.95001     18.8    18.4    0.00687 |   1976688.87549 31319027.49926  -31.95001 0.00210 0.00195 0.00687  0.213  0.270  0.138

Int. AREQ_GPS  1942826.82329 -5804070.23825 -1796893.84451    0.01247    0.00007    0.01400 2005.002
   10. AREQ_GPS X coordinate  (m)          1942826.20191     -0.63437      0.00496
   11. AREQ_GPS Y coordinate  (m)         -5804070.31656     -0.07838      0.01065
   12. AREQ_GPS Z coordinate  (m)         -1796894.25474     -0.42482      0.00362
Unc. AREQ_GPS  1942826.20191 -5804070.31656 -1796894.25474    0.01247    0.00007    0.01400 2006.042  0.0050  0.0107  0.0036
Apr. AREQ_GPS  1942826.20191 -5804070.31656 -1796894.25474    0.01247    0.00007    0.01400 2006.042  0.0050  0.0107  0.0036  -1.0000 -1.0000 -1.0000
Loc.   AREQ_GPS N coordinate  (m)         -1832932.95966     -0.44340      0.00431
Loc.   AREQ_GPS E coordinate  (m)         30799610.93949     -0.62644      0.00292
Loc.   AREQ_GPS U coordinate  (m)             2488.90905     -0.00222      0.01114
     NE,NU,EU position correlations          0.2155       0.5344       0.1849
pbo. AREQ_GPS ----------------  2006 01 16 11 59 53751.4998   1942826.20191 -5804070.31656 -1796894.25474 0.00496 0.01065 0.00362 -0.788 -0.074  0.177 |   -16.4655169243  288.5072034615 2488.90905     38.7    27.3    0.01114 |  -1832932.95966 30799610.93949 2488.90905 0.00431 0.00292 0.01114  0.216  0.534  0.185

Int. YELL_GPS -1224452.50143 -2689216.10746  5633638.27862   -0.02082   -0.00441   -0.00093 1997.002
   13. YELL_GPS X coordinate  (m)         -1224452.68637      0.00331      0.00122
   14. YELL_GPS Y coordinate  (m)         -2689216.15348     -0.00615      0.00197
   15. YELL_GPS Z coordinate  (m)          5633638.28981      0.01960      0.00347
Unc. YELL_GPS -1224452.68637 -2689216.15348  5633638.28981   -0.02082   -0.00441   -0.00093 2006.042  0.0012  0.0020  0.0035
Apr. YELL_GPS -1224452.68637 -2689216.15348  5633638.28981   -0.02082   -0.00441   -0.00093 2006.042  0.0012  0.0020  0.0035  -1.0000 -1.0000 -1.0000
Loc.   YELL_GPS N coordinate  (m)          6955341.27407      0.00536      0.00127
Loc.   YELL_GPS E coordinate  (m)         12628197.28250      0.00556      0.00111
Loc.   YELL_GPS U coordinate  (m)              180.92278      0.01932      0.00381
     NE,NU,EU position correlations          0.0728       0.0690       0.2110
pbo. YELL_GPS ----------------  2006 01 16 11 59 53751.4998  -1224452.68637 -2689216.15348  5633638.28981 0.00122 0.00197 0.00347  0.366 -0.321 -0.733 |    62.4808937276  245.5192981713  180.92278     11.4    21.6    0.00381 |   6955341.27407 12628197.28250  180.92278 0.00127 0.00111 0.00381  0.073  0.069  0.211

Int. TRAK_GPS -2480029.24905 -4703110.82031  3511298.59513   -0.02924    0.02645    0.01537 2005.002
   16. TRAK_GPS X coordinate  (m)         -2480029.28169     -0.00218      0.00204
   17. TRAK_GPS Y coordinate  (m)         -4703110.78140      0.01136      0.00411
   18. TRAK_GPS Z coordinate  (m)          3511298.60882     -0.00232      0.00309
Unc. TRAK_GPS -2480029.28169 -4703110.78140  3511298.60882   -0.02924    0.02645    0.01537 2006.042  0.0020  0.0041  0.0031
Apr. TRAK_GPS -2480029.28169 -4703110.78140  3511298.60882   -0.02924    0.02645    0.01537 2006.042  0.0020  0.0041  0.0031  -1.0000 -1.0000 -1.0000
Loc.   TRAK_GPS N coordinate  (m)          3742331.39003      0.00304      0.00150
Loc.   TRAK_GPS E coordinate  (m)         22451843.43948     -0.00723      0.00146
Loc.   TRAK_GPS U coordinate  (m)              115.53423     -0.00881      0.00512
     NE,NU,EU position correlations          0.1365       0.0028       0.3434
pbo. TRAK_GPS ----------------  2006 01 16 11 59 53751.4998  -2480029.28169 -4703110.78140  3511298.60882 0.00204 0.00411 0.00309  0.694 -0.584 -0.830 |    33.6179348590  242.1965658310  115.53423     13.5    15.7    0.00512 |   3742331.39003 22451843.43948  115.53423 0.00150 0.00146 0.00512  0.136  0.003  0.343

Int. HOB2_GPS -3950071.67350  2522415.25416 -4311638.02559   -0.03974    0.00862    0.04074 2005.002
   19. HOB2_GPS X coordinate  (m)         -3950071.72053     -0.00563      0.00310
   20. HOB2_GPS Y coordinate  (m)          2522415.26600      0.00286      0.00236
   21. HOB2_GPS Z coordinate  (m)         -4311637.99829     -0.01514      0.00369
Unc. HOB2_GPS -3950071.72053  2522415.26600 -4311637.99829   -0.03974    0.00862    0.04074 2006.042  0.0031  0.0024  0.0037
Apr. HOB2_GPS -3950071.72053  2522415.26600 -4311637.99829   -0.03974    0.00862    0.04074 2006.042  0.0031  0.0024  0.0037  -1.0000 -1.0000 -1.0000
Loc.   HOB2_GPS N coordinate  (m)         -4764998.76844     -0.00689      0.00117
Loc.   HOB2_GPS E coordinate  (m)         12041419.15720      0.00062      0.00099
Loc.   HOB2_GPS U coordinate  (m)               41.07300      0.01487      0.00514
     NE,NU,EU position correlations          0.3102      -0.1281      -0.2951
pbo. HOB2_GPS ----------------  2006 01 16 11 59 53751.4998  -3950071.72053  2522415.26600 -4311637.99829 0.00310 0.00236 0.00369 -0.869  0.866 -0.898 |   -42.8047122250  147.4387345194   41.07300     10.5    12.1    0.00514 |  -4764998.76844 12041419.15720   41.07300 0.00117 0.00099 0.00514  0.310 -0.128 -0.295

Int. TOW2_GPS -5054582.94073  3275504.33760 -2091539.27586   -0.03094   -0.01432    0.05283 2005.002
   22. TOW2_GPS X coordinate  (m)         -5054582.96751      0.00545      0.00417
   23. TOW2_GPS Y coordinate  (m)          3275504.32157     -0.00111      0.00281
   24. TOW2_GPS Z coordinate  (m)         -2091539.22390     -0.00308      0.00309
Unc. TOW2_GPS -5054582.96751  3275504.32157 -2091539.22390   -0.03094   -0.01432    0.05283 2006.042  0.0042  0.0028  0.0031
Apr. TOW2_GPS -5054582.96751  3275504.32157 -2091539.22390   -0.03094   -0.01432    0.05283 2006.042  0.0042  0.0028  0.0031  -1.0000 -1.0000 -1.0000
Loc.   TOW2_GPS N coordinate  (m)         -2145046.38950     -0.00461      0.00212
Loc.   TOW2_GPS E coordinate  (m)         15453122.46468     -0.00203      0.00117
Loc.   TOW2_GPS U coordinate  (m)               88.11555     -0.00388      0.00538
     NE,NU,EU position correlations          0.2906      -0.3441      -0.0163
pbo. TOW2_GPS ----------------  2006 01 16 11 59 53751.4998  -5054582.96751  3275504.32157 -2091539.22390 0.00417 0.00281 0.00309 -0.873  0.665 -0.736 |   -19.2692795683  147.0556883352   88.11555     19.0    11.1    0.00538 |  -2145046.38950 15453122.46468   88.11555 0.00212 0.00117 0.00538  0.291 -0.344 -0.016

Int. GUAM_GPS -5071312.73778  3568363.55234  1488904.35997    0.00611    0.00737    0.00522 2005.002
   25. GUAM_GPS X coordinate  (m)         -5071312.72195      0.00947      0.00660
   26. GUAM_GPS Y coordinate  (m)          3568363.55628     -0.00374      0.00437
   27. GUAM_GPS Z coordinate  (m)          1488904.33884     -0.02657      0.00338
Unc. GUAM_GPS -5071312.72195  3568363.55628  1488904.33884    0.00611    0.00737    0.00522 2006.042  0.0066  0.0044  0.0034
Apr. GUAM_GPS -5071312.72195  3568363.55628  1488904.33884    0.00611    0.00737    0.00522 2006.042  0.0066  0.0044  0.0034  -1.0000 -1.0000 -1.0000
Loc.   GUAM_GPS N coordinate  (m)          1512757.22605     -0.02352      0.00314
Loc.   GUAM_GPS E coordinate  (m)         15675134.97513     -0.00239      0.00205
Loc.   GUAM_GPS U coordinate  (m)              201.90662     -0.01582      0.00775
     NE,NU,EU position correlations         -0.0281      -0.1047       0.2082
pbo. GUAM_GPS ----------------  2006 01 16 11 59 53751.4998  -5071312.72195  3568363.55628  1488904.33884 0.00660 0.00437 0.00338 -0.848 -0.349  0.322 |    13.5893293732  144.8683609331  201.90662     28.2    18.9    0.00775 |   1512757.22605 15675134.97513  201.90662 0.00314 0.00205 0.00775 -0.028 -0.105  0.208

Int. USUD_GPS -3855263.02241  3427432.54860  3741020.34317   -0.00468    0.00390   -0.00211 2005.002
   28. USUD_GPS X coordinate  (m)         -3855263.01109      0.01619      0.00357
   29. USUD_GPS Y coordinate  (m)          3427432.53851     -0.01416      0.00272
   30. USUD_GPS Z coordinate  (m)          3741020.29075     -0.05022      0.00368
Unc. USUD_GPS -3855263.01109  3427432.53851  3741020.29075   -0.00468    0.00390   -0.00211 2006.042  0.0036  0.0027  0.0037
Apr. USUD_GPS -3855263.01109  3427432.53851  3741020.29075   -0.00468    0.00390   -0.00211 2006.042  0.0036  0.0027  0.0037  -1.0000 -1.0000 -1.0000
Loc.   USUD_GPS N coordinate  (m)          4022319.44922     -0.02803      0.00287
Loc.   USUD_GPS E coordinate  (m)         12439689.09761     -0.00018      0.00160
Loc.   USUD_GPS U coordinate  (m)             1508.59296     -0.04690      0.00478
     NE,NU,EU position correlations         -0.1504       0.0191       0.2214
pbo. USUD_GPS ----------------  2006 01 16 11 59 53751.4998  -3855263.01109  3427432.53851  3741020.29075 0.00357 0.00272 0.00368 -0.746 -0.422  0.432 |    36.1331103885  138.3620435735 1508.59296     25.8    17.8    0.00478 |   4022319.44922 12439689.09761 1508.59296 0.00287 0.00160 0.00478 -0.150  0.019  0.221

Int. DAV1_GPS   486854.55811  2285099.25423 -5914955.68461    0.00161   -0.00585   -0.00068 2005.002
   31. DAV1_GPS X coordinate  (m)           486854.54789     -0.01190      0.00250
   32. DAV1_GPS Y coordinate  (m)          2285099.25824      0.01010      0.00264
   33. DAV1_GPS Z coordinate  (m)         -5914955.69661     -0.01129      0.00501
Unc. DAV1_GPS   486854.54789  2285099.25824 -5914955.69661    0.00161   -0.00585   -0.00068 2006.042  0.0025  0.0026  0.0050
Apr. DAV1_GPS   486854.54789  2285099.25824 -5914955.69661    0.00161   -0.00585   -0.00068 2006.042  0.0025  0.0026  0.0050  -1.0000 -1.0000 -1.0000
Loc.   DAV1_GPS N coordinate  (m)         -7633992.68244      0.00273      0.00130
Loc.   DAV1_GPS E coordinate  (m)          3170252.89657      0.01374      0.00277
Loc.   DAV1_GPS U coordinate  (m)               44.40001      0.01322      0.00538
     NE,NU,EU position correlations          0.2002       0.0359       0.4833
pbo. DAV1_GPS ----------------  2006 01 16 11 59 53751.4998    486854.54789  2285099.25824 -5914955.69661 0.00250 0.00264 0.00501 -0.526  0.345 -0.802 |   -68.5773230549   77.9726134920   44.40001     11.7    68.2    0.00538 |  -7633992.68244  3170252.89657   44.40001 0.00130 0.00277 0.00538  0.200  0.036  0.483

Int. POL2_GPS  1239971.36992  4530790.09428  4302578.81606   -0.02731    0.00533    0.00479 2005.002
   34. POL2_GPS X coordinate  (m)          1239971.34191      0.00044      0.00160
   35. POL2_GPS Y coordinate  (m)          4530790.09270     -0.00714      0.00219
   36. POL2_GPS Z coordinate  (m)          4302578.83093      0.00988      0.00294
Unc. POL2_GPS  1239971.34191  4530790.09270  4302578.83093   -0.02731    0.00533    0.00479 2006.042  0.0016  0.0022  0.0029
Apr. POL2_GPS  1239971.34191  4530790.09270  4302578.83093   -0.02731    0.00533    0.00479 2006.042  0.0016  0.0022  0.0029  -1.0000 -1.0000 -1.0000
Loc.   POL2_GPS N coordinate  (m)          4751090.28394      0.01186      0.00168
Loc.   POL2_GPS E coordinate  (m)          6112787.07889     -0.00231      0.00138
Loc.   POL2_GPS U coordinate  (m)             1714.21104      0.00169      0.00335
     NE,NU,EU position correlations         -0.1220       0.3514      -0.2855
pbo. POL2_GPS ----------------  2006 01 16 11 59 53751.4998   1239971.34191  4530790.09270  4302578.83093 0.00160 0.00219 0.00294  0.449  0.472  0.611 |    42.6797701829   74.6942653506 1714.21104     15.1    16.9    0.00335 |   4751090.28394  6112787.07889 1714.21104 0.00168 0.00138 0.00335 -0.122  0.351 -0.285

Int. KERG_GPS  1406337.28912  3918161.09296 -4816167.35661   -0.00527   -0.00015   -0.00151 2005.002
   37. KERG_GPS X coordinate  (m)          1406337.28212     -0.00151      0.00286
   38. KERG_GPS Y coordinate  (m)          3918161.10369      0.01089      0.00435
   39. KERG_GPS Z coordinate  (m)         -4816167.37132     -0.01313      0.00547
Unc. KERG_GPS  1406337.28212  3918161.10369 -4816167.37132   -0.00527   -0.00015   -0.00151 2006.042  0.0029  0.0044  0.0055
Apr. KERG_GPS  1406337.28212  3918161.10369 -4816167.37132   -0.00527   -0.00015   -0.00151 2006.042  0.0029  0.0044  0.0055  -1.0000 -1.0000 -1.0000
Loc.   KERG_GPS N coordinate  (m)         -5493780.16037     -0.00122      0.00209
Loc.   KERG_GPS E coordinate  (m)          5094560.97805      0.00510      0.00314
Loc.   KERG_GPS U coordinate  (m)               73.02451      0.01631      0.00654
     NE,NU,EU position correlations         -0.3539      -0.2596       0.4253
pbo. KERG_GPS ----------------  2006 01 16 11 59 53751.4998   1406337.28212  3918161.10369 -4816167.37132 0.00286 0.00435 0.00547 -0.054  0.089 -0.847 |   -49.3514668565   70.2555221779   73.02451     18.8    43.2    0.00654 |  -5493780.16037  5094560.97805   73.02451 0.00209 0.00314 0.00654 -0.354 -0.260  0.425

Int. KIRU_GPS  2251420.79504   862817.22093  5885476.70247   -0.01574    0.01076    0.01142 2005.002
   40. KIRU_GPS X coordinate  (m)          2251420.77449     -0.00415      0.00132
   41. KIRU_GPS Y coordinate  (m)           862817.22824     -0.00390      0.00075
   42. KIRU_GPS Z coordinate  (m)          5885476.71486      0.00049      0.00273
Unc. KIRU_GPS  2251420.77449   862817.22824  5885476.71486   -0.01574    0.01076    0.01142 2006.042  0.0013  0.0007  0.0027
Apr. KIRU_GPS  2251420.77449   862817.22824  5885476.71486   -0.01574    0.01076    0.01142 2006.042  0.0013  0.0007  0.0027  -1.0000 -1.0000 -1.0000
Loc.   KIRU_GPS N coordinate  (m)          7553845.84222      0.00506      0.00083
Loc.   KIRU_GPS E coordinate  (m)           879764.88194     -0.00216      0.00068
Loc.   KIRU_GPS U coordinate  (m)              390.97860     -0.00154      0.00293
     NE,NU,EU position correlations          0.0463      -0.0070      -0.1314
pbo. KIRU_GPS ----------------  2006 01 16 11 59 53751.4998   2251420.77449   862817.22824  5885476.71486 0.00132 0.00075 0.00273  0.372  0.745  0.383 |    67.8573517395   20.9684475927  390.97860      7.5    16.2    0.00293 |   7553845.84222   879764.88194  390.97860 0.00083 0.00068 0.00293  0.046 -0.007 -0.131

Int. MATE_GPS  4641949.55683  1393045.42466  4133287.46435   -0.01829    0.01899    0.01495 2005.002
   43. MATE_GPS X coordinate  (m)          4641949.53943      0.00165      0.00234
   44. MATE_GPS Y coordinate  (m)          1393045.44455      0.00010      0.00104
   45. MATE_GPS Z coordinate  (m)          4133287.48260      0.00268      0.00215
Unc. MATE_GPS  4641949.53943  1393045.44455  4133287.48260   -0.01829    0.01899    0.01495 2006.042  0.0023  0.0010  0.0021
Apr. MATE_GPS  4641949.53943  1393045.44455  4133287.48260   -0.01829    0.01899    0.01495 2006.042  0.0023  0.0010  0.0021  -1.0000 -1.0000 -1.0000
Loc.   MATE_GPS N coordinate  (m)          4525040.66063      0.00099      0.00085
Loc.   MATE_GPS E coordinate  (m)          1410869.02901     -0.00038      0.00084
Loc.   MATE_GPS U coordinate  (m)              535.65407      0.00296      0.00312
     NE,NU,EU position correlations         -0.1162       0.0340      -0.0758
pbo. MATE_GPS ----------------  2006 01 16 11 59 53751.4998   4641949.53943  1393045.44455  4133287.48260 0.00234 0.00104 0.00215  0.546  0.861  0.491 |    40.6491318670   16.7044596805  535.65407      7.6    10.0    0.00312 |   4525040.66063  1410869.02901  535.65407 0.00085 0.00084 0.00312 -0.116  0.034 -0.076

Int. WTZR_GPS  4075580.55298   931853.79721  4801568.13598   -0.01605    0.01713    0.01009 2005.002
   46. WTZR_GPS X coordinate  (m)          4075580.53310     -0.00316      0.00192
   47. WTZR_GPS Y coordinate  (m)           931853.81276     -0.00230      0.00078
   48. WTZR_GPS Z coordinate  (m)          4801568.14290     -0.00359      0.00219
Unc. WTZR_GPS  4075580.53310   931853.81276  4801568.14290   -0.01605    0.01713    0.01009 2006.042  0.0019  0.0008  0.0022
Apr. WTZR_GPS  4075580.53310   931853.81276  4801568.14290   -0.01605    0.01713    0.01009 2006.042  0.0019  0.0008  0.0022  -1.0000 -1.0000 -1.0000
Loc.   WTZR_GPS N coordinate  (m)          5470707.16472      0.00035      0.00074
Loc.   WTZR_GPS E coordinate  (m)           937828.67930     -0.00154      0.00069
Loc.   WTZR_GPS U coordinate  (m)              666.02281     -0.00507      0.00285
     NE,NU,EU position correlations         -0.0159      -0.0143      -0.0629
pbo. WTZR_GPS ----------------  2006 01 16 11 59 53751.4998   4075580.53310   931853.81276  4801568.14290 0.00192 0.00078 0.00219  0.443  0.870  0.432 |    49.1441986101   12.8789100294  666.02281      6.7     9.4    0.00285 |   5470707.16472   937828.67930  666.02281 0.00074 0.00069 0.00285 -0.016 -0.014 -0.063

Int. NYAL_GPS  1202430.53162   252626.70891  6237767.61729   -0.01430    0.00750    0.01103 2005.002
   49. NYAL_GPS X coordinate  (m)          1202430.52009      0.00337      0.00115
   50. NYAL_GPS Y coordinate  (m)           252626.71649     -0.00024      0.00079
   51. NYAL_GPS Z coordinate  (m)          6237767.63373      0.00495      0.00377
Unc. NYAL_GPS  1202430.52009   252626.71649  6237767.63373   -0.01430    0.00750    0.01103 2006.042  0.0011  0.0008  0.0038
Apr. NYAL_GPS  1202430.52009   252626.71649  6237767.63373   -0.01430    0.00750    0.01103 2006.042  0.0011  0.0008  0.0038  -1.0000 -1.0000 -1.0000
Loc.   NYAL_GPS N coordinate  (m)          8786401.20128     -0.00223      0.00095
Loc.   NYAL_GPS E coordinate  (m)           253597.00860     -0.00092      0.00078
Loc.   NYAL_GPS U coordinate  (m)               78.52805      0.00549      0.00383
     NE,NU,EU position correlations          0.0072       0.0562      -0.0577
pbo. NYAL_GPS ----------------  2006 01 16 11 59 53751.4998   1202430.52009   252626.71649  6237767.63373 0.00115 0.00079 0.00377  0.122  0.555  0.112 |    78.9295849151   11.8650869747   78.52805      8.5    36.5    0.00383 |   8786401.20128   253597.00860   78.52805 0.00095 0.00078 0.00383  0.007  0.056 -0.058

Int. ZIMM_GPS  4331297.06286   567555.87751  4633133.93566   -0.01353    0.01807    0.01205 2005.002
   52. ZIMM_GPS X coordinate  (m)          4331297.05137      0.00260      0.00189
   53. ZIMM_GPS Y coordinate  (m)           567555.89658      0.00025      0.00065
   54. ZIMM_GPS Z coordinate  (m)          4633133.94802     -0.00019      0.00202
Unc. ZIMM_GPS  4331297.05137   567555.89658  4633133.94802   -0.01353    0.01807    0.01205 2006.042  0.0019  0.0007  0.0020
Apr. ZIMM_GPS  4331297.05137   567555.89658  4633133.94802   -0.01353    0.01807    0.01205 2006.042  0.0019  0.0007  0.0020  -1.0000 -1.0000 -1.0000
Loc.   ZIMM_GPS N coordinate  (m)          5218334.64254     -0.00203      0.00067
Loc.   ZIMM_GPS E coordinate  (m)           568072.18881     -0.00009      0.00061
Loc.   ZIMM_GPS U coordinate  (m)              956.33490      0.00165      0.00269
     NE,NU,EU position correlations         -0.0169       0.0177      -0.0230
pbo. ZIMM_GPS ----------------  2006 01 16 11 59 53751.4998   4331297.05137   567555.89658  4633133.94802 0.00189 0.00065 0.00202  0.321  0.881  0.308 |    46.8770976704    7.4652770506  956.33490      6.1     8.1    0.00269 |   5218334.64254   568072.18881  956.33490 0.00067 0.00061 0.00269 -0.017  0.018 -0.023

Eph. #IC  6  16 12  0  0                    GPST J2000 IAU76 BERNE
   55. PRN_0132 AntOffest X   (m)                0.27900      0.00000      0.00000
   56. PRN_0132 AntOffest Y   (m)                             0.00000      0.00000
   57. PRN_0132 AntOffest Z   (m)                2.38080      0.00000      0.00000
Eph.  2006  1 16 11 PRN_0132         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.38080

   58. PRN_0261 AntOffest X   (m)                             0.00000      0.00000
   59. PRN_0261 AntOffest Y   (m)                             0.00000      0.00000
   60. PRN_0261 AntOffest Z   (m)                0.77860      0.00000      0.00000
Eph.  2006  1 16 11 PRN_0261         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.77860

   61. PRN_0333 AntOffest X   (m)                0.27900      0.00000      0.00000
   62. PRN_0333 AntOffest Y   (m)                             0.00000      0.00000
   63. PRN_0333 AntOffest Z   (m)                2.79260      0.00000      0.00000
Eph.  2006  1 16 11 PRN_0333         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.79260

   64. PRN_0434 AntOffest X   (m)                0.27900      0.00000      0.00000
   65. PRN_0434 AntOffest Y   (m)                             0.00000      0.00000
   66. PRN_0434 AntOffest Z   (m)                2.42000      0.00000      0.00000
Eph.  2006  1 16 11 PRN_0434         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.42000

   67. PRN_0535 AntOffest X   (m)                0.27900      0.00000      0.00000
   68. PRN_0535 AntOffest Y   (m)                             0.00000      0.00000
   69. PRN_0535 AntOffest Z   (m)                2.62200      0.00000      0.00000
Eph.  2006  1 16 11 PRN_0535         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.62200

   70. PRN_0636 AntOffest X   (m)                0.27900      0.00000      0.00000
   71. PRN_0636 AntOffest Y   (m)                             0.00000      0.00000
   72. PRN_0636 AntOffest Z   (m)                2.87860      0.00000      0.00000
Eph.  2006  1 16 11 PRN_0636         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.87860

   73. PRN_0737 AntOffest X   (m)                0.27900      0.00000      0.00000
   74. PRN_0737 AntOffest Y   (m)                             0.00000      0.00000
   75. PRN_0737 AntOffest Z   (m)                2.35220      0.00000      0.00000
Eph.  2006  1 16 11 PRN_0737         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.35220

   76. PRN_0838 AntOffest X   (m)                0.27900      0.00000      0.00000
   77. PRN_0838 AntOffest Y   (m)                             0.00000      0.00000
   78. PRN_0838 AntOffest Z   (m)                2.57810      0.00000      0.00000
Eph.  2006  1 16 11 PRN_0838         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.57810

   79. PRN_0939 AntOffest X   (m)                0.27900      0.00000      0.00000
   80. PRN_0939 AntOffest Y   (m)                             0.00000      0.00000
   81. PRN_0939 AntOffest Z   (m)                2.46140      0.00000      0.00000
Eph.  2006  1 16 11 PRN_0939         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.46140

   82. PRN_1040 AntOffest X   (m)                0.27900      0.00000      0.00000
   83. PRN_1040 AntOffest Y   (m)                             0.00000      0.00000
   84. PRN_1040 AntOffest Z   (m)                2.54650      0.00000      0.00000
Eph.  2006  1 16 11 PRN_1040         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.54650

   85. PRN_1146 AntOffest X   (m)                             0.00000      0.00000
   86. PRN_1146 AntOffest Y   (m)                             0.00000      0.00000
   87. PRN_1146 AntOffest Z   (m)                1.14130      0.00000      0.00000
Eph.  2006  1 16 11 PRN_1146         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.14130

   88. PRN_1343 AntOffest X   (m)                             0.00000      0.00000
   89. PRN_1343 AntOffest Y   (m)                             0.00000      0.00000
   90. PRN_1343 AntOffest Z   (m)                1.38950      0.00000      0.00000
Eph.  2006  1 16 11 PRN_1343         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.38950

   91. PRN_1441 AntOffest X   (m)                             0.00000      0.00000
   92. PRN_1441 AntOffest Y   (m)                             0.00000      0.00000
   93. PRN_1441 AntOffest Z   (m)                1.34540      0.00000      0.00000
Eph.  2006  1 16 11 PRN_1441         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.34540

   94. PRN_1515 AntOffest X   (m)                0.27900      0.00000      0.00000
   95. PRN_1515 AntOffest Y   (m)                             0.00000      0.00000
   96. PRN_1515 AntOffest Z   (m)                2.46860      0.00000      0.00000
Eph.  2006  1 16 11 PRN_1515         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.46860

   97. PRN_1656 AntOffest X   (m)                             0.00000      0.00000
   98. PRN_1656 AntOffest Y   (m)                             0.00000      0.00000
   99. PRN_1656 AntOffest Z   (m)                1.50640      0.00000      0.00000
Eph.  2006  1 16 11 PRN_1656         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.50640

  100. PRN_1753 AntOffest X   (m)                             0.00000      0.00000
  101. PRN_1753 AntOffest Y   (m)                             0.00000      0.00000
  102. PRN_1753 AntOffest Z   (m)                0.82710      0.00000      0.00000
Eph.  2006  1 16 11 PRN_1753         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.82710

  103. PRN_1854 AntOffest X   (m)                             0.00000      0.00000
  104. PRN_1854 AntOffest Y   (m)                             0.00000      0.00000
  105. PRN_1854 AntOffest Z   (m)                1.29090      0.00000      0.00000
Eph.  2006  1 16 11 PRN_1854         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.29090

  106. PRN_1959 AntOffest X   (m)                             0.00000      0.00000
  107. PRN_1959 AntOffest Y   (m)                             0.00000      0.00000
  108. PRN_1959 AntOffest Z   (m)                0.84960      0.00000      0.00000
Eph.  2006  1 16 11 PRN_1959         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.84960

  109. PRN_2051 AntOffest X   (m)                             0.00000      0.00000
  110. PRN_2051 AntOffest Y   (m)                             0.00000      0.00000
  111. PRN_2051 AntOffest Z   (m)                1.34360      0.00000      0.00000
Eph.  2006  1 16 11 PRN_2051         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.34360

  112. PRN_2145 AntOffest X   (m)                             0.00000      0.00000
  113. PRN_2145 AntOffest Y   (m)                             0.00000      0.00000
  114. PRN_2145 AntOffest Z   (m)                1.40540      0.00000      0.00000
Eph.  2006  1 16 11 PRN_2145         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.40540

  115. PRN_2247 AntOffest X   (m)                             0.00000      0.00000
  116. PRN_2247 AntOffest Y   (m)                             0.00000      0.00000
  117. PRN_2247 AntOffest Z   (m)                0.90580      0.00000      0.00000
Eph.  2006  1 16 11 PRN_2247         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.90580

  118. PRN_2360 AntOffest X   (m)                             0.00000      0.00000
  119. PRN_2360 AntOffest Y   (m)                             0.00000      0.00000
  120. PRN_2360 AntOffest Z   (m)                0.80820      0.00000      0.00000
Eph.  2006  1 16 11 PRN_2360         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.80820

  121. PRN_2424 AntOffest X   (m)                0.27900      0.00000      0.00000
  122. PRN_2424 AntOffest Y   (m)                             0.00000      0.00000
  123. PRN_2424 AntOffest Z   (m)                2.60380      0.00000      0.00000
Eph.  2006  1 16 11 PRN_2424         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.60380

  124. PRN_2525 AntOffest X   (m)                0.27900      0.00000      0.00000
  125. PRN_2525 AntOffest Y   (m)                             0.00000      0.00000
  126. PRN_2525 AntOffest Z   (m)                2.48900      0.00000      0.00000
Eph.  2006  1 16 11 PRN_2525         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.48900

  127. PRN_2626 AntOffest X   (m)                0.27900      0.00000      0.00000
  128. PRN_2626 AntOffest Y   (m)                             0.00000      0.00000
  129. PRN_2626 AntOffest Z   (m)                2.45940      0.00000      0.00000
Eph.  2006  1 16 11 PRN_2626         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.45940

  130. PRN_2727 AntOffest X   (m)                0.27900      0.00000      0.00000
  131. PRN_2727 AntOffest Y   (m)                             0.00000      0.00000
  132. PRN_2727 AntOffest Z   (m)                2.63340      0.00000      0.00000
Eph.  2006  1 16 11 PRN_2727         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.63340

  133. PRN_2844 AntOffest X   (m)                             0.00000      0.00000
  134. PRN_2844 AntOffest Y   (m)                             0.00000      0.00000
  135. PRN_2844 AntOffest Z   (m)                1.04280      0.00000      0.00000
Eph.  2006  1 16 11 PRN_2844         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.04280

  136. PRN_2929 AntOffest X   (m)                0.27900      0.00000      0.00000
  137. PRN_2929 AntOffest Y   (m)                             0.00000      0.00000
  138. PRN_2929 AntOffest Z   (m)                2.51430      0.00000      0.00000
Eph.  2006  1 16 11 PRN_2929         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.51430

  139. PRN_3030 AntOffest X   (m)                0.27900      0.00000      0.00000
  140. PRN_3030 AntOffest Y   (m)                             0.00000      0.00000
  141. PRN_3030 AntOffest Z   (m)                2.61270      0.00000      0.00000
Eph.  2006  1 16 11 PRN_3030         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.61270

  142. X-pole position        (mas)             50.35913      0.21113      0.05364
  143. Y-pole position        (mas)            380.31495      0.09495      0.05531

  144. UT1-AT                 (ms)          -32665.96515      0.00885      0.00169
      Pole/UT1 correlations: XY, XU, YU          0.7135    -0.0286     0.0387

IERS  MJD      Xpole   Ypole  UT1-UTC    LOD  Xsig  Ysig   UTsig  LODsig  Nr Nf Nt    Xrt    Yrt  Xrtsig  Yrtsig XYcorr XUTcor YUTcor
IERS             (10**-6")       (0.1 usec)    (10**-6")     (0.1 usec)              (10**-6"/d)    (10**-6"/d)
IERS53751.50   50359  380315  3340348   1290    54    55      17       0  18 12 29    473    270      0      0    0.714 -0.029  0.039


