Globk Analysis

 +++++++++++++++++++++++++++++++++++++
 + GLORG                 Version 5.19 +
 +++++++++++++++++++++++++++++++++++++


 Stabilization with  20.0% constant,  80.0% site dependent weighting.
 Delete sites with   3.0-sigma condition.
 Height variance factor      10.00 Position,     10.00 Velocity
 For Position: Min dH sigma 0.0050 m;    Min RMS 0.0030 m,    Min dNE sigma 0.00050 m
 For Velocity: Min dH sigma 0.0050 m/yr; Min RMS 0.0030 m/yr, Min dNE sigma 0.00010 m/yr
 Sigma Ratio to allow use: Position   3.00 Velocity   3.00

====================================================================================================
 Starting Position stabilization iteration   1 L0001231200_thss.glx
 For   18 sites in origin, min/max height sigma       9.13     42.98 mm; Median       12.23 mm, Tol      15.00 mm L0001231200_thss.glx
 Removing GUAM_GPS from orgin condition, height sigma      42.98 mm, Ratio Tol  3.000 L0001231200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)    -0.39765 +-    0.16755 Iter  1 L0001231200_thss.glx
 Y Rotation  (mas)    -0.17047 +-    0.16882 Iter  1 L0001231200_thss.glx
 Z Rotation  (mas)     0.54773 +-    0.19383 Iter  1 L0001231200_thss.glx
 X Translation (m)    -0.02423 +-    0.00504 Iter  1 L0001231200_thss.glx
 Y Translation (m)    -0.00588 +-    0.00502 Iter  1 L0001231200_thss.glx
 Z Translation (m)    -0.01373 +-    0.00550 Iter  1 L0001231200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   1.00  REYK_GPS   1.00  CRO1_GPS   1.00  AREQ_GPS   1.00  YELL_GPS   1.00  TRAK_GPS   1.00 
HOB2_GPS   1.00  TOW2_GPS   1.00  USUD_GPS   1.00  DAV1_GPS   1.00  POL2_GPS   1.00  KERG_GPS   1.00 
KIRU_GPS   1.00  MATE_GPS   1.00  WTZR_GPS   1.00  NYAL_GPS   1.00  ZIMM_GPS   1.00 
 For   51 Position Iter  1 Pre RMS    0.0184 m; Post RMS   0.01360 m L0001231200_thss.glx
 For   17 sites in origin, min/max NE sigma       1.82      9.92 mm; Median        3.73 mm, Tol       5.74 mm L0001231200_thss.glx
 Removing USUD_GPS from orgin condition, NE sigma       9.92 mm, Ratio Tol  3.000 L0001231200_thss.glx

====================================================================================================
 Starting Position stabilization iteration   2 L0001231200_thss.glx
 For   16 sites in origin, min/max height sigma       9.13     19.26 mm; Median       11.56 mm, Tol      15.00 mm L0001231200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)    -0.59313 +-    0.05284 Iter  2 L0001231200_thss.glx
 Y Rotation  (mas)    -0.07701 +-    0.05490 Iter  2 L0001231200_thss.glx
 Z Rotation  (mas)     0.03764 +-    0.05957 Iter  2 L0001231200_thss.glx
 X Translation (m)    -0.01945 +-    0.00161 Iter  2 L0001231200_thss.glx
 Y Translation (m)    -0.00082 +-    0.00160 Iter  2 L0001231200_thss.glx
 Z Translation (m)    -0.00761 +-    0.00161 Iter  2 L0001231200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   0.79  REYK_GPS   0.70  CRO1_GPS   0.90  AREQ_GPS   1.57  YELL_GPS   0.75  TRAK_GPS   0.89 
HOB2_GPS   0.99  TOW2_GPS   1.28  DAV1_GPS   1.31  POL2_GPS   1.04  KERG_GPS   1.43  KIRU_GPS   0.71 
MATE_GPS   0.84  WTZR_GPS   0.75  NYAL_GPS   0.68  ZIMM_GPS   0.75 
 For   48 Position Iter  2 Pre RMS    0.0092 m; Post RMS   0.00395 m L0001231200_thss.glx
 For   16 sites in origin, min/max NE sigma       1.61      8.63 mm; Median        2.85 mm, Tol       3.71 mm L0001231200_thss.glx
 Removing AREQ_GPS from orgin condition, NE sigma       8.63 mm, Ratio Tol  3.000 L0001231200_thss.glx
 Removing TOW2_GPS from orgin condition, NE sigma       6.59 mm, Ratio Tol  3.000 L0001231200_thss.glx
 Removing DAV1_GPS from orgin condition, NE sigma       7.54 mm, Ratio Tol  3.000 L0001231200_thss.glx
 Removing KERG_GPS from orgin condition, NE sigma       8.60 mm, Ratio Tol  3.000 L0001231200_thss.glx

====================================================================================================
 Starting Position stabilization iteration   3 L0001231200_thss.glx
 For   12 sites in origin, min/max height sigma       9.13     17.39 mm; Median       10.66 mm, Tol      15.00 mm L0001231200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)    -0.52559 +-    0.05900 Iter  3 L0001231200_thss.glx
 Y Rotation  (mas)    -0.00585 +-    0.06422 Iter  3 L0001231200_thss.glx
 Z Rotation  (mas)    -0.02352 +-    0.05370 Iter  3 L0001231200_thss.glx
 X Translation (m)    -0.01731 +-    0.00183 Iter  3 L0001231200_thss.glx
 Y Translation (m)    -0.00253 +-    0.00181 Iter  3 L0001231200_thss.glx
 Z Translation (m)    -0.00811 +-    0.00143 Iter  3 L0001231200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   0.88  REYK_GPS   0.80  CRO1_GPS   1.25  YELL_GPS   0.84  TRAK_GPS   1.13  HOB2_GPS   1.21 
POL2_GPS   1.52  KIRU_GPS   0.80  MATE_GPS   0.92  WTZR_GPS   0.78  NYAL_GPS   0.77  ZIMM_GPS   0.76 
 For   36 Position Iter  3 Pre RMS    0.0065 m; Post RMS   0.00263 m L0001231200_thss.glx
 For   12 sites in origin, min/max NE sigma       1.20      4.17 mm; Median        1.79 mm, Tol       1.78 mm L0001231200_thss.glx
 Removing CRO1_GPS from orgin condition, NE sigma       3.80 mm, Ratio Tol  3.000 L0001231200_thss.glx
 Removing HOB2_GPS from orgin condition, NE sigma       3.70 mm, Ratio Tol  3.000 L0001231200_thss.glx
 Removing POL2_GPS from orgin condition, NE sigma       4.17 mm, Ratio Tol  3.000 L0001231200_thss.glx

====================================================================================================
 Starting Position stabilization iteration   4 L0001231200_thss.glx
 For    9 sites in origin, min/max height sigma       9.42     12.63 mm; Median       10.83 mm, Tol      15.00 mm L0001231200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)    -0.13985 +-    0.14274 Iter  4 L0001231200_thss.glx
 Y Rotation  (mas)     0.18860 +-    0.17041 Iter  4 L0001231200_thss.glx
 Z Rotation  (mas)    -0.05212 +-    0.07039 Iter  4 L0001231200_thss.glx
 X Translation (m)    -0.00677 +-    0.00402 Iter  4 L0001231200_thss.glx
 Y Translation (m)    -0.00671 +-    0.00486 Iter  4 L0001231200_thss.glx
 Z Translation (m)    -0.01326 +-    0.00231 Iter  4 L0001231200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   0.95  REYK_GPS   0.97  YELL_GPS   0.94  TRAK_GPS   1.52  KIRU_GPS   0.97  MATE_GPS   0.97 
WTZR_GPS   0.82  NYAL_GPS   0.89  ZIMM_GPS   0.79 
 For   27 Position Iter  4 Pre RMS    0.0053 m; Post RMS   0.00201 m L0001231200_thss.glx
 For    9 sites in origin, min/max NE sigma       1.04      1.70 mm; Median        1.40 mm, Tol       1.50 mm L0001231200_thss.glx
Rotating into local coordinates for equates
 Checking covariance matrix after equate and force
Globk Analysis


---------------------------------------------------------
 GLOBK Ver 5.29, Global solution
---------------------------------------------------------

 Solution commenced with: 2000/ 1/23  0: 0    (2000.0601)
 Solution ended with    : 2000/ 1/23 23:59    (2000.0628)
 Solution refers to     : 2000/ 1/23 11:59    (2000.0615) [Seconds tag  45.000]
 Satellite IC epoch     : 2000/ 1/23 12: 0  0.00
 GPS System Information : Time GPST Frame J2000 Precession IAU76 Radiation model BERNE Nutation IAU00 Gravity EGM08 EarthRad NONE  AntThrust NONE 
 MODELS Used in Analysis: SD-WOB  | SD-UT1  | IERS10  | E-Tide  | K1-Tide | PoleTide| OC-Load | MPT2010 |  
 ATM Delay Models Used  : GP25    | GP25    | GP25    | GP25    | 2nd Order Ion     | NONE    | UNKNOWN | 
 Reference Frame        : IGb08           
 Run time               : 2015/12/16 23:22  5.00

 There were         1 exps from          1 global files in the solution
 There were       178966 data used,       0 data not used and       178966 data total
 There were          141 global parameters estimated
 There were    18 Sites,   18 Used Sites,    0 radio sources, and   28 Satellites

 The  prefit chi**2 for      54 input parameters is     0.000

 LIST file      : L0001231200_thss.glx
 COMMON file    :  
 GLOBK CMD file : globk_comb.cmd
 GLORG CMD file : glorg_comb.cmd
 APRIORI file   : ../tables/itrf08_comb.apr
 APRIORI file   : ../tables/itrf08_comb.apr (glorg)
 NUTATION file  :  
 PLANETARY file :  
 SD ORIENT file :  
 PMU file       :  
 BACK SOLN file :  
 OUTGLOBAL file : H000123_THSS.GLX
 SVS EPHEM file :  
 SVS MARKOV file:  

* RENAME REPORT (RNRP option)
*   Sites             dN        sN       dE       sE     dU         sU  Units Compare date  EQ Dist EQ Name
* EARTHQUAKE LOG FITS
*  Sites             dN        sN       dE       sE     dU         sU   mm

 Summary of GLOBK command file globk_comb.cmd
-------------------------------------------------------------------------------
* GLOBK command file to generate daily time series and to combine
* h-files over 2 to 30 days.
* For combination, set COMB as a globk command-line option to
* invoke the saving of the output h-file
* Last edited by rwk 130701
* << column 1 must be blank if not comment >>
* This group of commands must appear before any others:
 srt_file @.srt
 srt_dir +1
# Optionally add a second eq_file for analysis-specific renames
* End commands that must appear first
* ITRF2008 augmented by now-defunct sites and recent IGS solutions;
# matched to itrf08_comb.eq
 apr_file ../tables/itrf08_comb.apr
# Optionally add additional apr files for other sites
* Set maximum chi2, prefit coordinate difference (m), and rotation (mas) for an h-file to be used;
 max_chii 13 3 100
# increase tolerances to include all files for diagnostics
# Not necessary unless combining h-files with different a priori EOP
 in_pmu ../tables/pmu.usno
* Invoke glorg
 org_cmd glorg_comb.cmd
* Print file options
 crt_opt NOPR
 prt_opt NOPR GDLF CMDS MIDP
 org_opt PSUM CMDS GDLF MIDP FIXA RNRP
# sh_glred will name the glorg print files
* Coordinate parameters to be estimated and a priori constraints
 apr_neu  all 10 10 10  0 0 0
* Rotation parameters to be estimated and a priori constraints
 apr_wob  10 10 0 0
 apr_ut1  10 0
# If combining with global h-files, allow EOPS to change
# between days
# EOP tight if translation-only stabilization in glorg
* Write out a combined H-file
# Can substitute your analysis name for 'COMB' in the file name below
  out_glb  H------_THSS.GLX
* Optionally put a uselist and/or sig_neu and mar_neu reweight in a source file
* Turn off quake log estimates if in the eq_file
 free_log -1
* Remove scratch files for repeatability runs
  del_scra yes
* Correct the pole tide when not compatible with GAMIT
  app_ptid all
* If orbits free in GAMIT (RELAX) and you want them fixed, use:
* but if you are combining with globk h-files, better to leave them
* on but, if the models are incompatible, turn off radiation-pressure parameters,
* When using MIT GLX files which have satellite phase center positions
* estimated use:
  apr_svan all  F F F     ! Fix antenna offset to IGS apriori values.
-------------------------------------------------------------------------------

 Summary of GLORG command file glorg_comb.cmd
-------------------------------------------------------------------------------
* Glorg command file for daily repeatabilities or combinations
* Last edited by rwk 130701
* Parameters to be estimated
 pos_org  xtran ytran ztran xrot yrot zrot
#   or if translation-only
* Downweight of height relative to horizontal (default is 10)
#   Heavy downweight if reference frame robust and heights suspect
* Controls for removing sites from the stabilization
#   Vary these to make the stabilization more robust or more precise
 stab_it 4 0.8 3.0
* A priori coordinates
#  ITRF2008 may be replaced by an apr file from a priori velocity solution
 apr_file ../tables/itrf08_comb.apr
* List of stabilization sites
#   This should match the well-determined sites in the apr_file
 stab_site clear
 source ../tables/igb08_hierarchy.stab_site
SOURCE ># Sites in IGb08 network hierarchy from ftp://igs-rf.ign.fr/pub/IGb08/IGb08_core.txt
SOURCE ># Created with core2stab_site.sh by Mike Floyd on 2014-08-08
SOURCE > stab_site AREQ
SOURCE > stab_site CRO1
SOURCE > stab_site DAV1
SOURCE > stab_site GUAM
SOURCE > stab_site HOB2
SOURCE > stab_site KERG
SOURCE > stab_site KIRU
SOURCE > stab_site MATE
SOURCE > stab_site NYAL
SOURCE > stab_site POL2
SOURCE > stab_site REYK
SOURCE > stab_site TOW2
SOURCE > stab_site TRAK
SOURCE > stab_site USUD
SOURCE > stab_site VILL
SOURCE > stab_site WTZR
SOURCE > stab_site YELL
SOURCE > stab_site ZIMM
SOURCE > 
SOURCE > 
-------------------------------------------------------------------------------

 EXPERIMENT LIST from L0001231200_thss.srt
     #  Name                               SCALE Diag PPM  Forw Chi2 Back Chi2 Status
     1 ../glbf/h0001231200_thss.glx     1.000000   0.000     0.000    -1.000   USED        

 SUMMARY POSITION ESTIMATES FROM GLOBK Ver 5.29        
    Long.       Lat.        dE adj.   dN adj.   dE +-     dN +-   RHO        dH adj.   dH +-  SITE
    (deg)      (deg)         (mm)      (mm)      (mm)      (mm)               (mm)      (mm)
  356.04802   40.44359       2.26      1.16      1.02      0.95 -0.017       14.47      3.22 VILL_GPS*
  338.04452   64.13878      -0.18     -0.79      1.11      1.28 -0.077        3.86      4.77 REYK_GPS*
  295.41568   17.75690      -0.61     -1.14      2.54      2.26 -0.018        2.59      5.87 CRO1_GPS 
  288.50721  -16.46551       3.17      3.05      4.35      5.42  0.013      -29.30     16.66 AREQ_GPS 
  245.51930   62.48089      -2.93     -0.63      0.73      0.96  0.230        8.91      3.05 YELL_GPS*
  242.19657   33.61793       0.82     -1.32      0.92      1.30 -0.024        5.95      4.52 TRAK_GPS*
  147.43873  -42.80471       6.30     25.45     11.81     16.15 -0.300       20.67     12.96 HOB2_GPS 
  147.05569  -19.26928       3.90     14.31     11.48     11.46 -0.357       33.13     17.07 TOW2_GPS 
  144.86836   13.58933     -11.13     -2.74     10.15      8.09 -0.178       14.70     42.48 GUAM_GPS 
  138.36204   36.13311     118.59    -33.97      7.78      6.58  0.233      -13.43     26.57 USUD_GPS 
   77.97261  -68.57732      37.94     10.95     18.60     15.60  0.445       -4.10     13.22 DAV1_GPS 
   74.69426   42.67977      -3.83     -1.11      2.10      2.18 -0.133        3.89      4.83 POL2_GPS 
   70.25552  -49.35147      37.67     11.93     19.25     13.49  0.351       20.20     13.63 KERG_GPS 
   20.96845   67.85735      -2.46      0.67      0.94      1.33  0.040        5.32      4.73 KIRU_GPS*
   16.70446   40.64913       3.23      1.58      0.92      1.07 -0.088        1.09      3.75 MATE_GPS*
   12.87891   49.14420      -1.83     -2.37      0.81      0.90 -0.119       -6.40      2.69 WTZR_GPS*
   11.86508   78.92958       1.20      1.11      0.81      1.00 -0.081       -0.75      3.99 NYAL_GPS*
    7.46528   46.87710      -0.61     -2.05      0.68      0.79 -0.054       -1.57      2.43 ZIMM_GPS*
POS STATISTICS: For    9 RefSites WRMS ENU   2.00   1.54   7.02  mm    NRMS ENU   2.34   1.52   2.07 L0001231200_thss.glx
POS MEANS: For    9 RefSites: East  -0.31 +-   0.67 North  -0.46 +-   0.51 Up   2.47 +-   2.34 mm L0001231200_thss.glx

 PARAMETER ESTIMATES FROM GLOBK Vers 5.29        
  #      PARAMETER                            Estimate       Adjustment     Sigma
Int. VILL_GPS  4849833.68541  -335049.02412  4116014.92373   -0.01055    0.02001    0.01155 2005.002
    1. VILL_GPS X coordinate  (m)          4849833.74795      0.01042      0.00269
    2. VILL_GPS Y coordinate  (m)          -335049.12143      0.00155      0.00102
    3. VILL_GPS Z coordinate  (m)          4116014.87690      0.01024      0.00201
Unc. VILL_GPS  4849833.74795  -335049.12143  4116014.87690   -0.01055    0.02001    0.01155 2000.061  0.0027  0.0010  0.0020
Apr. VILL_GPS  4849833.74795  -335049.12143  4116014.87690   -0.01055    0.02001    0.01155 2000.061  0.0027  0.0010  0.0020  -1.0000 -1.0000 -1.0000
Loc.   VILL_GPS N coordinate  (m)          4502160.13051      0.00116      0.00095
Loc.   VILL_GPS E coordinate  (m)         30163503.85515      0.00226      0.00102
Loc.   VILL_GPS U coordinate  (m)              647.35281      0.01447      0.00322
     NE,NU,EU position correlations         -0.0168      -0.2686       0.1201
pbo. VILL_GPS VILL_2PS          2000 01 23 11 59 51566.4998   4849833.74795  -335049.12143  4116014.87690 0.00269 0.00102 0.00201 -0.042  0.839 -0.034 |    40.4435925679  356.0480196942  647.35281      8.5    12.1    0.00322 |   4502160.13051 30163503.85515  647.35281 0.00095 0.00102 0.00322 -0.017 -0.269  0.120

Int. REYK_GPS  2587384.32846 -1043033.51334  5716564.04602   -0.01961   -0.00176    0.00895 2005.002
    4. REYK_GPS X coordinate  (m)          2587384.42751      0.00216      0.00234
    5. REYK_GPS Y coordinate  (m)         -1043033.50571     -0.00106      0.00134
    6. REYK_GPS Z coordinate  (m)          5716564.00492      0.00312      0.00428
Unc. REYK_GPS  2587384.42751 -1043033.50571  5716564.00492   -0.01961   -0.00176    0.00895 2000.061  0.0023  0.0013  0.0043
Apr. REYK_GPS  2587384.42751 -1043033.50571  5716564.00492   -0.01961   -0.00176    0.00895 2000.061  0.0023  0.0013  0.0043  -1.0000 -1.0000 -1.0000
Loc.   REYK_GPS N coordinate  (m)          7139896.68655     -0.00079      0.00128
Loc.   REYK_GPS E coordinate  (m)         16413892.74329     -0.00018      0.00111
Loc.   REYK_GPS U coordinate  (m)               93.05057      0.00386      0.00477
     NE,NU,EU position correlations         -0.0773      -0.0661       0.0267
pbo. REYK_GPS REYK_GPS          2000 01 23 11 59 51566.4998   2587384.42751 -1043033.50571  5716564.00492 0.00234 0.00134 0.00428 -0.494  0.796 -0.546 |    64.1387832056  338.0445154565   93.05057     11.5    22.8    0.00477 |   7139896.68655 16413892.74329   93.05057 0.00128 0.00111 0.00477 -0.077 -0.066  0.027

Int. CRO1_GPS  2607771.21531 -5488076.69905  1932767.78997    0.00742    0.00906    0.01252 2005.002
    7. CRO1_GPS X coordinate  (m)          2607771.17930      0.00065      0.00334
    8. CRO1_GPS Y coordinate  (m)         -5488076.74661     -0.00280      0.00487
    9. CRO1_GPS Z coordinate  (m)          1932767.72781     -0.00030      0.00334
Unc. CRO1_GPS  2607771.17930 -5488076.74661  1932767.72781    0.00742    0.00906    0.01252 2000.061  0.0033  0.0049  0.0033
Apr. CRO1_GPS  2607771.17930 -5488076.74661  1932767.72781    0.00742    0.00906    0.01252 2000.061  0.0033  0.0049  0.0033  -1.0000 -1.0000 -1.0000
Loc.   CRO1_GPS N coordinate  (m)          1976688.79949     -0.00114      0.00226
Loc.   CRO1_GPS E coordinate  (m)         31319027.43360     -0.00061      0.00254
Loc.   CRO1_GPS U coordinate  (m)              -31.94277      0.00259      0.00587
     NE,NU,EU position correlations         -0.0184       0.4321       0.0577
pbo. CRO1_GPS CRO1_2PS          2000 01 23 11 59 51566.4998   2607771.17930 -5488076.74661  1932767.72781 0.00334 0.00487 0.00334 -0.558  0.520 -0.727 |    17.7568976053  295.4156797002  -31.94277     20.3    23.9    0.00587 |   1976688.79949 31319027.43360  -31.94277 0.00226 0.00254 0.00587 -0.018  0.432  0.058

Int. AREQ_GPS  1942826.82329 -5804070.23825 -1796893.84451    0.01247    0.00007    0.01400 2005.002
   10. AREQ_GPS X coordinate  (m)          1942826.75603     -0.00565      0.00695
   11. AREQ_GPS Y coordinate  (m)         -5804070.21175      0.02685      0.01597
   12. AREQ_GPS Z coordinate  (m)         -1796893.90249      0.01118      0.00476
Unc. AREQ_GPS  1942826.75603 -5804070.21175 -1796893.90249    0.01247    0.00007    0.01400 2000.061  0.0069  0.0160  0.0048
Apr. AREQ_GPS  1942826.75603 -5804070.21175 -1796893.90249    0.01247    0.00007    0.01400 2000.061  0.0069  0.0160  0.0048  -1.0000 -1.0000 -1.0000
Loc.   AREQ_GPS N coordinate  (m)         -1832932.59818      0.00305      0.00542
Loc.   AREQ_GPS E coordinate  (m)         30799611.49787      0.00317      0.00435
Loc.   AREQ_GPS U coordinate  (m)             2488.88257     -0.02930      0.01666
     NE,NU,EU position correlations          0.0130       0.5410       0.0601
pbo. AREQ_GPS AREQ_GPS          2000 01 23 11 59 51566.4998   1942826.75603 -5804070.21175 -1796893.90249 0.00695 0.01597 0.00476 -0.751 -0.276  0.320 |   -16.4655136771  288.5072086919 2488.88257     48.7    40.8    0.01666 |  -1832932.59818 30799611.49787 2488.88257 0.00542 0.00435 0.01666  0.013  0.541  0.060

Int. YELL_GPS -1224452.50143 -2689216.10746  5633638.27862   -0.02082   -0.00441   -0.00093 1997.002
   13. YELL_GPS X coordinate  (m)         -1224452.56975     -0.00462      0.00108
   14. YELL_GPS Y coordinate  (m)         -2689216.12401     -0.00306      0.00152
   15. YELL_GPS Z coordinate  (m)          5633638.28337      0.00760      0.00269
Unc. YELL_GPS -1224452.56975 -2689216.12401  5633638.28337   -0.02082   -0.00441   -0.00093 2000.061  0.0011  0.0015  0.0027
Apr. YELL_GPS -1224452.56975 -2689216.12401  5633638.28337   -0.02082   -0.00441   -0.00093 2000.061  0.0011  0.0015  0.0027  -1.0000 -1.0000 -1.0000
Loc.   YELL_GPS N coordinate  (m)          6955341.33766     -0.00063      0.00096
Loc.   YELL_GPS E coordinate  (m)         12628197.37618     -0.00293      0.00073
Loc.   YELL_GPS U coordinate  (m)              180.88236      0.00891      0.00305
     NE,NU,EU position correlations          0.2299      -0.0935      -0.1550
pbo. YELL_GPS YELL_3PS          2000 01 23 11 59 51566.4998  -1224452.56975 -2689216.12401  5633638.28337 0.00108 0.00152 0.00269  0.676 -0.583 -0.778 |    62.4808942989  245.5192999926  180.88236      8.6    14.1    0.00305 |   6955341.33766 12628197.37618  180.88236 0.00096 0.00073 0.00305  0.230 -0.094 -0.155

Int. TRAK_GPS -2480029.24905 -4703110.82031  3511298.59513   -0.02924    0.02645    0.01537 2005.002
   16. TRAK_GPS X coordinate  (m)         -2480029.10652     -0.00193      0.00210
   17. TRAK_GPS Y coordinate  (m)         -4703110.95640     -0.00541      0.00336
   18. TRAK_GPS Z coordinate  (m)          3511298.52138      0.00218      0.00269
Unc. TRAK_GPS -2480029.10652 -4703110.95640  3511298.52138   -0.02924    0.02645    0.01537 2000.061  0.0021  0.0034  0.0027
Apr. TRAK_GPS -2480029.10652 -4703110.95640  3511298.52138   -0.02924    0.02645    0.01537 2000.061  0.0021  0.0034  0.0027  -1.0000 -1.0000 -1.0000
Loc.   TRAK_GPS N coordinate  (m)          3742331.27633     -0.00132      0.00130
Loc.   TRAK_GPS E coordinate  (m)         22451843.67581      0.00082      0.00092
Loc.   TRAK_GPS U coordinate  (m)              115.54668      0.00595      0.00452
     NE,NU,EU position correlations         -0.0244      -0.0293      -0.1913
pbo. TRAK_GPS TRAK_GPS          2000 01 23 11 59 51566.4998  -2480029.10652 -4703110.95640  3511298.52138 0.00210 0.00336 0.00269  0.871 -0.778 -0.814 |    33.6179338377  242.1965683804  115.54668     11.6     9.9    0.00452 |   3742331.27633 22451843.67581  115.54668 0.00130 0.00092 0.00452 -0.024 -0.029 -0.191

Int. HOB2_GPS -3950071.67350  2522415.25416 -4311638.02559   -0.03974    0.00862    0.04074 2005.002
   19. HOB2_GPS X coordinate  (m)         -3950071.50790     -0.03073      0.01534
   20. HOB2_GPS Y coordinate  (m)          2522415.22372      0.01215      0.01525
   21. HOB2_GPS Z coordinate  (m)         -4311638.22213      0.00474      0.01002
Unc. HOB2_GPS -3950071.50790  2522415.22372 -4311638.22213   -0.03974    0.00862    0.04074 2000.061  0.0153  0.0152  0.0100
Apr. HOB2_GPS -3950071.50790  2522415.22372 -4311638.22213   -0.03974    0.00862    0.04074 2000.061  0.0153  0.0152  0.0100  -1.0000 -1.0000 -1.0000
Loc.   HOB2_GPS N coordinate  (m)         -4764999.07052      0.02545      0.01615
Loc.   HOB2_GPS E coordinate  (m)         12041419.07852      0.00630      0.01181
Loc.   HOB2_GPS U coordinate  (m)               41.07692      0.02067      0.01296
     NE,NU,EU position correlations         -0.3001       0.5646      -0.0312
pbo. HOB2_GPS HOB2_GPS          2000 01 23 11 59 51566.4998  -3950071.50790  2522415.22372 -4311638.22213 0.01534 0.01525 0.01002 -0.442 -0.171  0.412 |   -42.8047149386  147.4387335560   41.07692    145.1   144.6    0.01296 |  -4764999.07052 12041419.07852   41.07692 0.01615 0.01181 0.01296 -0.300  0.565 -0.031

Int. TOW2_GPS -5054582.94073  3275504.33760 -2091539.27586   -0.03094   -0.01432    0.05283 2005.002
   22. TOW2_GPS X coordinate  (m)         -5054582.82019     -0.03232      0.01544
   23. TOW2_GPS Y coordinate  (m)          3275504.42465      0.01630      0.01519
   24. TOW2_GPS Z coordinate  (m)         -2091539.53421      0.00265      0.00924
Unc. TOW2_GPS -5054582.82019  3275504.42465 -2091539.53421   -0.03094   -0.01432    0.05283 2000.061  0.0154  0.0152  0.0092
Apr. TOW2_GPS -5054582.82019  3275504.42465 -2091539.53421   -0.03094   -0.01432    0.05283 2000.061  0.0154  0.0152  0.0092  -1.0000 -1.0000 -1.0000
Loc.   TOW2_GPS N coordinate  (m)         -2145046.70649      0.01431      0.01146
Loc.   TOW2_GPS E coordinate  (m)         15453122.29813      0.00390      0.01148
Loc.   TOW2_GPS U coordinate  (m)               88.15417      0.03313      0.01707
     NE,NU,EU position correlations         -0.3565       0.5205      -0.1418
pbo. TOW2_GPS TOW2_GPS          2000 01 23 11 59 51566.4998  -5054582.82019  3275504.42465 -2091539.53421 0.01544 0.01519 0.00924 -0.472 -0.044  0.328 |   -19.2692824159  147.0556867503   88.15417    102.9   109.3    0.01707 |  -2145046.70649 15453122.29813   88.15417 0.01146 0.01148 0.01707 -0.357  0.521 -0.142

Int. GUAM_GPS -5071312.73778  3568363.55234  1488904.35997    0.00611    0.00737    0.00522 2005.002
   25. GUAM_GPS X coordinate  (m)         -5071312.77378     -0.00581      0.03397
   26. GUAM_GPS Y coordinate  (m)          3568363.53362      0.01769      0.02570
   27. GUAM_GPS Z coordinate  (m)          1488904.33495      0.00077      0.01255
Unc. GUAM_GPS -5071312.77378  3568363.53362  1488904.33495    0.00611    0.00737    0.00522 2000.061  0.0340  0.0257  0.0126
Apr. GUAM_GPS -5071312.77378  3568363.53362  1488904.33495    0.00611    0.00737    0.00522 2000.061  0.0340  0.0257  0.0126  -1.0000 -1.0000 -1.0000
Loc.   GUAM_GPS N coordinate  (m)          1512757.21531     -0.00274      0.00809
Loc.   GUAM_GPS E coordinate  (m)         15675135.02347     -0.01113      0.01015
Loc.   GUAM_GPS U coordinate  (m)              201.93423      0.01470      0.04248
     NE,NU,EU position correlations         -0.1783      -0.0167      -0.0713
pbo. GUAM_GPS GUAM_2PS          2000 01 23 11 59 51566.4998  -5071312.77378  3568363.53362  1488904.33495 0.03397 0.02570 0.01255 -0.877 -0.718  0.749 |    13.5893292767  144.8683613799  201.93423     72.7    93.8    0.04248 |   1512757.21531 15675135.02347  201.93423 0.00809 0.01015 0.04248 -0.178 -0.017 -0.071

Int. USUD_GPS -3855263.02241  3427432.54860  3741020.34317   -0.00468    0.00390   -0.00211 2005.002
   28. USUD_GPS X coordinate  (m)         -3855263.08486     -0.08557      0.01587
   29. USUD_GPS Y coordinate  (m)          3427432.44673     -0.08260      0.01719
   30. USUD_GPS Z coordinate  (m)          3741020.31821     -0.03538      0.01620
Unc. USUD_GPS -3855263.08486  3427432.44673  3741020.31821   -0.00468    0.00390   -0.00211 2000.061  0.0159  0.0172  0.0162
Apr. USUD_GPS -3855263.08486  3427432.44673  3741020.31821   -0.00468    0.00390   -0.00211 2000.061  0.0159  0.0172  0.0162  -1.0000 -1.0000 -1.0000
Loc.   USUD_GPS N coordinate  (m)          4022319.47493     -0.03397      0.00658
Loc.   USUD_GPS E coordinate  (m)         12439689.21505      0.11859      0.00778
Loc.   USUD_GPS U coordinate  (m)             1508.60443     -0.01343      0.02657
     NE,NU,EU position correlations          0.2329      -0.0557      -0.2391
pbo. USUD_GPS USUD_1PS          2000 01 23 11 59 51566.4998  -3855263.08486  3427432.44673  3741020.31821 0.01587 0.01719 0.01620 -0.796 -0.856  0.796 |    36.1331106194  138.3620448797 1508.60443     59.1    86.5    0.02657 |   4022319.47493 12439689.21505 1508.60443 0.00658 0.00778 0.02657  0.233 -0.056 -0.239

Int. DAV1_GPS   486854.55811  2285099.25423 -5914955.68461    0.00161   -0.00585   -0.00068 2005.002
   31. DAV1_GPS X coordinate  (m)           486854.51485     -0.03530      0.01701
   32. DAV1_GPS Y coordinate  (m)          2285099.29953      0.01640      0.01719
   33. DAV1_GPS Z coordinate  (m)         -5914955.67342      0.00783      0.01339
Unc. DAV1_GPS   486854.51485  2285099.29953 -5914955.67342    0.00161   -0.00585   -0.00068 2000.061  0.0170  0.0172  0.0134
Apr. DAV1_GPS   486854.51485  2285099.29953 -5914955.67342    0.00161   -0.00585   -0.00068 2000.061  0.0170  0.0172  0.0134  -1.0000 -1.0000 -1.0000
Loc.   DAV1_GPS N coordinate  (m)         -7633992.64286      0.01095      0.01560
Loc.   DAV1_GPS E coordinate  (m)          3170252.93737      0.03794      0.01860
Loc.   DAV1_GPS U coordinate  (m)               44.39066     -0.00410      0.01322
     NE,NU,EU position correlations          0.4454       0.0334       0.0792
pbo. DAV1_GPS DAV1_3PS          2000 01 23 11 59 51566.4998    486854.51485  2285099.29953 -5914955.67342 0.01701 0.01719 0.01339 -0.472 -0.109  0.105 |   -68.5773226994   77.9726144954   44.39066    140.2   457.4    0.01322 |  -7633992.64286  3170252.93737   44.39066 0.01560 0.01860 0.01322  0.445  0.033  0.079

Int. POL2_GPS  1239971.36992  4530790.09428  4302578.81606   -0.02731    0.00533    0.00479 2005.002
   34. POL2_GPS X coordinate  (m)          1239971.50949      0.00464      0.00254
   35. POL2_GPS Y coordinate  (m)          4530790.07043      0.00248      0.00304
   36. POL2_GPS Z coordinate  (m)          4302578.79421      0.00181      0.00409
Unc. POL2_GPS  1239971.50949  4530790.07043  4302578.79421   -0.02731    0.00533    0.00479 2000.061  0.0025  0.0030  0.0041
Apr. POL2_GPS  1239971.50949  4530790.07043  4302578.79421   -0.02731    0.00533    0.00479 2000.061  0.0025  0.0030  0.0041  -1.0000 -1.0000 -1.0000
Loc.   POL2_GPS N coordinate  (m)          4751090.24144     -0.00111      0.00218
Loc.   POL2_GPS E coordinate  (m)          6112786.91169     -0.00383      0.00210
Loc.   POL2_GPS U coordinate  (m)             1714.20288      0.00389      0.00483
     NE,NU,EU position correlations         -0.1327       0.3379      -0.4742
pbo. POL2_GPS POL2_GPS          2000 01 23 11 59 51566.4998   1239971.50949  4530790.07043  4302578.79421 0.00254 0.00304 0.00409  0.576  0.584  0.664 |    42.6797698011   74.6942633075 1714.20288     19.6    25.6    0.00483 |   4751090.24144  6112786.91169 1714.20288 0.00218 0.00210 0.00483 -0.133  0.338 -0.474

Int. KERG_GPS  1406337.28912  3918161.09296 -4816167.35661   -0.00527   -0.00015   -0.00151 2005.002
   37. KERG_GPS X coordinate  (m)          1406337.28721     -0.02794      0.01696
   38. KERG_GPS Y coordinate  (m)          3918161.12735      0.03365      0.01717
   39. KERG_GPS Z coordinate  (m)         -4816167.35663     -0.00748      0.01249
Unc. KERG_GPS  1406337.28721  3918161.12735 -4816167.35663   -0.00527   -0.00015   -0.00151 2000.061  0.0170  0.0172  0.0125
Apr. KERG_GPS  1406337.28721  3918161.12735 -4816167.35663   -0.00527   -0.00015   -0.00151 2000.061  0.0170  0.0172  0.0125  -1.0000 -1.0000 -1.0000
Loc.   KERG_GPS N coordinate  (m)         -5493780.13258      0.01193      0.01349
Loc.   KERG_GPS E coordinate  (m)          5094560.98124      0.03767      0.01925
Loc.   KERG_GPS U coordinate  (m)               73.02900      0.02020      0.01363
     NE,NU,EU position correlations          0.3508       0.1547       0.1928
pbo. KERG_GPS KERG_2PS          2000 01 23 11 59 51566.4998   1406337.28721  3918161.12735 -4816167.35663 0.01696 0.01717 0.01249 -0.444 -0.104  0.008 |   -49.3514666069   70.2555222219   73.02900    121.2   265.5    0.01363 |  -5493780.13258  5094560.98124   73.02900 0.01349 0.01925 0.01363  0.351  0.155  0.193

Int. KIRU_GPS  2251420.79504   862817.22093  5885476.70247   -0.01574    0.01076    0.01142 2005.002
   40. KIRU_GPS X coordinate  (m)          2251420.87499      0.00218      0.00205
   41. KIRU_GPS Y coordinate  (m)           862817.16597     -0.00180      0.00126
   42. KIRU_GPS Z coordinate  (m)          5885476.65123      0.00518      0.00439
Unc. KIRU_GPS  2251420.87499   862817.16597  5885476.65123   -0.01574    0.01076    0.01142 2000.061  0.0021  0.0013  0.0044
Apr. KIRU_GPS  2251420.87499   862817.16597  5885476.65123   -0.01574    0.01076    0.01142 2000.061  0.0021  0.0013  0.0044  -1.0000 -1.0000 -1.0000
Loc.   KIRU_GPS N coordinate  (m)          7553845.75214      0.00067      0.00133
Loc.   KIRU_GPS E coordinate  (m)           879764.78812     -0.00246      0.00094
Loc.   KIRU_GPS U coordinate  (m)              390.94663      0.00532      0.00473
     NE,NU,EU position correlations          0.0399      -0.0455       0.2039
pbo. KIRU_GPS KIRU_GPS          2000 01 23 11 59 51566.4998   2251420.87499   862817.16597  5885476.65123 0.00205 0.00126 0.00439  0.608  0.738  0.625 |    67.8573509303   20.9684453565  390.94663     11.9    22.3    0.00473 |   7553845.75214   879764.78812  390.94663 0.00133 0.00094 0.00473  0.040 -0.046  0.204

Int. MATE_GPS  4641949.55683  1393045.42466  4133287.46435   -0.01829    0.01899    0.01495 2005.002
   43. MATE_GPS X coordinate  (m)          4641949.64608     -0.00112      0.00297
   44. MATE_GPS Y coordinate  (m)          1393045.33388      0.00304      0.00133
   45. MATE_GPS Z coordinate  (m)          4133287.39240      0.00191      0.00233
Unc. MATE_GPS  4641949.64608  1393045.33388  4133287.39240   -0.01829    0.01899    0.01495 2000.061  0.0030  0.0013  0.0023
Apr. MATE_GPS  4641949.64608  1393045.33388  4133287.39240   -0.01829    0.01899    0.01495 2000.061  0.0030  0.0013  0.0023  -1.0000 -1.0000 -1.0000
Loc.   MATE_GPS N coordinate  (m)          4525040.54610      0.00158      0.00107
Loc.   MATE_GPS E coordinate  (m)          1410868.89256      0.00323      0.00092
Loc.   MATE_GPS U coordinate  (m)              535.64867      0.00109      0.00375
     NE,NU,EU position correlations         -0.0878      -0.2930       0.1135
pbo. MATE_GPS MATE_4PS          2000 01 23 11 59 51566.4998   4641949.64608  1393045.33388  4133287.39240 0.00297 0.00133 0.00233  0.695  0.848  0.631 |    40.6491308383   16.7044580650  535.64867      9.6    10.9    0.00375 |   4525040.54610  1410868.89256  535.64867 0.00107 0.00092 0.00375 -0.088 -0.293  0.114

Int. WTZR_GPS  4075580.55298   931853.79721  4801568.13598   -0.01605    0.01713    0.01009 2005.002
   46. WTZR_GPS X coordinate  (m)          4075580.63033     -0.00195      0.00195
   47. WTZR_GPS Y coordinate  (m)           931853.71026     -0.00232      0.00097
   48. WTZR_GPS Z coordinate  (m)          4801568.07974     -0.00639      0.00200
Unc. WTZR_GPS  4075580.63033   931853.71026  4801568.07974   -0.01605    0.01713    0.01009 2000.061  0.0019  0.0010  0.0020
Apr. WTZR_GPS  4075580.63033   931853.71026  4801568.07974   -0.01605    0.01713    0.01009 2000.061  0.0019  0.0010  0.0020  -1.0000 -1.0000 -1.0000
Loc.   WTZR_GPS N coordinate  (m)          5470707.06891     -0.00237      0.00090
Loc.   WTZR_GPS E coordinate  (m)           937828.55795     -0.00183      0.00081
Loc.   WTZR_GPS U coordinate  (m)              666.02209     -0.00640      0.00269
     NE,NU,EU position correlations         -0.1192      -0.2006       0.1347
pbo. WTZR_GPS WTZR_GPS          2000 01 23 11 59 51566.4998   4075580.63033   931853.71026  4801568.07974 0.00195 0.00097 0.00200  0.516  0.805  0.457 |    49.1441977494   12.8789083630  666.02209      8.1    11.1    0.00269 |   5470707.06891   937828.55795  666.02209 0.00090 0.00081 0.00269 -0.119 -0.201  0.135

Int. NYAL_GPS  1202430.53162   252626.70891  6237767.61729   -0.01430    0.00750    0.01103 2005.002
   49. NYAL_GPS X coordinate  (m)          1202430.60081     -0.00146      0.00105
   50. NYAL_GPS Y coordinate  (m)           252626.67278      0.00092      0.00087
   51. NYAL_GPS Z coordinate  (m)          6237767.56228     -0.00052      0.00397
Unc. NYAL_GPS  1202430.60081   252626.67278  6237767.56228   -0.01430    0.00750    0.01103 2000.061  0.0010  0.0009  0.0040
Apr. NYAL_GPS  1202430.60081   252626.67278  6237767.56228   -0.01430    0.00750    0.01103 2000.061  0.0010  0.0009  0.0040  -1.0000 -1.0000 -1.0000
Loc.   NYAL_GPS N coordinate  (m)          8786401.11910      0.00111      0.00100
Loc.   NYAL_GPS E coordinate  (m)           253596.94942      0.00120      0.00081
Loc.   NYAL_GPS U coordinate  (m)               78.47136     -0.00075      0.00399
     NE,NU,EU position correlations         -0.0807       0.2395       0.1949
pbo. NYAL_GPS NYAL_2PS          2000 01 23 11 59 51566.4998   1202430.60081   252626.67278  6237767.56228 0.00105 0.00087 0.00397  0.306  0.429  0.289 |    78.9295841769   11.8650842061   78.47136      9.0    37.8    0.00399 |   8786401.11910   253596.94942   78.47136 0.00100 0.00081 0.00399 -0.081  0.240  0.195

Int. ZIMM_GPS  4331297.06286   567555.87751  4633133.93566   -0.01353    0.01807    0.01205 2005.002
   52. ZIMM_GPS X coordinate  (m)          4331297.13019      0.00049      0.00187
   53. ZIMM_GPS Y coordinate  (m)           567555.78769     -0.00055      0.00074
   54. ZIMM_GPS Z coordinate  (m)          4633133.87357     -0.00255      0.00172
Unc. ZIMM_GPS  4331297.13019   567555.78769  4633133.87357   -0.01353    0.01807    0.01205 2000.061  0.0019  0.0007  0.0017
Apr. ZIMM_GPS  4331297.13019   567555.78769  4633133.87357   -0.01353    0.01807    0.01205 2000.061  0.0019  0.0007  0.0017  -1.0000 -1.0000 -1.0000
Loc.   ZIMM_GPS N coordinate  (m)          5218334.54481     -0.00205      0.00079
Loc.   ZIMM_GPS E coordinate  (m)           568072.07083     -0.00061      0.00068
Loc.   ZIMM_GPS U coordinate  (m)              956.32432     -0.00157      0.00243
     NE,NU,EU position correlations         -0.0542      -0.2509       0.0904
pbo. ZIMM_GPS ZIMM_2PS          2000 01 23 11 59 51566.4998   4331297.13019   567555.78769  4633133.87357 0.00187 0.00074 0.00172  0.378  0.820  0.343 |    46.8770967925    7.4652755001  956.32432      7.1     8.9    0.00243 |   5218334.54481   568072.07083  956.32432 0.00079 0.00068 0.00243 -0.054 -0.251  0.090

Eph. #IC  0  23 12  0  0                    GPST J2000 IAU76 BERNE
   55. PRN_0132 AntOffest X   (m)                0.27900      0.00000      0.00000
   56. PRN_0132 AntOffest Y   (m)                             0.00000      0.00000
   57. PRN_0132 AntOffest Z   (m)                2.38080      0.00000      0.00000
Eph.  2000  1 23 11 PRN_0132         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.38080

   58. PRN_0213 AntOffest X   (m)                0.27900      0.00000      0.00000
   59. PRN_0213 AntOffest Y   (m)                             0.00000      0.00000
   60. PRN_0213 AntOffest Z   (m)                2.71220      0.00000      0.00000
Eph.  2000  1 23 11 PRN_0213         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.71220

   61. PRN_0333 AntOffest X   (m)                0.27900      0.00000      0.00000
   62. PRN_0333 AntOffest Y   (m)                             0.00000      0.00000
   63. PRN_0333 AntOffest Z   (m)                2.79260      0.00000      0.00000
Eph.  2000  1 23 11 PRN_0333         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.79260

   64. PRN_0434 AntOffest X   (m)                0.27900      0.00000      0.00000
   65. PRN_0434 AntOffest Y   (m)                             0.00000      0.00000
   66. PRN_0434 AntOffest Z   (m)                2.42000      0.00000      0.00000
Eph.  2000  1 23 11 PRN_0434         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.42000

   67. PRN_0535 AntOffest X   (m)                0.27900      0.00000      0.00000
   68. PRN_0535 AntOffest Y   (m)                             0.00000      0.00000
   69. PRN_0535 AntOffest Z   (m)                2.62200      0.00000      0.00000
Eph.  2000  1 23 11 PRN_0535         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.62200

   70. PRN_0636 AntOffest X   (m)                0.27900      0.00000      0.00000
   71. PRN_0636 AntOffest Y   (m)                             0.00000      0.00000
   72. PRN_0636 AntOffest Z   (m)                2.87860      0.00000      0.00000
Eph.  2000  1 23 11 PRN_0636         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.87860

   73. PRN_0737 AntOffest X   (m)                0.27900      0.00000      0.00000
   74. PRN_0737 AntOffest Y   (m)                             0.00000      0.00000
   75. PRN_0737 AntOffest Z   (m)                2.35220      0.00000      0.00000
Eph.  2000  1 23 11 PRN_0737         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.35220

   76. PRN_0838 AntOffest X   (m)                0.27900      0.00000      0.00000
   77. PRN_0838 AntOffest Y   (m)                             0.00000      0.00000
   78. PRN_0838 AntOffest Z   (m)                2.57810      0.00000      0.00000
Eph.  2000  1 23 11 PRN_0838         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.57810

   79. PRN_0939 AntOffest X   (m)                0.27900      0.00000      0.00000
   80. PRN_0939 AntOffest Y   (m)                             0.00000      0.00000
   81. PRN_0939 AntOffest Z   (m)                2.46140      0.00000      0.00000
Eph.  2000  1 23 11 PRN_0939         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.46140

   82. PRN_1040 AntOffest X   (m)                0.27900      0.00000      0.00000
   83. PRN_1040 AntOffest Y   (m)                             0.00000      0.00000
   84. PRN_1040 AntOffest Z   (m)                2.54650      0.00000      0.00000
Eph.  2000  1 23 11 PRN_1040         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.54650

   85. PRN_1146 AntOffest X   (m)                             0.00000      0.00000
   86. PRN_1146 AntOffest Y   (m)                             0.00000      0.00000
   87. PRN_1146 AntOffest Z   (m)                1.14130      0.00000      0.00000
Eph.  2000  1 23 11 PRN_1146         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.14130

   88. PRN_1343 AntOffest X   (m)                             0.00000      0.00000
   89. PRN_1343 AntOffest Y   (m)                             0.00000      0.00000
   90. PRN_1343 AntOffest Z   (m)                1.38950      0.00000      0.00000
Eph.  2000  1 23 11 PRN_1343         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.38950

   91. PRN_1414 AntOffest X   (m)                0.27900      0.00000      0.00000
   92. PRN_1414 AntOffest Y   (m)                             0.00000      0.00000
   93. PRN_1414 AntOffest Z   (m)                2.84950      0.00000      0.00000
Eph.  2000  1 23 11 PRN_1414         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.84950

   94. PRN_1515 AntOffest X   (m)                0.27900      0.00000      0.00000
   95. PRN_1515 AntOffest Y   (m)                             0.00000      0.00000
   96. PRN_1515 AntOffest Z   (m)                2.46860      0.00000      0.00000
Eph.  2000  1 23 11 PRN_1515         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.46860

   97. PRN_1616 AntOffest X   (m)                0.27900      0.00000      0.00000
   98. PRN_1616 AntOffest Y   (m)                             0.00000      0.00000
   99. PRN_1616 AntOffest Z   (m)                2.52110      0.00000      0.00000
Eph.  2000  1 23 11 PRN_1616         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.52110

  100. PRN_1717 AntOffest X   (m)                0.27900      0.00000      0.00000
  101. PRN_1717 AntOffest Y   (m)                             0.00000      0.00000
  102. PRN_1717 AntOffest Z   (m)                2.42280      0.00000      0.00000
Eph.  2000  1 23 11 PRN_1717         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.42280

  103. PRN_1818 AntOffest X   (m)                0.27900      0.00000      0.00000
  104. PRN_1818 AntOffest Y   (m)                             0.00000      0.00000
  105. PRN_1818 AntOffest Z   (m)                2.58180      0.00000      0.00000
Eph.  2000  1 23 11 PRN_1818         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.58180

  106. PRN_1919 AntOffest X   (m)                0.27900      0.00000      0.00000
  107. PRN_1919 AntOffest Y   (m)                             0.00000      0.00000
  108. PRN_1919 AntOffest Z   (m)                2.97160      0.00000      0.00000
Eph.  2000  1 23 11 PRN_1919         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.97160

  109. PRN_2121 AntOffest X   (m)                0.27900      0.00000      0.00000
  110. PRN_2121 AntOffest Y   (m)                             0.00000      0.00000
  111. PRN_2121 AntOffest Z   (m)                2.52390      0.00000      0.00000
Eph.  2000  1 23 11 PRN_2121         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.52390

  112. PRN_2222 AntOffest X   (m)                0.27900      0.00000      0.00000
  113. PRN_2222 AntOffest Y   (m)                             0.00000      0.00000
  114. PRN_2222 AntOffest Z   (m)                2.45140      0.00000      0.00000
Eph.  2000  1 23 11 PRN_2222         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.45140

  115. PRN_2323 AntOffest X   (m)                0.27900      0.00000      0.00000
  116. PRN_2323 AntOffest Y   (m)                             0.00000      0.00000
  117. PRN_2323 AntOffest Z   (m)                2.77720      0.00000      0.00000
Eph.  2000  1 23 11 PRN_2323         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.77720

  118. PRN_2424 AntOffest X   (m)                0.27900      0.00000      0.00000
  119. PRN_2424 AntOffest Y   (m)                             0.00000      0.00000
  120. PRN_2424 AntOffest Z   (m)                2.60380      0.00000      0.00000
Eph.  2000  1 23 11 PRN_2424         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.60380

  121. PRN_2525 AntOffest X   (m)                0.27900      0.00000      0.00000
  122. PRN_2525 AntOffest Y   (m)                             0.00000      0.00000
  123. PRN_2525 AntOffest Z   (m)                2.48900      0.00000      0.00000
Eph.  2000  1 23 11 PRN_2525         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.48900

  124. PRN_2626 AntOffest X   (m)                0.27900      0.00000      0.00000
  125. PRN_2626 AntOffest Y   (m)                             0.00000      0.00000
  126. PRN_2626 AntOffest Z   (m)                2.45940      0.00000      0.00000
Eph.  2000  1 23 11 PRN_2626         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.45940

  127. PRN_2727 AntOffest X   (m)                0.27900      0.00000      0.00000
  128. PRN_2727 AntOffest Y   (m)                             0.00000      0.00000
  129. PRN_2727 AntOffest Z   (m)                2.63340      0.00000      0.00000
Eph.  2000  1 23 11 PRN_2727         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.63340

  130. PRN_2929 AntOffest X   (m)                0.27900      0.00000      0.00000
  131. PRN_2929 AntOffest Y   (m)                             0.00000      0.00000
  132. PRN_2929 AntOffest Z   (m)                2.51430      0.00000      0.00000
Eph.  2000  1 23 11 PRN_2929         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.51430

  133. PRN_3030 AntOffest X   (m)                0.27900      0.00000      0.00000
  134. PRN_3030 AntOffest Y   (m)                             0.00000      0.00000
  135. PRN_3030 AntOffest Z   (m)                2.61270      0.00000      0.00000
Eph.  2000  1 23 11 PRN_3030         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.61270

  136. PRN_3131 AntOffest X   (m)                0.27900      0.00000      0.00000
  137. PRN_3131 AntOffest Y   (m)                             0.00000      0.00000
  138. PRN_3131 AntOffest Z   (m)                2.25650      0.00000      0.00000
Eph.  2000  1 23 11 PRN_3131         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.25650

  139. X-pole position        (mas)             55.93794     -0.18006      0.08848
  140. Y-pole position        (mas)            377.27938      0.20438      0.09628

  141. UT1-AT                 (ms)          -31662.58968     -0.00268      0.00305
      Pole/UT1 correlations: XY, XU, YU         -0.0586    -0.3852     0.5370

IERS  MJD      Xpole   Ypole  UT1-UTC    LOD  Xsig  Ysig   UTsig  LODsig  Nr Nf Nt    Xrt    Yrt  Xrtsig  Yrtsig XYcorr XUTcor YUTcor
IERS             (10**-6")       (0.1 usec)    (10**-6")     (0.1 usec)              (10**-6"/d)    (10**-6"/d)
IERS51566.50   55938  377279  3374103  11570    88    96      31       0  18  9 28    448    410      0      0   -0.059 -0.385  0.537


