Globk Analysis

 +++++++++++++++++++++++++++++++++++++
 + GLORG                 Version 5.19 +
 +++++++++++++++++++++++++++++++++++++


 Stabilization with  20.0% constant,  80.0% site dependent weighting.
 Delete sites with   3.0-sigma condition.
 Height variance factor      10.00 Position,     10.00 Velocity
 For Position: Min dH sigma 0.0050 m;    Min RMS 0.0030 m,    Min dNE sigma 0.00050 m
 For Velocity: Min dH sigma 0.0050 m/yr; Min RMS 0.0030 m/yr, Min dNE sigma 0.00010 m/yr
 Sigma Ratio to allow use: Position   3.00 Velocity   3.00

====================================================================================================
 Starting Position stabilization iteration   1 L1201301200_thss.glx
 For   18 sites in origin, min/max height sigma       7.10      9.92 mm; Median        8.49 mm, Tol      15.00 mm L1201301200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)    -1.55358 +-    1.10045 Iter  1 L1201301200_thss.glx
 Y Rotation  (mas)    -1.11144 +-    1.13797 Iter  1 L1201301200_thss.glx
 Z Rotation  (mas)    -1.53550 +-    1.23120 Iter  1 L1201301200_thss.glx
 X Translation (m)    -0.12892 +-    0.03385 Iter  1 L1201301200_thss.glx
 Y Translation (m)     0.00306 +-    0.03299 Iter  1 L1201301200_thss.glx
 Z Translation (m)    -0.04720 +-    0.03522 Iter  1 L1201301200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   1.00  REYK_GPS   1.00  CRO1_GPS   1.00  AREQ_GPS   1.00  YELL_GPS   1.00  TRAK_GPS   1.00 
HOB2_GPS   1.00  TOW2_GPS   1.00  GUAM_GPS   1.00  USUD_GPS   1.00  DAV1_GPS   1.00  POL2_GPS   1.00 
KERG_GPS   1.00  KIRU_GPS   1.00  MATE_GPS   1.00  WTZR_GPS   1.00  NYAL_GPS   1.00  ZIMM_GPS   1.00 
 For   54 Position Iter  1 Pre RMS    0.1062 m; Post RMS   0.09215 m L1201301200_thss.glx
 For   18 sites in origin, min/max NE sigma       1.25      3.40 mm; Median        1.90 mm, Tol       1.95 mm L1201301200_thss.glx
Deleting AREQ_GPS Position error   0.6451 m, relative variance     1.80 Nsigma     5.21
Deleting USUD_GPS Position error   0.3435 m, relative variance     1.01 Nsigma     3.72

====================================================================================================
 Starting Position stabilization iteration   2 L1201301200_thss.glx
 For   16 sites in origin, min/max height sigma       7.10      9.92 mm; Median        8.49 mm, Tol      15.00 mm L1201301200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)     0.15785 +-    0.08150 Iter  2 L1201301200_thss.glx
 Y Rotation  (mas)     0.07500 +-    0.09039 Iter  2 L1201301200_thss.glx
 Z Rotation  (mas)    -0.00419 +-    0.09272 Iter  2 L1201301200_thss.glx
 X Translation (m)    -0.02661 +-    0.00263 Iter  2 L1201301200_thss.glx
 Y Translation (m)    -0.00094 +-    0.00246 Iter  2 L1201301200_thss.glx
 Z Translation (m)     0.01118 +-    0.00254 Iter  2 L1201301200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   0.84  REYK_GPS   0.84  CRO1_GPS   1.04  YELL_GPS   0.89  TRAK_GPS   0.94  HOB2_GPS   1.07 
TOW2_GPS   1.10  GUAM_GPS   1.13  DAV1_GPS   1.19  POL2_GPS   0.90  KERG_GPS   1.39  KIRU_GPS   0.80 
MATE_GPS   0.81  WTZR_GPS   0.81  NYAL_GPS   0.83  ZIMM_GPS   0.76 
 For   48 Position Iter  2 Pre RMS    0.0167 m; Post RMS   0.00612 m L1201301200_thss.glx
 For   16 sites in origin, min/max NE sigma       0.99      3.73 mm; Median        1.69 mm, Tol       2.10 mm L1201301200_thss.glx
Deleting REYK_GPS Position error   0.0220 m, relative variance     0.71 Nsigma     4.27

====================================================================================================
 Starting Position stabilization iteration   3 L1201301200_thss.glx
 For   15 sites in origin, min/max height sigma       7.10      9.92 mm; Median        8.37 mm, Tol      15.00 mm L1201301200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)     0.12403 +-    0.06976 Iter  3 L1201301200_thss.glx
 Y Rotation  (mas)     0.10981 +-    0.07960 Iter  3 L1201301200_thss.glx
 Z Rotation  (mas)     0.01184 +-    0.07924 Iter  3 L1201301200_thss.glx
 X Translation (m)    -0.02525 +-    0.00230 Iter  3 L1201301200_thss.glx
 Y Translation (m)    -0.00042 +-    0.00212 Iter  3 L1201301200_thss.glx
 Z Translation (m)     0.01219 +-    0.00218 Iter  3 L1201301200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   0.80  CRO1_GPS   1.15  YELL_GPS   0.87  TRAK_GPS   0.94  HOB2_GPS   1.02  TOW2_GPS   1.12 
GUAM_GPS   1.24  DAV1_GPS   1.28  POL2_GPS   0.90  KERG_GPS   1.56  KIRU_GPS   0.79  MATE_GPS   0.75 
WTZR_GPS   0.77  NYAL_GPS   0.83  ZIMM_GPS   0.71 
 For   45 Position Iter  3 Pre RMS    0.0158 m; Post RMS   0.00515 m L1201301200_thss.glx
 For   15 sites in origin, min/max NE sigma       0.93      3.92 mm; Median        1.69 mm, Tol       2.28 mm L1201301200_thss.glx
Deleting TOW2_GPS Position error   0.0178 m, relative variance     1.16 Nsigma     3.22
Deleting GUAM_GPS Position error   0.0220 m, relative variance     1.53 Nsigma     3.44

====================================================================================================
 Starting Position stabilization iteration   4 L1201301200_thss.glx
 For   13 sites in origin, min/max height sigma       7.10      9.92 mm; Median        8.30 mm, Tol      15.00 mm L1201301200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)     0.13204 +-    0.06697 Iter  4 L1201301200_thss.glx
 Y Rotation  (mas)     0.11692 +-    0.07048 Iter  4 L1201301200_thss.glx
 Z Rotation  (mas)    -0.02562 +-    0.07547 Iter  4 L1201301200_thss.glx
 X Translation (m)    -0.02473 +-    0.00206 Iter  4 L1201301200_thss.glx
 Y Translation (m)     0.00002 +-    0.00203 Iter  4 L1201301200_thss.glx
 Z Translation (m)     0.01219 +-    0.00205 Iter  4 L1201301200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   0.78  CRO1_GPS   1.15  YELL_GPS   0.85  TRAK_GPS   0.91  HOB2_GPS   0.95  DAV1_GPS   1.32 
POL2_GPS   0.88  KERG_GPS   1.59  KIRU_GPS   0.78  MATE_GPS   0.73  WTZR_GPS   0.75  NYAL_GPS   0.82 
ZIMM_GPS   0.70 
 For   39 Position Iter  4 Pre RMS    0.0165 m; Post RMS   0.00444 m L1201301200_thss.glx
 For   13 sites in origin, min/max NE sigma       0.91      3.65 mm; Median        1.55 mm, Tol       1.91 mm L1201301200_thss.glx
 Removing KERG_GPS from orgin condition, NE sigma       3.65 mm, Ratio Tol  3.000 L1201301200_thss.glx
Rotating into local coordinates for equates
 Checking covariance matrix after equate and force
Globk Analysis


---------------------------------------------------------
 GLOBK Ver 5.29, Global solution
---------------------------------------------------------

 Solution commenced with: 2012/ 1/30  0: 0    (2012.0792)
 Solution ended with    : 2012/ 1/30 23:59    (2012.0820)
 Solution refers to     : 2012/ 1/30 11:59    (2012.0806) [Seconds tag  45.000]
 Satellite IC epoch     : 2012/ 1/30 12: 0  0.00
 GPS System Information : Time GPST Frame J2000 Precession IAU76 Radiation model BERNE Nutation IAU00 Gravity EGM08 EarthRad NONE  AntThrust NONE 
 MODELS Used in Analysis: SD-WOB  | SD-UT1  | IERS10  | E-Tide  | K1-Tide | PoleTide| OC-Load | MPT2010 |  
 ATM Delay Models Used  : GP25    | GP25    | GP25    | GP25    | 2nd Order Ion     | NONE    | UNKNOWN | 
 Reference Frame        : IGb08           
 Run time               : 2015/12/18 15:49 24.00

 There were         1 exps from          1 global files in the solution
 There were       268102 data used,       0 data not used and       268102 data total
 There were          150 global parameters estimated
 There were    18 Sites,   18 Used Sites,    0 radio sources, and   31 Satellites

 The  prefit chi**2 for      54 input parameters is     0.000

 LIST file      : L1201301200_thss.glx
 COMMON file    :  
 GLOBK CMD file : globk_comb.cmd
 GLORG CMD file : glorg_comb.cmd
 APRIORI file   : ../tables/itrf08_comb.apr
 APRIORI file   : ../tables/itrf08_comb.apr (glorg)
 NUTATION file  :  
 PLANETARY file :  
 SD ORIENT file :  
 PMU file       :  
 BACK SOLN file :  
 OUTGLOBAL file :  
 SVS EPHEM file :  
 SVS MARKOV file:  

* RENAME REPORT (RNRP option)
*   Sites             dN        sN       dE       sE     dU         sU  Units Compare date  EQ Dist EQ Name
* EARTHQUAKE LOG FITS
*  Sites             dN        sN       dE       sE     dU         sU   mm

 Summary of GLOBK command file globk_comb.cmd
-------------------------------------------------------------------------------
* GLOBK command file to generate daily time series and to combine
* h-files over 2 to 30 days.
* For combination, set COMB as a globk command-line option to
* invoke the saving of the output h-file
* Last edited by rwk 130701
* << column 1 must be blank if not comment >>
* This group of commands must appear before any others:
 srt_file @.srt
 srt_dir +1
# Optionally add a second eq_file for analysis-specific renames
* End commands that must appear first
* ITRF2008 augmented by now-defunct sites and recent IGS solutions;
# matched to itrf08_comb.eq
 apr_file ../tables/itrf08_comb.apr
# Optionally add additional apr files for other sites
* Set maximum chi2, prefit coordinate difference (m), and rotation (mas) for an h-file to be used;
 max_chii 13 3 100
# increase tolerances to include all files for diagnostics
# Not necessary unless combining h-files with different a priori EOP
 in_pmu ../tables/pmu.usno
* Invoke glorg
 org_cmd glorg_comb.cmd
* Print file options
 crt_opt NOPR
 prt_opt NOPR GDLF CMDS MIDP
 org_opt PSUM CMDS GDLF MIDP FIXA RNRP
# sh_glred will name the glorg print files
* Coordinate parameters to be estimated and a priori constraints
 apr_neu  all 10 10 10  0 0 0
* Rotation parameters to be estimated and a priori constraints
 apr_wob  5 5 0 0
 apr_ut1  5 0
# If combining with global h-files, allow EOPS to change
# between days
# EOP tight if translation-only stabilization in glorg
* Write out a combined H-file
# Can substitute your analysis name for 'COMB' in the file name below
COMB out_glb  H------_COMB.GLX
* Optionally put a uselist and/or sig_neu and mar_neu reweight in a source file
* Turn off quake log estimates if in the eq_file
 free_log -1
* Remove scratch files for repeatability runs
  del_scra yes
* Correct the pole tide when not compatible with GAMIT
  app_ptid all
* If orbits free in GAMIT (RELAX) and you want them fixed, use:
* but if you are combining with globk h-files, better to leave them
* on but, if the models are incompatible, turn off radiation-pressure parameters,
* When using MIT GLX files which have satellite phase center positions
* estimated use:
  apr_svan all  F F F     ! Fix antenna offset to IGS apriori values.
-------------------------------------------------------------------------------

 Summary of GLORG command file glorg_comb.cmd
-------------------------------------------------------------------------------
* Glorg command file for daily repeatabilities or combinations
* Last edited by rwk 130701
* Parameters to be estimated
 pos_org  xtran ytran ztran xrot yrot zrot
#   or if translation-only
* Downweight of height relative to horizontal (default is 10)
#   Heavy downweight if reference frame robust and heights suspect
* Controls for removing sites from the stabilization
#   Vary these to make the stabilization more robust or more precise
 stab_it 4 0.8 3.0
* A priori coordinates
#  ITRF2008 may be replaced by an apr file from a priori velocity solution
 apr_file ../tables/itrf08_comb.apr
* List of stabilization sites
#   This should match the well-determined sites in the apr_file
 stab_site clear
 source ../tables/igb08_hierarchy.stab_site
SOURCE ># Sites in IGb08 network hierarchy from ftp://igs-rf.ign.fr/pub/IGb08/IGb08_core.txt
SOURCE ># Created with core2stab_site.sh by Mike Floyd on 2014-08-08
SOURCE > stab_site AREQ
SOURCE > stab_site CRO1
SOURCE > stab_site DAV1
SOURCE > stab_site GUAM
SOURCE > stab_site HOB2
SOURCE > stab_site KERG
SOURCE > stab_site KIRU
SOURCE > stab_site MATE
SOURCE > stab_site NYAL
SOURCE > stab_site POL2
SOURCE > stab_site REYK
SOURCE > stab_site TOW2
SOURCE > stab_site TRAK
SOURCE > stab_site USUD
SOURCE > stab_site VILL
SOURCE > stab_site WTZR
SOURCE > stab_site YELL
SOURCE > stab_site ZIMM
SOURCE > 
SOURCE > 
-------------------------------------------------------------------------------

 EXPERIMENT LIST from L1201301200_thss.srt
     #  Name                               SCALE Diag PPM  Forw Chi2 Back Chi2 Status
     1 ../glbf/h1201301200_thss.glx     1.000000   0.000     0.000    -1.000   USED        

 SUMMARY POSITION ESTIMATES FROM GLOBK Ver 5.29        
    Long.       Lat.        dE adj.   dN adj.   dE +-     dN +-   RHO        dH adj.   dH +-  SITE
    (deg)      (deg)         (mm)      (mm)      (mm)      (mm)               (mm)      (mm)
  356.04802   40.44359      -2.19      1.71      0.87      0.97  0.042       16.20      3.65 VILL_GPS*
  338.04451   64.13879     -21.95      9.43      1.09      1.33 -0.005      -21.91      3.79 REYK_GPS 
  295.41568   17.75690       5.43     -4.40      1.80      1.80  0.146        0.67      6.35 CRO1_GPS*
  288.50720  -16.46552    -691.66   -476.21      2.46      3.36  0.250       -9.23      6.77 AREQ_GPS 
  245.51930   62.48089      -0.85     10.76      1.07      1.11  0.003       19.26      3.54 YELL_GPS*
  242.19656   33.61794      -2.09     -8.33      1.23      1.18  0.123      -10.37      4.05 TRAK_GPS*
  147.43874  -42.80471       5.52      0.18      1.21      1.62  0.405       -6.64      5.87 HOB2_GPS*
  147.05569  -19.26928       0.53     16.45      1.71      2.88  0.228      -27.43      5.70 TOW2_GPS 
  144.86836   13.58933      12.05    -18.49      1.91      3.15 -0.091      -10.05      6.91 GUAM_GPS 
  138.36205   36.13311     362.15     22.42      1.52      2.59 -0.102      -24.53      4.46 USUD_GPS 
   77.97261  -68.57732      -7.10      2.01      2.36      1.39  0.131        4.95      5.87 DAV1_GPS*
   74.69427   42.67977      -6.30      6.51      1.13      1.36 -0.099      -22.22      3.12 POL2_GPS*
   70.25552  -49.35147      11.77      6.16      2.86      2.27 -0.402       -9.08      7.58 KERG_GPS 
   20.96845   67.85735       2.09      2.65      0.85      1.02  0.022      -16.16      3.46 KIRU_GPS*
   16.70446   40.64913      -2.23      1.37      0.74      0.76 -0.078       -1.69      2.98 MATE_GPS*
   12.87891   49.14420       3.63     -2.14      0.79      0.89  0.019      -24.03      3.32 WTZR_GPS*
   11.86509   78.92959       5.06     -3.37      0.99      1.13  0.029      -10.23      4.82 NYAL_GPS*
    7.46528   46.87710      -1.59      1.11      0.61      0.68  0.010        0.79      2.60 ZIMM_GPS*
POS STATISTICS: For   12 RefSites WRMS ENU   3.34   4.26  14.61  mm    NRMS ENU   3.53   4.13   3.95 L1201301200_thss.glx
POS MEANS: For   12 RefSites: East  -0.01 +-   0.96 North   0.88 +-   1.23 Up  -4.82 +-   4.22 mm L1201301200_thss.glx

 PARAMETER ESTIMATES FROM GLOBK Vers 5.29        
  #      PARAMETER                            Estimate       Adjustment     Sigma
Int. VILL_GPS  4849833.68541  -335049.02412  4116014.92373   -0.01055    0.02001    0.01155 2005.002
    1. VILL_GPS X coordinate  (m)          4849833.62181      0.01108      0.00283
    2. VILL_GPS Y coordinate  (m)          -335048.88543     -0.00296      0.00087
    3. VILL_GPS Z coordinate  (m)          4116015.01726      0.01178      0.00250
Unc. VILL_GPS  4849833.62181  -335048.88543  4116015.01726   -0.01055    0.02001    0.01155 2012.081  0.0028  0.0009  0.0025
Apr. VILL_GPS  4849833.62181  -335048.88543  4116015.01726   -0.01055    0.02001    0.01155 2012.081  0.0028  0.0009  0.0025  -1.0000 -1.0000 -1.0000
Loc.   VILL_GPS N coordinate  (m)          4502160.32999      0.00171      0.00097
Loc.   VILL_GPS E coordinate  (m)         30163504.08155     -0.00219      0.00087
Loc.   VILL_GPS U coordinate  (m)              647.33571      0.01620      0.00365
     NE,NU,EU position correlations          0.0420       0.0368       0.0823
pbo. VILL_GPS ----------------  2012 01 30 11 59 55956.4998   4849833.62181  -335048.88543  4116015.01726 0.00283 0.00087 0.00250 -0.132  0.867 -0.105 |    40.4435943599  356.0480223666  647.33571      8.7    10.2    0.00365 |   4502160.32999 30163504.08155  647.33571 0.00097 0.00087 0.00365  0.042  0.037  0.082

Int. REYK_GPS  2587384.32846 -1043033.51334  5716564.04602   -0.01961   -0.00176    0.00895 2005.002
    4. REYK_GPS X coordinate  (m)          2587384.16466     -0.02498      0.00194
    5. REYK_GPS Y coordinate  (m)         -1043033.53939     -0.01359      0.00121
    6. REYK_GPS Z coordinate  (m)          5716564.09382     -0.01555      0.00347
Unc. REYK_GPS  2587384.16466 -1043033.53939  5716564.09382   -0.01961   -0.00176    0.00895 2012.081  0.0019  0.0012  0.0035
Apr. REYK_GPS  2587384.16466 -1043033.53939  5716564.09382   -0.01961   -0.00176    0.00895 2012.081  0.0019  0.0012  0.0035  -1.0000 -1.0000 -1.0000
Loc.   REYK_GPS N coordinate  (m)          7139896.93300      0.00943      0.00133
Loc.   REYK_GPS E coordinate  (m)         16413892.61413     -0.02195      0.00109
Loc.   REYK_GPS U coordinate  (m)               93.02972     -0.02191      0.00379
     NE,NU,EU position correlations         -0.0053       0.0316       0.0925
pbo. REYK_GPS ----------------  2012 01 30 11 59 55956.4998   2587384.16466 -1043033.53939  5716564.09382 0.00194 0.00121 0.00347 -0.370  0.686 -0.357 |    64.1387854196  338.0445127965   93.02972     12.0    22.4    0.00379 |   7139896.93300 16413892.61413   93.02972 0.00133 0.00109 0.00379 -0.005  0.032  0.092

Int. CRO1_GPS  2607771.21531 -5488076.69905  1932767.78997    0.00742    0.00906    0.01252 2005.002
    7. CRO1_GPS X coordinate  (m)          2607771.27359      0.00575      0.00331
    8. CRO1_GPS Y coordinate  (m)         -5488076.63436      0.00055      0.00527
    9. CRO1_GPS Z coordinate  (m)          1932767.87460     -0.00399      0.00285
Unc. CRO1_GPS  2607771.27359 -5488076.63436  1932767.87460    0.00742    0.00906    0.01252 2012.081  0.0033  0.0053  0.0028
Apr. CRO1_GPS  2607771.27359 -5488076.63436  1932767.87460    0.00742    0.00906    0.01252 2012.081  0.0033  0.0053  0.0028  -1.0000 -1.0000 -1.0000
Loc.   CRO1_GPS N coordinate  (m)          1976688.95879     -0.00440      0.00180
Loc.   CRO1_GPS E coordinate  (m)         31319027.56689      0.00543      0.00180
Loc.   CRO1_GPS U coordinate  (m)              -31.95602      0.00067      0.00635
     NE,NU,EU position correlations          0.1465       0.2162       0.2218
pbo. CRO1_GPS ----------------  2012 01 30 11 59 55956.4998   2607771.27359 -5488076.63436  1932767.87460 0.00331 0.00527 0.00285 -0.799  0.698 -0.732 |    17.7568990363  295.4156809575  -31.95602     16.2    17.0    0.00635 |   1976688.95879 31319027.56689  -31.95602 0.00180 0.00180 0.00635  0.146  0.216  0.222

Int. AREQ_GPS  1942826.82329 -5804070.23825 -1796893.84451    0.01247    0.00007    0.01400 2005.002
   10. AREQ_GPS X coordinate  (m)          1942826.21028     -0.70128      0.00354
   11. AREQ_GPS Y coordinate  (m)         -5804070.32170     -0.08395      0.00651
   12. AREQ_GPS Z coordinate  (m)         -1796894.19974     -0.45433      0.00287
Unc. AREQ_GPS  1942826.21028 -5804070.32170 -1796894.19974    0.01247    0.00007    0.01400 2012.081  0.0035  0.0065  0.0029
Apr. AREQ_GPS  1942826.21028 -5804070.32170 -1796894.19974    0.01247    0.00007    0.01400 2012.081  0.0035  0.0065  0.0029  -1.0000 -1.0000 -1.0000
Loc.   AREQ_GPS N coordinate  (m)         -1832932.90447     -0.47621      0.00336
Loc.   AREQ_GPS E coordinate  (m)         30799610.94580     -0.69166      0.00246
Loc.   AREQ_GPS U coordinate  (m)             2488.90068     -0.00923      0.00677
     NE,NU,EU position correlations          0.2504       0.4700       0.1860
pbo. AREQ_GPS ----------------  2012 01 30 11 59 55956.4998   1942826.21028 -5804070.32170 -1796894.19974 0.00354 0.00651 0.00287 -0.682  0.092  0.038 |   -16.4655164285  288.5072035205 2488.90068     30.1    23.1    0.00677 |  -1832932.90447 30799610.94580 2488.90068 0.00336 0.00246 0.00677  0.250  0.470  0.186

Int. YELL_GPS -1224452.50143 -2689216.10746  5633638.27862   -0.02082   -0.00441   -0.00093 1997.002
   13. YELL_GPS X coordinate  (m)         -1224452.81590     -0.00053      0.00112
   14. YELL_GPS Y coordinate  (m)         -2689216.17308      0.00088      0.00186
   15. YELL_GPS Z coordinate  (m)          5633638.28665      0.02205      0.00319
Unc. YELL_GPS -1224452.81590 -2689216.17308  5633638.28665   -0.02082   -0.00441   -0.00093 2012.081  0.0011  0.0019  0.0032
Apr. YELL_GPS -1224452.81590 -2689216.17308  5633638.28665   -0.02082   -0.00441   -0.00093 2012.081  0.0011  0.0019  0.0032  -1.0000 -1.0000 -1.0000
Loc.   YELL_GPS N coordinate  (m)          6955341.20927      0.01076      0.00111
Loc.   YELL_GPS E coordinate  (m)         12628197.17303     -0.00085      0.00107
Loc.   YELL_GPS U coordinate  (m)              180.95302      0.01926      0.00354
     NE,NU,EU position correlations          0.0034       0.0325       0.2300
pbo. YELL_GPS ----------------  2012 01 30 11 59 55956.4998  -1224452.81590 -2689216.17308  5633638.28665 0.00112 0.00186 0.00319  0.310 -0.331 -0.755 |    62.4808931455  245.5192960429  180.95302     10.0    20.9    0.00354 |   6955341.20927 12628197.17303  180.95302 0.00111 0.00107 0.00354  0.003  0.032  0.230

Int. TRAK_GPS -2480029.24905 -4703110.82031  3511298.59513   -0.02924    0.02645    0.01537 2005.002
   16. TRAK_GPS X coordinate  (m)         -2480029.45598      0.00005      0.00181
   17. TRAK_GPS Y coordinate  (m)         -4703110.62851      0.00457      0.00314
   18. TRAK_GPS Z coordinate  (m)          3511298.69126     -0.01267      0.00249
Unc. TRAK_GPS -2480029.45598 -4703110.62851  3511298.69126   -0.02924    0.02645    0.01537 2012.081  0.0018  0.0031  0.0025
Apr. TRAK_GPS -2480029.45598 -4703110.62851  3511298.69126   -0.02924    0.02645    0.01537 2012.081  0.0018  0.0031  0.0025  -1.0000 -1.0000 -1.0000
Loc.   TRAK_GPS N coordinate  (m)          3742331.48891     -0.00833      0.00118
Loc.   TRAK_GPS E coordinate  (m)         22451843.21424     -0.00209      0.00123
Loc.   TRAK_GPS U coordinate  (m)              115.53495     -0.01037      0.00405
     NE,NU,EU position correlations          0.1226       0.0553       0.1499
pbo. TRAK_GPS ----------------  2012 01 30 11 59 55956.4998  -2480029.45598 -4703110.62851  3511298.69126 0.00181 0.00314 0.00249  0.680 -0.614 -0.826 |    33.6179357473  242.1965634012  115.53495     10.6    13.3    0.00405 |   3742331.48891 22451843.21424  115.53495 0.00118 0.00123 0.00405  0.123  0.055  0.150

Int. HOB2_GPS -3950071.67350  2522415.25416 -4311638.02559   -0.03974    0.00862    0.04074 2005.002
   19. HOB2_GPS X coordinate  (m)         -3950071.95376      0.00105      0.00341
   20. HOB2_GPS Y coordinate  (m)          2522415.30797     -0.00721      0.00259
   21. HOB2_GPS Z coordinate  (m)         -4311637.73258      0.00462      0.00451
Unc. HOB2_GPS -3950071.95376  2522415.30797 -4311637.73258   -0.03974    0.00862    0.04074 2012.081  0.0034  0.0026  0.0045
Apr. HOB2_GPS -3950071.95376  2522415.30797 -4311637.73258   -0.03974    0.00862    0.04074 2012.081  0.0034  0.0026  0.0045  -1.0000 -1.0000 -1.0000
Loc.   HOB2_GPS N coordinate  (m)         -4764998.42387      0.00018      0.00162
Loc.   HOB2_GPS E coordinate  (m)         12041419.24722      0.00552      0.00121
Loc.   HOB2_GPS U coordinate  (m)               41.05324     -0.00664      0.00587
     NE,NU,EU position correlations          0.4050      -0.3225      -0.2665
pbo. HOB2_GPS ----------------  2012 01 30 11 59 55956.4998  -3950071.95376  2522415.30797 -4311637.73258 0.00341 0.00259 0.00451 -0.831  0.820 -0.880 |   -42.8047091297  147.4387356216   41.05324     14.6    14.9    0.00587 |  -4764998.42387 12041419.24722   41.05324 0.00162 0.00121 0.00587  0.405 -0.323 -0.266

Int. TOW2_GPS -5054582.94073  3275504.33760 -2091539.27586   -0.03094   -0.01432    0.05283 2005.002
   22. TOW2_GPS X coordinate  (m)         -5054583.14281      0.01693      0.00459
   23. TOW2_GPS Y coordinate  (m)          3275504.22463     -0.01160      0.00318
   24. TOW2_GPS Z coordinate  (m)         -2091538.87736      0.02454      0.00353
Unc. TOW2_GPS -5054583.14281  3275504.22463 -2091538.87736   -0.03094   -0.01432    0.05283 2012.081  0.0046  0.0032  0.0035
Apr. TOW2_GPS -5054583.14281  3275504.22463 -2091538.87736   -0.03094   -0.01432    0.05283 2012.081  0.0046  0.0032  0.0035  -1.0000 -1.0000 -1.0000
Loc.   TOW2_GPS N coordinate  (m)         -2145046.02920      0.01645      0.00288
Loc.   TOW2_GPS E coordinate  (m)         15453122.64130      0.00053      0.00171
Loc.   TOW2_GPS U coordinate  (m)               88.09030     -0.02743      0.00570
     NE,NU,EU position correlations          0.2284      -0.1590      -0.0038
pbo. TOW2_GPS ----------------  2012 01 30 11 59 55956.4998  -5054583.14281  3275504.22463 -2091538.87736 0.00459 0.00318 0.00353 -0.783  0.458 -0.542 |   -19.2692763317  147.0556900160   88.09030     25.8    16.2    0.00570 |  -2145046.02920 15453122.64130   88.09030 0.00288 0.00171 0.00570  0.228 -0.159 -0.004

Int. GUAM_GPS -5071312.73778  3568363.55234  1488904.35997    0.00611    0.00737    0.00522 2005.002
   25. GUAM_GPS X coordinate  (m)         -5071312.69700     -0.00247      0.00578
   26. GUAM_GPS Y coordinate  (m)          3568363.59152     -0.01299      0.00400
   27. GUAM_GPS Z coordinate  (m)          1488904.37659     -0.02033      0.00345
Unc. GUAM_GPS -5071312.69700  3568363.59152  1488904.37659    0.00611    0.00737    0.00522 2012.081  0.0058  0.0040  0.0035
Apr. GUAM_GPS -5071312.69700  3568363.59152  1488904.37659    0.00611    0.00737    0.00522 2012.081  0.0058  0.0040  0.0035  -1.0000 -1.0000 -1.0000
Loc.   GUAM_GPS N coordinate  (m)          1512757.26300     -0.01849      0.00315
Loc.   GUAM_GPS E coordinate  (m)         15675134.93196      0.01205      0.00191
Loc.   GUAM_GPS U coordinate  (m)              201.91537     -0.01005      0.00691
     NE,NU,EU position correlations         -0.0910      -0.0068       0.1217
pbo. GUAM_GPS ----------------  2012 01 30 11 59 55956.4998  -5071312.69700  3568363.59152  1488904.37659 0.00578 0.00400 0.00345 -0.833 -0.342  0.362 |    13.5893297052  144.8683605342  201.91537     28.3    17.6    0.00691 |   1512757.26300 15675134.93196  201.91537 0.00315 0.00191 0.00691 -0.091 -0.007  0.122

Int. USUD_GPS -3855263.02241  3427432.54860  3741020.34317   -0.00468    0.00390   -0.00211 2005.002
   28. USUD_GPS X coordinate  (m)         -3855263.27148     -0.21594      0.00321
   29. USUD_GPS Y coordinate  (m)          3427432.28361     -0.29260      0.00258
   30. USUD_GPS Z coordinate  (m)          3741020.33198      0.00375      0.00344
Unc. USUD_GPS -3855263.27148  3427432.28361  3741020.33198   -0.00468    0.00390   -0.00211 2012.081  0.0032  0.0026  0.0034
Apr. USUD_GPS -3855263.27148  3427432.28361  3741020.33198   -0.00468    0.00390   -0.00211 2012.081  0.0032  0.0026  0.0034  -1.0000 -1.0000 -1.0000
Loc.   USUD_GPS N coordinate  (m)          4022319.46769      0.02242      0.00259
Loc.   USUD_GPS E coordinate  (m)         12439689.46061      0.36215      0.00152
Loc.   USUD_GPS U coordinate  (m)             1508.63766     -0.02453      0.00446
     NE,NU,EU position correlations         -0.1018       0.0584       0.1593
pbo. USUD_GPS ----------------  2012 01 30 11 59 55956.4998  -3855263.27148  3427432.28361  3741020.33198 0.00321 0.00258 0.00344 -0.725 -0.456  0.458 |    36.1331105544  138.3620476110 1508.63766     23.2    16.9    0.00446 |   4022319.46769 12439689.46061 1508.63766 0.00259 0.00152 0.00446 -0.102  0.058  0.159

Int. DAV1_GPS   486854.55811  2285099.25423 -5914955.68461    0.00161   -0.00585   -0.00068 2005.002
   31. DAV1_GPS X coordinate  (m)           486854.57722      0.00772      0.00209
   32. DAV1_GPS Y coordinate  (m)          2285099.21495      0.00213      0.00285
   33. DAV1_GPS Z coordinate  (m)         -5914955.69329     -0.00387      0.00542
Unc. DAV1_GPS   486854.57722  2285099.21495 -5914955.69329    0.00161   -0.00585   -0.00068 2012.081  0.0021  0.0028  0.0054
Apr. DAV1_GPS   486854.57722  2285099.21495 -5914955.69329    0.00161   -0.00585   -0.00068 2012.081  0.0021  0.0028  0.0054  -1.0000 -1.0000 -1.0000
Loc.   DAV1_GPS N coordinate  (m)         -7633992.71489      0.00201      0.00139
Loc.   DAV1_GPS E coordinate  (m)          3170252.85897     -0.00710      0.00236
Loc.   DAV1_GPS U coordinate  (m)               44.38369      0.00495      0.00587
     NE,NU,EU position correlations          0.1305       0.1105       0.5199
pbo. DAV1_GPS ----------------  2012 01 30 11 59 55956.4998    486854.57722  2285099.21495 -5914955.69329 0.00209 0.00285 0.00542 -0.419  0.347 -0.833 |   -68.5773233464   77.9726125672   44.38369     12.4    58.0    0.00587 |  -7633992.71489  3170252.85897   44.38369 0.00139 0.00236 0.00587  0.131  0.110  0.520

Int. POL2_GPS  1239971.36992  4530790.09428  4302578.81606   -0.02731    0.00533    0.00479 2005.002
   34. POL2_GPS X coordinate  (m)          1239971.17719      0.00059      0.00138
   35. POL2_GPS Y coordinate  (m)          4530790.11030     -0.02171      0.00205
   36. POL2_GPS Z coordinate  (m)          4302578.83976     -0.01021      0.00260
Unc. POL2_GPS  1239971.17719  4530790.11030  4302578.83976   -0.02731    0.00533    0.00479 2012.081  0.0014  0.0021  0.0026
Apr. POL2_GPS  1239971.17719  4530790.11030  4302578.83976   -0.02731    0.00533    0.00479 2012.081  0.0014  0.0021  0.0026  -1.0000 -1.0000 -1.0000
Loc.   POL2_GPS N coordinate  (m)          4751090.30843      0.00651      0.00136
Loc.   POL2_GPS E coordinate  (m)          6112787.24213     -0.00630      0.00113
Loc.   POL2_GPS U coordinate  (m)             1714.19754     -0.02222      0.00312
     NE,NU,EU position correlations         -0.0991       0.3137      -0.3202
pbo. POL2_GPS ----------------  2012 01 30 11 59 55956.4998   1239971.17719  4530790.11030  4302578.83976 0.00138 0.00205 0.00260  0.542  0.534  0.691 |    42.6797704030   74.6942673453 1714.19754     12.2    13.8    0.00312 |   4751090.30843  6112787.24213 1714.19754 0.00136 0.00113 0.00312 -0.099  0.314 -0.320

Int. KERG_GPS  1406337.28912  3918161.09296 -4816167.35661   -0.00527   -0.00015   -0.00151 2005.002
   37. KERG_GPS X coordinate  (m)          1406337.24030     -0.01151      0.00256
   38. KERG_GPS Y coordinate  (m)          3918161.09467      0.00277      0.00483
   39. KERG_GPS Z coordinate  (m)         -4816167.35640      0.01090      0.00639
Unc. KERG_GPS  1406337.24030  3918161.09467 -4816167.35640   -0.00527   -0.00015   -0.00151 2012.081  0.0026  0.0048  0.0064
Apr. KERG_GPS  1406337.24030  3918161.09467 -4816167.35640   -0.00527   -0.00015   -0.00151 2012.081  0.0026  0.0048  0.0064  -1.0000 -1.0000 -1.0000
Loc.   KERG_GPS N coordinate  (m)         -5493780.16782      0.00616      0.00227
Loc.   KERG_GPS E coordinate  (m)          5094561.01429      0.01177      0.00286
Loc.   KERG_GPS U coordinate  (m)               72.99846     -0.00908      0.00758
     NE,NU,EU position correlations         -0.4019      -0.3391       0.4903
pbo. KERG_GPS ----------------  2012 01 30 11 59 55956.4998   1406337.24030  3918161.09467 -4816167.35640 0.00256 0.00483 0.00639  0.039  0.043 -0.869 |   -49.3514669234   70.2555226776   72.99846     20.4    39.4    0.00758 |  -5493780.16782  5094561.01429   72.99846 0.00227 0.00286 0.00758 -0.402 -0.339  0.490

Int. KIRU_GPS  2251420.79504   862817.22093  5885476.70247   -0.01574    0.01076    0.01142 2005.002
   40. KIRU_GPS X coordinate  (m)          2251420.67486     -0.00876      0.00156
   41. KIRU_GPS Y coordinate  (m)           862817.29598     -0.00111      0.00096
   42. KIRU_GPS Z coordinate  (m)          5885476.76936     -0.01395      0.00322
Unc. KIRU_GPS  2251420.67486   862817.29598  5885476.76936   -0.01574    0.01076    0.01142 2012.081  0.0016  0.0010  0.0032
Apr. KIRU_GPS  2251420.67486   862817.29598  5885476.76936   -0.01574    0.01076    0.01142 2012.081  0.0016  0.0010  0.0032  -1.0000 -1.0000 -1.0000
Loc.   KIRU_GPS N coordinate  (m)          7553845.92631      0.00265      0.00102
Loc.   KIRU_GPS E coordinate  (m)           879764.98057      0.00209      0.00085
Loc.   KIRU_GPS U coordinate  (m)              391.00315     -0.01616      0.00346
     NE,NU,EU position correlations          0.0215      -0.0167      -0.0276
pbo. KIRU_GPS ----------------  2012 01 30 11 59 55956.4998   2251420.67486   862817.29598  5885476.76936 0.00156 0.00096 0.00322  0.405  0.727  0.427 |    67.8573524949   20.9684499432  391.00315      9.1    20.2    0.00346 |   7553845.92631   879764.98057  391.00315 0.00102 0.00085 0.00346  0.022 -0.017 -0.028

Int. MATE_GPS  4641949.55683  1393045.42466  4133287.46435   -0.01829    0.01899    0.01495 2005.002
   43. MATE_GPS X coordinate  (m)          4641949.42592     -0.00144      0.00221
   44. MATE_GPS Y coordinate  (m)          1393045.55632     -0.00276      0.00096
   45. MATE_GPS Z coordinate  (m)          4133287.57012     -0.00006      0.00205
Unc. MATE_GPS  4641949.42592  1393045.55632  4133287.57012   -0.01829    0.01899    0.01495 2012.081  0.0022  0.0010  0.0020
Apr. MATE_GPS  4641949.42592  1393045.55632  4133287.57012   -0.01829    0.01899    0.01495 2012.081  0.0022  0.0010  0.0020  -1.0000 -1.0000 -1.0000
Loc.   MATE_GPS N coordinate  (m)          4525040.77720      0.00137      0.00076
Loc.   MATE_GPS E coordinate  (m)          1410869.16849     -0.00223      0.00074
Loc.   MATE_GPS U coordinate  (m)              535.65297     -0.00169      0.00298
     NE,NU,EU position correlations         -0.0780       0.0588      -0.0385
pbo. MATE_GPS ----------------  2012 01 30 11 59 55956.4998   4641949.42592  1393045.55632  4133287.57012 0.00221 0.00096 0.00205  0.597  0.878  0.560 |    40.6491329142   16.7044613319  535.65297      6.8     8.8    0.00298 |   4525040.77720  1410869.16849  535.65297 0.00076 0.00074 0.00298 -0.078  0.059 -0.039

Int. WTZR_GPS  4075580.55298   931853.79721  4801568.13598   -0.01605    0.01713    0.01009 2005.002
   46. WTZR_GPS X coordinate  (m)          4075580.42474     -0.01462      0.00230
   47. WTZR_GPS Y coordinate  (m)           931853.91885      0.00038      0.00092
   48. WTZR_GPS Z coordinate  (m)          4801568.18788     -0.01953      0.00251
Unc. WTZR_GPS  4075580.42474   931853.91885  4801568.18788   -0.01605    0.01713    0.01009 2012.081  0.0023  0.0009  0.0025
Apr. WTZR_GPS  4075580.42474   931853.91885  4801568.18788   -0.01605    0.01713    0.01009 2012.081  0.0023  0.0009  0.0025  -1.0000 -1.0000 -1.0000
Loc.   WTZR_GPS N coordinate  (m)          5470707.25623     -0.00214      0.00089
Loc.   WTZR_GPS E coordinate  (m)           937828.80661      0.00363      0.00079
Loc.   WTZR_GPS U coordinate  (m)              666.00319     -0.02403      0.00332
     NE,NU,EU position correlations          0.0188      -0.1052      -0.0097
pbo. WTZR_GPS ----------------  2012 01 30 11 59 55956.4998   4075580.42474   931853.91885  4801568.18788 0.00230 0.00092 0.00251  0.491  0.863  0.488 |    49.1441994321   12.8789117778  666.00319      8.0    10.8    0.00332 |   5470707.25623   937828.80661  666.00319 0.00089 0.00079 0.00332  0.019 -0.105 -0.010

Int. NYAL_GPS  1202430.53162   252626.70891  6237767.61729   -0.01430    0.00750    0.01103 2005.002
   49. NYAL_GPS X coordinate  (m)          1202430.43066      0.00026      0.00127
   50. NYAL_GPS Y coordinate  (m)           252626.76723      0.00523      0.00100
   51. NYAL_GPS Z coordinate  (m)          6237767.68467     -0.01069      0.00479
Unc. NYAL_GPS  1202430.43066   252626.76723  6237767.68467   -0.01430    0.00750    0.01103 2012.081  0.0013  0.0010  0.0048
Apr. NYAL_GPS  1202430.43066   252626.76723  6237767.68467   -0.01430    0.00750    0.01103 2012.081  0.0013  0.0010  0.0048  -1.0000 -1.0000 -1.0000
Loc.   NYAL_GPS N coordinate  (m)          8786401.28646     -0.00337      0.00113
Loc.   NYAL_GPS E coordinate  (m)           253597.07642      0.00506      0.00099
Loc.   NYAL_GPS U coordinate  (m)               78.56324     -0.01023      0.00482
     NE,NU,EU position correlations          0.0290       0.2262      -0.0010
pbo. NYAL_GPS ----------------  2012 01 30 11 59 55956.4998   1202430.43066   252626.76723  6237767.68467 0.00127 0.00100 0.00479  0.080  0.488  0.131 |    78.9295856803   11.8650901479   78.56324     10.1    46.2    0.00482 |   8786401.28646   253597.07642   78.56324 0.00113 0.00099 0.00482  0.029  0.226 -0.001

Int. ZIMM_GPS  4331297.06286   567555.87751  4633133.93566   -0.01353    0.01807    0.01205 2005.002
   52. ZIMM_GPS X coordinate  (m)          4331296.96702     -0.00006      0.00186
   53. ZIMM_GPS Y coordinate  (m)           567556.00381     -0.00161      0.00065
   54. ZIMM_GPS Z coordinate  (m)          4633134.02229      0.00133      0.00193
Unc. ZIMM_GPS  4331296.96702   567556.00381  4633134.02229   -0.01353    0.01807    0.01205 2012.081  0.0019  0.0007  0.0019
Apr. ZIMM_GPS  4331296.96702   567556.00381  4633134.02229   -0.01353    0.01807    0.01205 2012.081  0.0019  0.0007  0.0019  -1.0000 -1.0000 -1.0000
Loc.   ZIMM_GPS N coordinate  (m)          5218334.74430      0.00111      0.00068
Loc.   ZIMM_GPS E coordinate  (m)           568072.30587     -0.00159      0.00061
Loc.   ZIMM_GPS U coordinate  (m)              956.34147      0.00079      0.00260
     NE,NU,EU position correlations          0.0105      -0.0408       0.0304
pbo. ZIMM_GPS ----------------  2012 01 30 11 59 55956.4998   4331296.96702   567556.00381  4633134.02229 0.00186 0.00065 0.00193  0.356  0.872  0.354 |    46.8770985846    7.4652785888  956.34147      6.1     8.0    0.00260 |   5218334.74430   568072.30587  956.34147 0.00068 0.00061 0.00260  0.010 -0.041  0.030

Eph. #IC 12  30 12  0  0                    GPST J2000 IAU76 BERNE
   55. PRN_0163 AntOffest X   (m)                0.39400      0.00000      0.00000
   56. PRN_0163 AntOffest Y   (m)                             0.00000      0.00000
   57. PRN_0163 AntOffest Z   (m)                1.56130      0.00000      0.00000
Eph.  2012  1 30 11 PRN_0163         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.39400   0.00000   1.56130

   58. PRN_0261 AntOffest X   (m)                             0.00000      0.00000
   59. PRN_0261 AntOffest Y   (m)                             0.00000      0.00000
   60. PRN_0261 AntOffest Z   (m)                0.77860      0.00000      0.00000
Eph.  2012  1 30 11 PRN_0261         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.77860

   61. PRN_0333 AntOffest X   (m)                0.27900      0.00000      0.00000
   62. PRN_0333 AntOffest Y   (m)                             0.00000      0.00000
   63. PRN_0333 AntOffest Z   (m)                2.79260      0.00000      0.00000
Eph.  2012  1 30 11 PRN_0333         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.79260

   64. PRN_0434 AntOffest X   (m)                0.27900      0.00000      0.00000
   65. PRN_0434 AntOffest Y   (m)                             0.00000      0.00000
   66. PRN_0434 AntOffest Z   (m)                2.42000      0.00000      0.00000
Eph.  2012  1 30 11 PRN_0434         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.42000

   67. PRN_0550 AntOffest X   (m)                             0.00000      0.00000
   68. PRN_0550 AntOffest Y   (m)                             0.00000      0.00000
   69. PRN_0550 AntOffest Z   (m)                0.82260      0.00000      0.00000
Eph.  2012  1 30 11 PRN_0550         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.82260

   70. PRN_0636 AntOffest X   (m)                0.27900      0.00000      0.00000
   71. PRN_0636 AntOffest Y   (m)                             0.00000      0.00000
   72. PRN_0636 AntOffest Z   (m)                2.87860      0.00000      0.00000
Eph.  2012  1 30 11 PRN_0636         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.87860

   73. PRN_0748 AntOffest X   (m)                             0.00000      0.00000
   74. PRN_0748 AntOffest Y   (m)                             0.00000      0.00000
   75. PRN_0748 AntOffest Z   (m)                0.85290      0.00000      0.00000
Eph.  2012  1 30 11 PRN_0748         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.85290

   76. PRN_0838 AntOffest X   (m)                0.27900      0.00000      0.00000
   77. PRN_0838 AntOffest Y   (m)                             0.00000      0.00000
   78. PRN_0838 AntOffest Z   (m)                2.57810      0.00000      0.00000
Eph.  2012  1 30 11 PRN_0838         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.57810

   79. PRN_0939 AntOffest X   (m)                0.27900      0.00000      0.00000
   80. PRN_0939 AntOffest Y   (m)                             0.00000      0.00000
   81. PRN_0939 AntOffest Z   (m)                2.46140      0.00000      0.00000
Eph.  2012  1 30 11 PRN_0939         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.46140

   82. PRN_1040 AntOffest X   (m)                0.27900      0.00000      0.00000
   83. PRN_1040 AntOffest Y   (m)                             0.00000      0.00000
   84. PRN_1040 AntOffest Z   (m)                2.54650      0.00000      0.00000
Eph.  2012  1 30 11 PRN_1040         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.54650

   85. PRN_1146 AntOffest X   (m)                             0.00000      0.00000
   86. PRN_1146 AntOffest Y   (m)                             0.00000      0.00000
   87. PRN_1146 AntOffest Z   (m)                1.14130      0.00000      0.00000
Eph.  2012  1 30 11 PRN_1146         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.14130

   88. PRN_1258 AntOffest X   (m)                             0.00000      0.00000
   89. PRN_1258 AntOffest Y   (m)                             0.00000      0.00000
   90. PRN_1258 AntOffest Z   (m)                0.84080      0.00000      0.00000
Eph.  2012  1 30 11 PRN_1258         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.84080

   91. PRN_1343 AntOffest X   (m)                             0.00000      0.00000
   92. PRN_1343 AntOffest Y   (m)                             0.00000      0.00000
   93. PRN_1343 AntOffest Z   (m)                1.38950      0.00000      0.00000
Eph.  2012  1 30 11 PRN_1343         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.38950

   94. PRN_1441 AntOffest X   (m)                             0.00000      0.00000
   95. PRN_1441 AntOffest Y   (m)                             0.00000      0.00000
   96. PRN_1441 AntOffest Z   (m)                1.34540      0.00000      0.00000
Eph.  2012  1 30 11 PRN_1441         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.34540

   97. PRN_1555 AntOffest X   (m)                             0.00000      0.00000
   98. PRN_1555 AntOffest Y   (m)                             0.00000      0.00000
   99. PRN_1555 AntOffest Z   (m)                0.68110      0.00000      0.00000
Eph.  2012  1 30 11 PRN_1555         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.68110

  100. PRN_1656 AntOffest X   (m)                             0.00000      0.00000
  101. PRN_1656 AntOffest Y   (m)                             0.00000      0.00000
  102. PRN_1656 AntOffest Z   (m)                1.50640      0.00000      0.00000
Eph.  2012  1 30 11 PRN_1656         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.50640

  103. PRN_1753 AntOffest X   (m)                             0.00000      0.00000
  104. PRN_1753 AntOffest Y   (m)                             0.00000      0.00000
  105. PRN_1753 AntOffest Z   (m)                0.82710      0.00000      0.00000
Eph.  2012  1 30 11 PRN_1753         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.82710

  106. PRN_1854 AntOffest X   (m)                             0.00000      0.00000
  107. PRN_1854 AntOffest Y   (m)                             0.00000      0.00000
  108. PRN_1854 AntOffest Z   (m)                1.29090      0.00000      0.00000
Eph.  2012  1 30 11 PRN_1854         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.29090

  109. PRN_1959 AntOffest X   (m)                             0.00000      0.00000
  110. PRN_1959 AntOffest Y   (m)                             0.00000      0.00000
  111. PRN_1959 AntOffest Z   (m)                0.84960      0.00000      0.00000
Eph.  2012  1 30 11 PRN_1959         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.84960

  112. PRN_2051 AntOffest X   (m)                             0.00000      0.00000
  113. PRN_2051 AntOffest Y   (m)                             0.00000      0.00000
  114. PRN_2051 AntOffest Z   (m)                1.34360      0.00000      0.00000
Eph.  2012  1 30 11 PRN_2051         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.34360

  115. PRN_2145 AntOffest X   (m)                             0.00000      0.00000
  116. PRN_2145 AntOffest Y   (m)                             0.00000      0.00000
  117. PRN_2145 AntOffest Z   (m)                1.40540      0.00000      0.00000
Eph.  2012  1 30 11 PRN_2145         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.40540

  118. PRN_2247 AntOffest X   (m)                             0.00000      0.00000
  119. PRN_2247 AntOffest Y   (m)                             0.00000      0.00000
  120. PRN_2247 AntOffest Z   (m)                0.90580      0.00000      0.00000
Eph.  2012  1 30 11 PRN_2247         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.90580

  121. PRN_2360 AntOffest X   (m)                             0.00000      0.00000
  122. PRN_2360 AntOffest Y   (m)                             0.00000      0.00000
  123. PRN_2360 AntOffest Z   (m)                0.80820      0.00000      0.00000
Eph.  2012  1 30 11 PRN_2360         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.80820

  124. PRN_2562 AntOffest X   (m)                0.39400      0.00000      0.00000
  125. PRN_2562 AntOffest Y   (m)                             0.00000      0.00000
  126. PRN_2562 AntOffest Z   (m)                1.59730      0.00000      0.00000
Eph.  2012  1 30 11 PRN_2562         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.39400   0.00000   1.59730

  127. PRN_2626 AntOffest X   (m)                0.27900      0.00000      0.00000
  128. PRN_2626 AntOffest Y   (m)                             0.00000      0.00000
  129. PRN_2626 AntOffest Z   (m)                2.45940      0.00000      0.00000
Eph.  2012  1 30 11 PRN_2626         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.45940

  130. PRN_2727 AntOffest X   (m)                0.27900      0.00000      0.00000
  131. PRN_2727 AntOffest Y   (m)                             0.00000      0.00000
  132. PRN_2727 AntOffest Z   (m)                2.63340      0.00000      0.00000
Eph.  2012  1 30 11 PRN_2727         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.63340

  133. PRN_2844 AntOffest X   (m)                             0.00000      0.00000
  134. PRN_2844 AntOffest Y   (m)                             0.00000      0.00000
  135. PRN_2844 AntOffest Z   (m)                1.04280      0.00000      0.00000
Eph.  2012  1 30 11 PRN_2844         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.04280

  136. PRN_2957 AntOffest X   (m)                             0.00000      0.00000
  137. PRN_2957 AntOffest Y   (m)                             0.00000      0.00000
  138. PRN_2957 AntOffest Z   (m)                0.85710      0.00000      0.00000
Eph.  2012  1 30 11 PRN_2957         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.85710

  139. PRN_3035 AntOffest X   (m)                0.27900      0.00000      0.00000
  140. PRN_3035 AntOffest Y   (m)                             0.00000      0.00000
  141. PRN_3035 AntOffest Z   (m)                2.61270      0.00000      0.00000
Eph.  2012  1 30 11 PRN_3035         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.61270

  142. PRN_3152 AntOffest X   (m)                             0.00000      0.00000
  143. PRN_3152 AntOffest Y   (m)                             0.00000      0.00000
  144. PRN_3152 AntOffest Z   (m)                0.97140      0.00000      0.00000
Eph.  2012  1 30 11 PRN_3152         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.97140

  145. PRN_3223 AntOffest X   (m)                0.27900      0.00000      0.00000
  146. PRN_3223 AntOffest Y   (m)                             0.00000      0.00000
  147. PRN_3223 AntOffest Z   (m)                2.77720      0.00000      0.00000
Eph.  2012  1 30 11 PRN_3223         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.77720

  148. X-pole position        (mas)             60.68885      0.14085      0.05521
  149. Y-pole position        (mas)            256.03668      0.13068      0.04523

  150. UT1-AT                 (ms)          -34449.14728     -0.00228      0.00159
      Pole/UT1 correlations: XY, XU, YU          0.7002    -0.0007     0.0635

IERS  MJD      Xpole   Ypole  UT1-UTC    LOD  Xsig  Ysig   UTsig  LODsig  Nr Nf Nt    Xrt    Yrt  Xrtsig  Yrtsig XYcorr XUTcor YUTcor
IERS             (10**-6")       (0.1 usec)    (10**-6")     (0.1 usec)              (10**-6"/d)    (10**-6"/d)
IERS55956.50   60689  256037 -4491473   6820    55    45      16       0  18 12 31  -2541   -188      0      0    0.700 -0.001  0.064


