Globk Analysis

 +++++++++++++++++++++++++++++++++++++
 + GLORG                 Version 5.19 +
 +++++++++++++++++++++++++++++++++++++


 Stabilization with  20.0% constant,  80.0% site dependent weighting.
 Delete sites with   3.0-sigma condition.
 Height variance factor      10.00 Position,     10.00 Velocity
 For Position: Min dH sigma 0.0050 m;    Min RMS 0.0030 m,    Min dNE sigma 0.00050 m
 For Velocity: Min dH sigma 0.0050 m/yr; Min RMS 0.0030 m/yr, Min dNE sigma 0.00010 m/yr
 Sigma Ratio to allow use: Position   3.00 Velocity   3.00

====================================================================================================
 Starting Position stabilization iteration   1 L0601151200_thss.glx
 For   18 sites in origin, min/max height sigma       7.40     11.31 mm; Median        8.60 mm, Tol      15.00 mm L0601151200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)    -1.67537 +-    0.88818 Iter  1 L0601151200_thss.glx
 Y Rotation  (mas)    -0.69860 +-    0.91843 Iter  1 L0601151200_thss.glx
 Z Rotation  (mas)    -2.42752 +-    0.99369 Iter  1 L0601151200_thss.glx
 X Translation (m)    -0.09813 +-    0.02732 Iter  1 L0601151200_thss.glx
 Y Translation (m)     0.01275 +-    0.02663 Iter  1 L0601151200_thss.glx
 Z Translation (m)    -0.05278 +-    0.02842 Iter  1 L0601151200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   1.00  REYK_GPS   1.00  CRO1_GPS   1.00  AREQ_GPS   1.00  YELL_GPS   1.00  TRAK_GPS   1.00 
HOB2_GPS   1.00  TOW2_GPS   1.00  GUAM_GPS   1.00  USUD_GPS   1.00  DAV1_GPS   1.00  POL2_GPS   1.00 
KERG_GPS   1.00  KIRU_GPS   1.00  MATE_GPS   1.00  WTZR_GPS   1.00  NYAL_GPS   1.00  ZIMM_GPS   1.00 
 For   54 Position Iter  1 Pre RMS    0.0872 m; Post RMS   0.07437 m L0601151200_thss.glx
 For   18 sites in origin, min/max NE sigma       1.22      3.52 mm; Median        1.99 mm, Tol       2.32 mm L0601151200_thss.glx
Deleting AREQ_GPS Position error   0.5681 m, relative variance     2.09 Nsigma     5.29

====================================================================================================
 Starting Position stabilization iteration   2 L0601151200_thss.glx
 For   17 sites in origin, min/max height sigma       7.40      9.82 mm; Median        8.45 mm, Tol      15.00 mm L0601151200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)     0.13654 +-    0.08196 Iter  2 L0601151200_thss.glx
 Y Rotation  (mas)    -0.02029 +-    0.09160 Iter  2 L0601151200_thss.glx
 Z Rotation  (mas)     0.05755 +-    0.09317 Iter  2 L0601151200_thss.glx
 X Translation (m)    -0.01244 +-    0.00267 Iter  2 L0601151200_thss.glx
 Y Translation (m)    -0.00778 +-    0.00248 Iter  2 L0601151200_thss.glx
 Z Translation (m)     0.00013 +-    0.00257 Iter  2 L0601151200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   0.82  REYK_GPS   0.83  CRO1_GPS   0.98  YELL_GPS   0.93  TRAK_GPS   1.06  HOB2_GPS   1.05 
TOW2_GPS   1.12  GUAM_GPS   1.15  USUD_GPS   1.07  DAV1_GPS   1.11  POL2_GPS   0.92  KERG_GPS   1.27 
KIRU_GPS   0.80  MATE_GPS   0.82  WTZR_GPS   0.77  NYAL_GPS   0.78  ZIMM_GPS   0.75 
 For   51 Position Iter  2 Pre RMS    0.0104 m; Post RMS   0.00641 m L0601151200_thss.glx
 For   17 sites in origin, min/max NE sigma       1.00      3.19 mm; Median        1.83 mm, Tol       2.49 mm L0601151200_thss.glx
Deleting REYK_GPS Position error   0.0187 m, relative variance     0.70 Nsigma     3.48
Deleting USUD_GPS Position error   0.0306 m, relative variance     1.27 Nsigma     4.24

====================================================================================================
 Starting Position stabilization iteration   3 L0601151200_thss.glx
 For   15 sites in origin, min/max height sigma       7.55      9.82 mm; Median        8.45 mm, Tol      15.00 mm L0601151200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)     0.05678 +-    0.05800 Iter  3 L0601151200_thss.glx
 Y Rotation  (mas)    -0.01780 +-    0.06595 Iter  3 L0601151200_thss.glx
 Z Rotation  (mas)     0.08782 +-    0.06882 Iter  3 L0601151200_thss.glx
 X Translation (m)    -0.01070 +-    0.00191 Iter  3 L0601151200_thss.glx
 Y Translation (m)    -0.00762 +-    0.00176 Iter  3 L0601151200_thss.glx
 Z Translation (m)     0.00439 +-    0.00188 Iter  3 L0601151200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   0.79  CRO1_GPS   1.08  YELL_GPS   0.95  TRAK_GPS   1.11  HOB2_GPS   1.04  TOW2_GPS   1.17 
GUAM_GPS   1.23  DAV1_GPS   1.17  POL2_GPS   0.92  KERG_GPS   1.41  KIRU_GPS   0.80  MATE_GPS   0.79 
WTZR_GPS   0.75  NYAL_GPS   0.78  ZIMM_GPS   0.72 
 For   45 Position Iter  3 Pre RMS    0.0084 m; Post RMS   0.00431 m L0601151200_thss.glx
 For   15 sites in origin, min/max NE sigma       0.94      3.24 mm; Median        1.80 mm, Tol       2.59 mm L0601151200_thss.glx
Deleting GUAM_GPS Position error   0.0278 m, relative variance     1.70 Nsigma     4.95

====================================================================================================
 Starting Position stabilization iteration   4 L0601151200_thss.glx
 For   14 sites in origin, min/max height sigma       7.55      9.82 mm; Median        8.43 mm, Tol      15.00 mm L0601151200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)    -0.01119 +-    0.04267 Iter  4 L0601151200_thss.glx
 Y Rotation  (mas)    -0.03892 +-    0.04769 Iter  4 L0601151200_thss.glx
 Z Rotation  (mas)     0.09324 +-    0.05246 Iter  4 L0601151200_thss.glx
 X Translation (m)    -0.01110 +-    0.00138 Iter  4 L0601151200_thss.glx
 Y Translation (m)    -0.00751 +-    0.00129 Iter  4 L0601151200_thss.glx
 Z Translation (m)     0.00715 +-    0.00141 Iter  4 L0601151200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   0.78  CRO1_GPS   1.09  YELL_GPS   0.93  TRAK_GPS   1.08  HOB2_GPS   0.98  TOW2_GPS   1.15 
DAV1_GPS   1.19  POL2_GPS   0.94  KERG_GPS   1.43  KIRU_GPS   0.80  MATE_GPS   0.77  WTZR_GPS   0.73 
NYAL_GPS   0.78  ZIMM_GPS   0.71 
 For   42 Position Iter  4 Pre RMS    0.0082 m; Post RMS   0.00312 m L0601151200_thss.glx
 For   14 sites in origin, min/max NE sigma       0.92      3.22 mm; Median        1.77 mm, Tol       2.54 mm L0601151200_thss.glx
Deleting YELL_GPS Position error   0.0092 m, relative variance     0.90 Nsigma     3.11
Rotating into local coordinates for equates
 Checking covariance matrix after equate and force
Globk Analysis


---------------------------------------------------------
 GLOBK Ver 5.29, Global solution
---------------------------------------------------------

 Solution commenced with: 2006/ 1/15  0: 0    (2006.0384)
 Solution ended with    : 2006/ 1/15 23:59    (2006.0411)
 Solution refers to     : 2006/ 1/15 11:59    (2006.0397) [Seconds tag  45.000]
 Satellite IC epoch     : 2006/ 1/15 12: 0  0.00
 GPS System Information : Time GPST Frame J2000 Precession IAU76 Radiation model BERNE Nutation IAU00 Gravity EGM08 EarthRad NONE  AntThrust NONE 
 MODELS Used in Analysis: SD-WOB  | SD-UT1  | IERS10  | E-Tide  | K1-Tide | PoleTide| OC-Load | MPT2010 |  
 ATM Delay Models Used  : GP25    | GP25    | GP25    | GP25    | 2nd Order Ion     | NONE    | UNKNOWN | 
 Reference Frame        : IGb08           
 Run time               : 2015/12/17 15:14 46.00

 There were         1 exps from          1 global files in the solution
 There were       237534 data used,       0 data not used and       237534 data total
 There were          144 global parameters estimated
 There were    18 Sites,   18 Used Sites,    0 radio sources, and   29 Satellites

 The  prefit chi**2 for      54 input parameters is     0.000

 LIST file      : L0601151200_thss.glx
 COMMON file    :  
 GLOBK CMD file : globk_comb.cmd
 GLORG CMD file : glorg_comb.cmd
 APRIORI file   : ../tables/itrf08_comb.apr
 APRIORI file   : ../tables/itrf08_comb.apr (glorg)
 NUTATION file  :  
 PLANETARY file :  
 SD ORIENT file :  
 PMU file       :  
 BACK SOLN file :  
 OUTGLOBAL file :  
 SVS EPHEM file :  
 SVS MARKOV file:  

* RENAME REPORT (RNRP option)
*   Sites             dN        sN       dE       sE     dU         sU  Units Compare date  EQ Dist EQ Name
* EARTHQUAKE LOG FITS
*  Sites             dN        sN       dE       sE     dU         sU   mm

 Summary of GLOBK command file globk_comb.cmd
-------------------------------------------------------------------------------
* GLOBK command file to generate daily time series and to combine
* h-files over 2 to 30 days.
* For combination, set COMB as a globk command-line option to
* invoke the saving of the output h-file
* Last edited by rwk 130701
* << column 1 must be blank if not comment >>
* This group of commands must appear before any others:
 srt_file @.srt
 srt_dir +1
# Optionally add a second eq_file for analysis-specific renames
* End commands that must appear first
* ITRF2008 augmented by now-defunct sites and recent IGS solutions;
# matched to itrf08_comb.eq
 apr_file ../tables/itrf08_comb.apr
# Optionally add additional apr files for other sites
* Set maximum chi2, prefit coordinate difference (m), and rotation (mas) for an h-file to be used;
 max_chii 13 3 100
# increase tolerances to include all files for diagnostics
# Not necessary unless combining h-files with different a priori EOP
 in_pmu ../tables/pmu.usno
* Invoke glorg
 org_cmd glorg_comb.cmd
* Print file options
 crt_opt NOPR
 prt_opt NOPR GDLF CMDS MIDP
 org_opt PSUM CMDS GDLF MIDP FIXA RNRP
# sh_glred will name the glorg print files
* Coordinate parameters to be estimated and a priori constraints
 apr_neu  all 10 10 10  0 0 0
* Rotation parameters to be estimated and a priori constraints
 apr_wob  5 5 0 0
 apr_ut1  5 0
# If combining with global h-files, allow EOPS to change
# between days
# EOP tight if translation-only stabilization in glorg
* Write out a combined H-file
# Can substitute your analysis name for 'COMB' in the file name below
COMB out_glb  H------_COMB.GLX
* Optionally put a uselist and/or sig_neu and mar_neu reweight in a source file
* Turn off quake log estimates if in the eq_file
 free_log -1
* Remove scratch files for repeatability runs
  del_scra yes
* Correct the pole tide when not compatible with GAMIT
  app_ptid all
* If orbits free in GAMIT (RELAX) and you want them fixed, use:
* but if you are combining with globk h-files, better to leave them
* on but, if the models are incompatible, turn off radiation-pressure parameters,
* When using MIT GLX files which have satellite phase center positions
* estimated use:
  apr_svan all  F F F     ! Fix antenna offset to IGS apriori values.
-------------------------------------------------------------------------------

 Summary of GLORG command file glorg_comb.cmd
-------------------------------------------------------------------------------
* Glorg command file for daily repeatabilities or combinations
* Last edited by rwk 130701
* Parameters to be estimated
 pos_org  xtran ytran ztran xrot yrot zrot
#   or if translation-only
* Downweight of height relative to horizontal (default is 10)
#   Heavy downweight if reference frame robust and heights suspect
* Controls for removing sites from the stabilization
#   Vary these to make the stabilization more robust or more precise
 stab_it 4 0.8 3.0
* A priori coordinates
#  ITRF2008 may be replaced by an apr file from a priori velocity solution
 apr_file ../tables/itrf08_comb.apr
* List of stabilization sites
#   This should match the well-determined sites in the apr_file
 stab_site clear
 source ../tables/igb08_hierarchy.stab_site
SOURCE ># Sites in IGb08 network hierarchy from ftp://igs-rf.ign.fr/pub/IGb08/IGb08_core.txt
SOURCE ># Created with core2stab_site.sh by Mike Floyd on 2014-08-08
SOURCE > stab_site AREQ
SOURCE > stab_site CRO1
SOURCE > stab_site DAV1
SOURCE > stab_site GUAM
SOURCE > stab_site HOB2
SOURCE > stab_site KERG
SOURCE > stab_site KIRU
SOURCE > stab_site MATE
SOURCE > stab_site NYAL
SOURCE > stab_site POL2
SOURCE > stab_site REYK
SOURCE > stab_site TOW2
SOURCE > stab_site TRAK
SOURCE > stab_site USUD
SOURCE > stab_site VILL
SOURCE > stab_site WTZR
SOURCE > stab_site YELL
SOURCE > stab_site ZIMM
SOURCE > 
SOURCE > 
-------------------------------------------------------------------------------

 EXPERIMENT LIST from L0601151200_thss.srt
     #  Name                               SCALE Diag PPM  Forw Chi2 Back Chi2 Status
     1 ../glbf/h0601151200_thss.glx     1.000000   0.000     0.000    -1.000   USED        

 SUMMARY POSITION ESTIMATES FROM GLOBK Ver 5.29        
    Long.       Lat.        dE adj.   dN adj.   dE +-     dN +-   RHO        dH adj.   dH +-  SITE
    (deg)      (deg)         (mm)      (mm)      (mm)      (mm)               (mm)      (mm)
  356.04802   40.44359       0.66      3.26      0.82      0.92 -0.010       16.90      3.41 VILL_GPS*
  338.04451   64.13878     -17.57      8.96      1.08      1.24 -0.032      -33.21      3.89 REYK_GPS 
  295.41568   17.75690       1.97     -5.83      1.53      1.65  0.162       -3.19      5.05 CRO1_GPS*
  288.50720  -16.46552    -623.44   -438.29      2.78      3.73  0.317        9.45      9.41 AREQ_GPS 
  245.51930   62.48089       4.00      6.12      1.21      1.26  0.006       17.56      3.89 YELL_GPS 
  242.19657   33.61793      -3.45      2.75      1.62      1.48  0.120       -9.18      5.54 TRAK_GPS*
  147.43873  -42.80471       1.55     -7.98      1.12      1.40  0.351        9.44      4.77 HOB2_GPS*
  147.05569  -19.26928      -5.30     -5.33      1.35      2.10  0.271        3.79      5.70 TOW2_GPS*
  144.86836   13.58933      -1.09    -31.02      2.05      2.76 -0.089      -27.69      7.77 GUAM_GPS 
  138.36204   36.13311       3.44    -36.35      1.68      2.52 -0.226      -52.09      4.90 USUD_GPS 
   77.97261  -68.57732      10.10      0.37      2.24      1.22  0.085       -4.10      5.36 DAV1_GPS*
   74.69427   42.67977      -0.17      4.12      1.21      1.42 -0.286       -2.97      3.34 POL2_GPS*
   70.25552  -49.35147       5.32      1.75      2.53      1.98 -0.391       -1.89      6.00 KERG_GPS*
   20.96845   67.85735      -0.78      4.07      0.85      1.01  0.101       -4.37      3.56 KIRU_GPS*
   16.70446   40.64913      -0.97     -1.23      0.84      0.83 -0.108        1.30      3.02 MATE_GPS*
   12.87891   49.14420      -1.62     -0.68      0.70      0.77 -0.021       -8.59      2.90 WTZR_GPS*
   11.86509   78.92958       1.85      0.65      0.80      0.97  0.013        9.60      4.02 NYAL_GPS*
    7.46528   46.87710      -0.43     -1.57      0.64      0.66 -0.038       -0.83      2.56 ZIMM_GPS*
POS STATISTICS: For   13 RefSites WRMS ENU   2.15   2.96   7.41  mm    NRMS ENU   2.19   2.80   1.96 L0601151200_thss.glx
POS MEANS: For   13 RefSites: East  -0.17 +-   0.60 North  -0.12 +-   0.82 Up   0.38 +-   2.06 mm L0601151200_thss.glx

 PARAMETER ESTIMATES FROM GLOBK Vers 5.29        
  #      PARAMETER                            Estimate       Adjustment     Sigma
Int. VILL_GPS  4849833.68541  -335049.02412  4116014.92373   -0.01055    0.02001    0.01155 2005.002
    1. VILL_GPS X coordinate  (m)          4849833.68526      0.01081      0.00263
    2. VILL_GPS Y coordinate  (m)          -335049.00342     -0.00009      0.00082
    3. VILL_GPS Z coordinate  (m)          4116014.94913      0.01340      0.00235
Unc. VILL_GPS  4849833.68526  -335049.00342  4116014.94913   -0.01055    0.02001    0.01155 2006.040  0.0026  0.0008  0.0024
Apr. VILL_GPS  4849833.68526  -335049.00342  4116014.94913   -0.01055    0.02001    0.01155 2006.040  0.0026  0.0008  0.0024  -1.0000 -1.0000 -1.0000
Loc.   VILL_GPS N coordinate  (m)          4502160.23157      0.00326      0.00092
Loc.   VILL_GPS E coordinate  (m)         30163503.96839      0.00066      0.00082
Loc.   VILL_GPS U coordinate  (m)              647.34588      0.01690      0.00341
     NE,NU,EU position correlations         -0.0099       0.0632       0.1056
pbo. VILL_GPS ----------------  2006 01 15 11 59 53750.4998   4849833.68526  -335049.00342  4116014.94913 0.00263 0.00082 0.00235 -0.093  0.864 -0.095 |    40.4435934757  356.0480210309  647.34588      8.2     9.7    0.00341 |   4502160.23157 30163503.96839  647.34588 0.00092 0.00082 0.00341 -0.010  0.063  0.106

Int. REYK_GPS  2587384.32846 -1043033.51334  5716564.04602   -0.01961   -0.00176    0.00895 2005.002
    4. REYK_GPS X coordinate  (m)          2587384.28054     -0.02755      0.00188
    5. REYK_GPS Y coordinate  (m)         -1043033.52301     -0.00784      0.00116
    6. REYK_GPS Z coordinate  (m)          5716564.02941     -0.02591      0.00359
Unc. REYK_GPS  2587384.28054 -1043033.52301  5716564.02941   -0.01961   -0.00176    0.00895 2006.040  0.0019  0.0012  0.0036
Apr. REYK_GPS  2587384.28054 -1043033.52301  5716564.02941   -0.01961   -0.00176    0.00895 2006.040  0.0019  0.0012  0.0036  -1.0000 -1.0000 -1.0000
Loc.   REYK_GPS N coordinate  (m)          7139896.81389      0.00896      0.00124
Loc.   REYK_GPS E coordinate  (m)         16413892.67249     -0.01757      0.00108
Loc.   REYK_GPS U coordinate  (m)               93.01597     -0.03321      0.00389
     NE,NU,EU position correlations         -0.0320       0.1088       0.1162
pbo. REYK_GPS ----------------  2006 01 15 11 59 53750.4998   2587384.28054 -1043033.52301  5716564.02941 0.00188 0.00116 0.00359 -0.322  0.713 -0.357 |    64.1387843495  338.0445139984   93.01597     11.1    22.3    0.00389 |   7139896.81389 16413892.67249   93.01597 0.00124 0.00108 0.00389 -0.032  0.109  0.116

Int. CRO1_GPS  2607771.21531 -5488076.69905  1932767.78997    0.00742    0.00906    0.01252 2005.002
    7. CRO1_GPS X coordinate  (m)          2607771.22425      0.00123      0.00254
    8. CRO1_GPS Y coordinate  (m)         -5488076.68764      0.00199      0.00423
    9. CRO1_GPS Z coordinate  (m)          1932767.79646     -0.00652      0.00250
Unc. CRO1_GPS  2607771.22425 -5488076.68764  1932767.79646    0.00742    0.00906    0.01252 2006.040  0.0025  0.0042  0.0025
Apr. CRO1_GPS  2607771.22425 -5488076.68764  1932767.79646    0.00742    0.00906    0.01252 2006.040  0.0025  0.0042  0.0025  -1.0000 -1.0000 -1.0000
Loc.   CRO1_GPS N coordinate  (m)          1976688.87567     -0.00583      0.00165
Loc.   CRO1_GPS E coordinate  (m)         31319027.49948      0.00197      0.00153
Loc.   CRO1_GPS U coordinate  (m)              -31.95419     -0.00319      0.00505
     NE,NU,EU position correlations          0.1623       0.2990       0.1007
pbo. CRO1_GPS ----------------  2006 01 15 11 59 53750.4998   2607771.22425 -5488076.68764  1932767.79646 0.00254 0.00423 0.00250 -0.746  0.672 -0.710 |    17.7568982896  295.4156803217  -31.95419     14.8    14.4    0.00505 |   1976688.87567 31319027.49948  -31.95419 0.00165 0.00153 0.00505  0.162  0.299  0.101

Int. AREQ_GPS  1942826.82329 -5804070.23825 -1796893.84451    0.01247    0.00007    0.01400 2005.002
   10. AREQ_GPS X coordinate  (m)          1942826.20874     -0.62751      0.00468
   11. AREQ_GPS Y coordinate  (m)         -5804070.32759     -0.08942      0.00888
   12. AREQ_GPS Z coordinate  (m)         -1796894.25317     -0.42321      0.00308
Unc. AREQ_GPS  1942826.20874 -5804070.32759 -1796894.25317    0.01247    0.00007    0.01400 2006.040  0.0047  0.0089  0.0031
Apr. AREQ_GPS  1942826.20874 -5804070.32759 -1796894.25317    0.01247    0.00007    0.01400 2006.040  0.0047  0.0089  0.0031  -1.0000 -1.0000 -1.0000
Loc.   AREQ_GPS N coordinate  (m)         -1832932.95454     -0.43829      0.00373
Loc.   AREQ_GPS E coordinate  (m)         30799610.94246     -0.62344      0.00278
Loc.   AREQ_GPS U coordinate  (m)             2488.92072      0.00945      0.00941
     NE,NU,EU position correlations          0.3175       0.5457       0.3359
pbo. AREQ_GPS ----------------  2006 01 15 11 59 53750.4998   1942826.20874 -5804070.32759 -1796894.25317 0.00468 0.00888 0.00308 -0.797 -0.045  0.149 |   -16.4655168783  288.5072034893 2488.92072     33.5    26.0    0.00941 |  -1832932.95454 30799610.94246 2488.92072 0.00373 0.00278 0.00941  0.317  0.546  0.336

Int. YELL_GPS -1224452.50143 -2689216.10746  5633638.27862   -0.02082   -0.00441   -0.00093 1997.002
   13. YELL_GPS X coordinate  (m)         -1224452.68712      0.00251      0.00124
   14. YELL_GPS Y coordinate  (m)         -2689216.15147     -0.00415      0.00206
   15. YELL_GPS Z coordinate  (m)          5633638.28861      0.01840      0.00351
Unc. YELL_GPS -1224452.68712 -2689216.15147  5633638.28861   -0.02082   -0.00441   -0.00093 2006.040  0.0012  0.0021  0.0035
Apr. YELL_GPS -1224452.68712 -2689216.15147  5633638.28861   -0.02082   -0.00441   -0.00093 2006.040  0.0012  0.0021  0.0035  -1.0000 -1.0000 -1.0000
Loc.   YELL_GPS N coordinate  (m)          6955341.27487      0.00612      0.00126
Loc.   YELL_GPS E coordinate  (m)         12628197.28099      0.00400      0.00121
Loc.   YELL_GPS U coordinate  (m)              180.92102      0.01756      0.00389
     NE,NU,EU position correlations          0.0055       0.0420       0.2575
pbo. YELL_GPS ----------------  2006 01 15 11 59 53750.4998  -1224452.68712 -2689216.15147  5633638.28861 0.00124 0.00206 0.00351  0.284 -0.293 -0.743 |    62.4808937348  245.5192981420  180.92102     11.4    23.5    0.00389 |   6955341.27487 12628197.28099  180.92102 0.00126 0.00121 0.00389  0.006  0.042  0.257

Int. TRAK_GPS -2480029.24905 -4703110.82031  3511298.59513   -0.02924    0.02645    0.01537 2005.002
   16. TRAK_GPS X coordinate  (m)         -2480029.27820      0.00123      0.00216
   17. TRAK_GPS Y coordinate  (m)         -4703110.78310      0.00973      0.00452
   18. TRAK_GPS Z coordinate  (m)          3511298.60833     -0.00277      0.00322
Unc. TRAK_GPS -2480029.27820 -4703110.78310  3511298.60833   -0.02924    0.02645    0.01537 2006.040  0.0022  0.0045  0.0032
Apr. TRAK_GPS -2480029.27820 -4703110.78310  3511298.60833   -0.02924    0.02645    0.01537 2006.040  0.0022  0.0045  0.0032  -1.0000 -1.0000 -1.0000
Loc.   TRAK_GPS N coordinate  (m)          3742331.38969      0.00275      0.00148
Loc.   TRAK_GPS E coordinate  (m)         22451843.44336     -0.00345      0.00162
Loc.   TRAK_GPS U coordinate  (m)              115.53386     -0.00918      0.00554
     NE,NU,EU position correlations          0.1197      -0.0608       0.3902
pbo. TRAK_GPS ----------------  2006 01 15 11 59 53750.4998  -2480029.27820 -4703110.78310  3511298.60833 0.00216 0.00452 0.00322  0.679 -0.590 -0.854 |    33.6179348560  242.1965658728  115.53386     13.3    17.5    0.00554 |   3742331.38969 22451843.44336  115.53386 0.00148 0.00162 0.00554  0.120 -0.061  0.390

Int. HOB2_GPS -3950071.67350  2522415.25416 -4311638.02559   -0.03974    0.00862    0.04074 2005.002
   19. HOB2_GPS X coordinate  (m)         -3950071.71693     -0.00214      0.00288
   20. HOB2_GPS Y coordinate  (m)          2522415.26264     -0.00048      0.00224
   21. HOB2_GPS Z coordinate  (m)         -4311637.99552     -0.01226      0.00355
Unc. HOB2_GPS -3950071.71693  2522415.26264 -4311637.99552   -0.03974    0.00862    0.04074 2006.040  0.0029  0.0022  0.0036
Apr. HOB2_GPS -3950071.71693  2522415.26264 -4311637.99552   -0.03974    0.00862    0.04074 2006.040  0.0029  0.0022  0.0036  -1.0000 -1.0000 -1.0000
Loc.   HOB2_GPS N coordinate  (m)         -4764998.76970     -0.00798      0.00140
Loc.   HOB2_GPS E coordinate  (m)         12041419.15810      0.00155      0.00112
Loc.   HOB2_GPS U coordinate  (m)               41.06757      0.00944      0.00477
     NE,NU,EU position correlations          0.3505      -0.1705      -0.2785
pbo. HOB2_GPS ----------------  2006 01 15 11 59 53750.4998  -3950071.71693  2522415.26264 -4311637.99552 0.00288 0.00224 0.00355 -0.808  0.787 -0.854 |   -42.8047122364  147.4387345304   41.06757     12.6    13.7    0.00477 |  -4764998.76970 12041419.15810   41.06757 0.00140 0.00112 0.00477  0.351 -0.170 -0.279

Int. TOW2_GPS -5054582.94073  3275504.33760 -2091539.27586   -0.03094   -0.01432    0.05283 2005.002
   22. TOW2_GPS X coordinate  (m)         -5054582.97154      0.00134      0.00454
   23. TOW2_GPS Y coordinate  (m)          3275504.32816      0.00544      0.00303
   24. TOW2_GPS Z coordinate  (m)         -2091539.22725     -0.00628      0.00299
Unc. TOW2_GPS -5054582.97154  3275504.32816 -2091539.22725   -0.03094   -0.01432    0.05283 2006.040  0.0045  0.0030  0.0030
Apr. TOW2_GPS -5054582.97154  3275504.32816 -2091539.22725   -0.03094   -0.01432    0.05283 2006.040  0.0045  0.0030  0.0030  -1.0000 -1.0000 -1.0000
Loc.   TOW2_GPS N coordinate  (m)         -2145046.39036     -0.00533      0.00210
Loc.   TOW2_GPS E coordinate  (m)         15453122.46134     -0.00530      0.00135
Loc.   TOW2_GPS U coordinate  (m)               88.12323      0.00379      0.00570
     NE,NU,EU position correlations          0.2711      -0.2079       0.0228
pbo. TOW2_GPS ----------------  2006 01 15 11 59 53750.4998  -5054582.97154  3275504.32816 -2091539.22725 0.00454 0.00303 0.00299 -0.855  0.632 -0.701 |   -19.2692795761  147.0556883034   88.12323     18.8    12.9    0.00570 |  -2145046.39036 15453122.46134   88.12323 0.00210 0.00135 0.00570  0.271 -0.208  0.023

Int. GUAM_GPS -5071312.73778  3568363.55234  1488904.35997    0.00611    0.00737    0.00522 2005.002
   25. GUAM_GPS X coordinate  (m)         -5071312.71471      0.01672      0.00659
   26. GUAM_GPS Y coordinate  (m)          3568363.54956     -0.01043      0.00438
   27. GUAM_GPS Z coordinate  (m)          1488904.32876     -0.03663      0.00310
Unc. GUAM_GPS -5071312.71471  3568363.54956  1488904.32876    0.00611    0.00737    0.00522 2006.040  0.0066  0.0044  0.0031
Apr. GUAM_GPS -5071312.71471  3568363.54956  1488904.32876    0.00611    0.00737    0.00522 2006.040  0.0066  0.0044  0.0031  -1.0000 -1.0000 -1.0000
Loc.   GUAM_GPS N coordinate  (m)          1512757.21850     -0.03102      0.00276
Loc.   GUAM_GPS E coordinate  (m)         15675134.97645     -0.00109      0.00205
Loc.   GUAM_GPS U coordinate  (m)              201.89474     -0.02769      0.00777
     NE,NU,EU position correlations         -0.0893      -0.0906       0.1967
pbo. GUAM_GPS ----------------  2006 01 15 11 59 53750.4998  -5071312.71471  3568363.54956  1488904.32876 0.00659 0.00438 0.00310 -0.847 -0.417  0.420 |    13.5893293054  144.8683609454  201.89474     24.8    18.9    0.00777 |   1512757.21850 15675134.97645  201.89474 0.00276 0.00205 0.00777 -0.089 -0.091  0.197

Int. USUD_GPS -3855263.02241  3427432.54860  3741020.34317   -0.00468    0.00390   -0.00211 2005.002
   28. USUD_GPS X coordinate  (m)         -3855263.01399      0.01328      0.00367
   29. USUD_GPS Y coordinate  (m)          3427432.53624     -0.01641      0.00281
   30. USUD_GPS Z coordinate  (m)          3741020.28097     -0.06001      0.00345
Unc. USUD_GPS -3855263.01399  3427432.53624  3741020.28097   -0.00468    0.00390   -0.00211 2006.040  0.0037  0.0028  0.0035
Apr. USUD_GPS -3855263.01399  3427432.53624  3741020.28097   -0.00468    0.00390   -0.00211 2006.040  0.0037  0.0028  0.0035  -1.0000 -1.0000 -1.0000
Loc.   USUD_GPS N coordinate  (m)          4022319.44091     -0.03635      0.00252
Loc.   USUD_GPS E coordinate  (m)         12439689.10123      0.00344      0.00168
Loc.   USUD_GPS U coordinate  (m)             1508.58772     -0.05209      0.00490
     NE,NU,EU position correlations         -0.2258      -0.0466       0.1967
pbo. USUD_GPS ----------------  2006 01 15 11 59 53750.4998  -3855263.01399  3427432.53624  3741020.28097 0.00367 0.00281 0.00345 -0.734 -0.495  0.550 |    36.1331103138  138.3620436137 1508.58772     22.7    18.7    0.00490 |   4022319.44091 12439689.10123 1508.58772 0.00252 0.00168 0.00490 -0.226 -0.047  0.197

Int. DAV1_GPS   486854.55811  2285099.25423 -5914955.68461    0.00161   -0.00585   -0.00068 2005.002
   31. DAV1_GPS X coordinate  (m)           486854.54966     -0.01012      0.00204
   32. DAV1_GPS Y coordinate  (m)          2285099.24912      0.00097      0.00253
   33. DAV1_GPS Z coordinate  (m)         -5914955.68137      0.00395      0.00496
Unc. DAV1_GPS   486854.54966  2285099.24912 -5914955.68137    0.00161   -0.00585   -0.00068 2006.040  0.0020  0.0025  0.0050
Apr. DAV1_GPS   486854.54966  2285099.24912 -5914955.68137    0.00161   -0.00585   -0.00068 2006.040  0.0020  0.0025  0.0050  -1.0000 -1.0000 -1.0000
Loc.   DAV1_GPS N coordinate  (m)         -7633992.68483      0.00037      0.00122
Loc.   DAV1_GPS E coordinate  (m)          3170252.89295      0.01010      0.00224
Loc.   DAV1_GPS U coordinate  (m)               44.38270     -0.00410      0.00536
     NE,NU,EU position correlations          0.0849       0.0922       0.4329
pbo. DAV1_GPS ----------------  2006 01 15 11 59 53750.4998    486854.54966  2285099.24912 -5914955.68137 0.00204 0.00253 0.00496 -0.352  0.258 -0.836 |   -68.5773230764   77.9726134030   44.38270     11.0    55.0    0.00536 |  -7633992.68483  3170252.89295   44.38270 0.00122 0.00224 0.00536  0.085  0.092  0.433

Int. POL2_GPS  1239971.36992  4530790.09428  4302578.81606   -0.02731    0.00533    0.00479 2005.002
   34. POL2_GPS X coordinate  (m)          1239971.34040     -0.00115      0.00145
   35. POL2_GPS Y coordinate  (m)          4530790.09498     -0.00484      0.00224
   36. POL2_GPS Z coordinate  (m)          4302578.82207      0.00103      0.00275
Unc. POL2_GPS  1239971.34040  4530790.09498  4302578.82207   -0.02731    0.00533    0.00479 2006.040  0.0014  0.0022  0.0027
Apr. POL2_GPS  1239971.34040  4530790.09498  4302578.82207   -0.02731    0.00533    0.00479 2006.040  0.0014  0.0022  0.0027  -1.0000 -1.0000 -1.0000
Loc.   POL2_GPS N coordinate  (m)          4751090.27619      0.00412      0.00142
Loc.   POL2_GPS E coordinate  (m)          6112787.08095     -0.00017      0.00121
Loc.   POL2_GPS U coordinate  (m)             1714.20636     -0.00297      0.00334
     NE,NU,EU position correlations         -0.2860       0.2843      -0.3323
pbo. POL2_GPS ----------------  2006 01 15 11 59 53750.4998   1239971.34040  4530790.09498  4302578.82207 0.00145 0.00224 0.00275  0.504  0.619  0.677 |    42.6797701133   74.6942653758 1714.20636     12.8    14.8    0.00334 |   4751090.27619  6112787.08095 1714.20636 0.00142 0.00121 0.00334 -0.286  0.284 -0.332

Int. KERG_GPS  1406337.28912  3918161.09296 -4816167.35661   -0.00527   -0.00015   -0.00151 2005.002
   37. KERG_GPS X coordinate  (m)          1406337.27867     -0.00498      0.00233
   38. KERG_GPS Y coordinate  (m)          3918161.09468      0.00188      0.00372
   39. KERG_GPS Z coordinate  (m)         -4816167.35561      0.00257      0.00521
Unc. KERG_GPS  1406337.27867  3918161.09468 -4816167.35561   -0.00527   -0.00015   -0.00151 2006.040  0.0023  0.0037  0.0052
Apr. KERG_GPS  1406337.27867  3918161.09468 -4816167.35561   -0.00527   -0.00015   -0.00151 2006.040  0.0023  0.0037  0.0052  -1.0000 -1.0000 -1.0000
Loc.   KERG_GPS N coordinate  (m)         -5493780.15745      0.00175      0.00198
Loc.   KERG_GPS E coordinate  (m)          5094560.97825      0.00532      0.00253
Loc.   KERG_GPS U coordinate  (m)               73.00631     -0.00189      0.00600
     NE,NU,EU position correlations         -0.3907      -0.4083       0.4196
pbo. KERG_GPS ----------------  2006 01 15 11 59 53750.4998   1406337.27867  3918161.09468 -4816167.35561 0.00233 0.00372 0.00521 -0.003  0.052 -0.844 |   -49.3514668303   70.2555221807   73.00631     17.8    34.9    0.00600 |  -5493780.15745  5094560.97825   73.00631 0.00198 0.00253 0.00600 -0.391 -0.408  0.420

Int. KIRU_GPS  2251420.79504   862817.22093  5885476.70247   -0.01574    0.01076    0.01142 2005.002
   40. KIRU_GPS X coordinate  (m)          2251420.77390     -0.00479      0.00160
   41. KIRU_GPS Y coordinate  (m)           862817.22945     -0.00266      0.00089
   42. KIRU_GPS Z coordinate  (m)          5885476.71183     -0.00250      0.00332
Unc. KIRU_GPS  2251420.77390   862817.22945  5885476.71183   -0.01574    0.01076    0.01142 2006.040  0.0016  0.0009  0.0033
Apr. KIRU_GPS  2251420.77390   862817.22945  5885476.71183   -0.01574    0.01076    0.01142 2006.040  0.0016  0.0009  0.0033  -1.0000 -1.0000 -1.0000
Loc.   KIRU_GPS N coordinate  (m)          7553845.84120      0.00407      0.00101
Loc.   KIRU_GPS E coordinate  (m)           879764.88328     -0.00078      0.00085
Loc.   KIRU_GPS U coordinate  (m)              390.97575     -0.00437      0.00356
     NE,NU,EU position correlations          0.1006       0.0153      -0.1425
pbo. KIRU_GPS ----------------  2006 01 15 11 59 53750.4998   2251420.77390   862817.22945  5885476.71183 0.00160 0.00089 0.00332  0.326  0.734  0.372 |    67.8573517303   20.9684476246  390.97575      9.1    20.1    0.00356 |   7553845.84120   879764.88328  390.97575 0.00101 0.00085 0.00356  0.101  0.015 -0.142

Int. MATE_GPS  4641949.55683  1393045.42466  4133287.46435   -0.01829    0.01899    0.01495 2005.002
   43. MATE_GPS X coordinate  (m)          4641949.53982      0.00199      0.00223
   44. MATE_GPS Y coordinate  (m)          1393045.44397     -0.00042      0.00106
   45. MATE_GPS Z coordinate  (m)          4133287.47979     -0.00010      0.00211
Unc. MATE_GPS  4641949.53982  1393045.44397  4133287.47979   -0.01829    0.01899    0.01495 2006.040  0.0022  0.0011  0.0021
Apr. MATE_GPS  4641949.53982  1393045.44397  4133287.47979   -0.01829    0.01899    0.01495 2006.040  0.0022  0.0011  0.0021  -1.0000 -1.0000 -1.0000
Loc.   MATE_GPS N coordinate  (m)          4525040.65835     -0.00123      0.00083
Loc.   MATE_GPS E coordinate  (m)          1410869.02835     -0.00097      0.00084
Loc.   MATE_GPS U coordinate  (m)              535.65239      0.00130      0.00302
     NE,NU,EU position correlations         -0.1075       0.0900      -0.0092
pbo. MATE_GPS ----------------  2006 01 15 11 59 53750.4998   4641949.53982  1393045.44397  4133287.47979 0.00223 0.00106 0.00211  0.555  0.862  0.511 |    40.6491318466   16.7044596727  535.65239      7.4    10.0    0.00302 |   4525040.65835  1410869.02835  535.65239 0.00083 0.00084 0.00302 -0.108  0.090 -0.009

Int. WTZR_GPS  4075580.55298   931853.79721  4801568.13598   -0.01605    0.01713    0.01009 2005.002
   46. WTZR_GPS X coordinate  (m)          4075580.53166     -0.00464      0.00197
   47. WTZR_GPS Y coordinate  (m)           931853.81228     -0.00273      0.00081
   48. WTZR_GPS Z coordinate  (m)          4801568.13954     -0.00693      0.00223
Unc. WTZR_GPS  4075580.53166   931853.81228  4801568.13954   -0.01605    0.01713    0.01009 2006.040  0.0020  0.0008  0.0022
Apr. WTZR_GPS  4075580.53166   931853.81228  4801568.13954   -0.01605    0.01713    0.01009 2006.040  0.0020  0.0008  0.0022  -1.0000 -1.0000 -1.0000
Loc.   WTZR_GPS N coordinate  (m)          5470707.16366     -0.00068      0.00077
Loc.   WTZR_GPS E coordinate  (m)           937828.67915     -0.00162      0.00070
Loc.   WTZR_GPS U coordinate  (m)              666.01928     -0.00859      0.00290
     NE,NU,EU position correlations         -0.0211      -0.0280      -0.0447
pbo. WTZR_GPS ----------------  2006 01 15 11 59 53750.4998   4075580.53166   931853.81228  4801568.13954 0.00197 0.00081 0.00223  0.454  0.867  0.440 |    49.1441986005   12.8789100274  666.01928      6.9     9.7    0.00290 |   5470707.16366   937828.67915  666.01928 0.00077 0.00070 0.00290 -0.021 -0.028 -0.045

Int. NYAL_GPS  1202430.53162   252626.70891  6237767.61729   -0.01430    0.00750    0.01103 2005.002
   49. NYAL_GPS X coordinate  (m)          1202430.51758      0.00081      0.00118
   50. NYAL_GPS Y coordinate  (m)           252626.71876      0.00206      0.00080
   51. NYAL_GPS Z coordinate  (m)          6237767.63829      0.00954      0.00396
Unc. NYAL_GPS  1202430.51758   252626.71876  6237767.63829   -0.01430    0.00750    0.01103 2006.040  0.0012  0.0008  0.0040
Apr. NYAL_GPS  1202430.51758   252626.71876  6237767.63829   -0.01430    0.00750    0.01103 2006.040  0.0012  0.0008  0.0040  -1.0000 -1.0000 -1.0000
Loc.   NYAL_GPS N coordinate  (m)          8786401.20410      0.00065      0.00097
Loc.   NYAL_GPS E coordinate  (m)           253597.01133      0.00185      0.00080
Loc.   NYAL_GPS U coordinate  (m)               78.53214      0.00960      0.00402
     NE,NU,EU position correlations          0.0132       0.0663      -0.0815
pbo. NYAL_GPS ----------------  2006 01 15 11 59 53750.4998   1202430.51758   252626.71876  6237767.63829 0.00118 0.00080 0.00396  0.105  0.565  0.093 |    78.9295849405   11.8650871025   78.53214      8.7    37.2    0.00402 |   8786401.20410   253597.01133   78.53214 0.00097 0.00080 0.00402  0.013  0.066 -0.082

Int. ZIMM_GPS  4331297.06286   567555.87751  4633133.93566   -0.01353    0.01807    0.01205 2005.002
   52. ZIMM_GPS X coordinate  (m)          4331297.04943      0.00062      0.00179
   53. ZIMM_GPS Y coordinate  (m)           567555.89593     -0.00035      0.00068
   54. ZIMM_GPS Z coordinate  (m)          4633133.94650     -0.00168      0.00193
Unc. ZIMM_GPS  4331297.04943   567555.89593  4633133.94650   -0.01353    0.01807    0.01205 2006.040  0.0018  0.0007  0.0019
Apr. ZIMM_GPS  4331297.04943   567555.89593  4633133.94650   -0.01353    0.01807    0.01205 2006.040  0.0018  0.0007  0.0019  -1.0000 -1.0000 -1.0000
Loc.   ZIMM_GPS N coordinate  (m)          5218334.64296     -0.00157      0.00066
Loc.   ZIMM_GPS E coordinate  (m)           568072.18842     -0.00043      0.00064
Loc.   ZIMM_GPS U coordinate  (m)              956.33242     -0.00083      0.00256
     NE,NU,EU position correlations         -0.0382       0.0279       0.0036
pbo. ZIMM_GPS ----------------  2006 01 15 11 59 53750.4998   4331297.04943   567555.89593  4633133.94650 0.00179 0.00068 0.00193  0.316  0.874  0.298 |    46.8770976743    7.4652770454  956.33242      6.0     8.4    0.00256 |   5218334.64296   568072.18842  956.33242 0.00066 0.00064 0.00256 -0.038  0.028  0.004

Eph. #IC  6  15 12  0  0                    GPST J2000 IAU76 BERNE
   55. PRN_0132 AntOffest X   (m)                0.27900      0.00000      0.00000
   56. PRN_0132 AntOffest Y   (m)                             0.00000      0.00000
   57. PRN_0132 AntOffest Z   (m)                2.38080      0.00000      0.00000
Eph.  2006  1 15 11 PRN_0132         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.38080

   58. PRN_0261 AntOffest X   (m)                             0.00000      0.00000
   59. PRN_0261 AntOffest Y   (m)                             0.00000      0.00000
   60. PRN_0261 AntOffest Z   (m)                0.77860      0.00000      0.00000
Eph.  2006  1 15 11 PRN_0261         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.77860

   61. PRN_0333 AntOffest X   (m)                0.27900      0.00000      0.00000
   62. PRN_0333 AntOffest Y   (m)                             0.00000      0.00000
   63. PRN_0333 AntOffest Z   (m)                2.79260      0.00000      0.00000
Eph.  2006  1 15 11 PRN_0333         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.79260

   64. PRN_0434 AntOffest X   (m)                0.27900      0.00000      0.00000
   65. PRN_0434 AntOffest Y   (m)                             0.00000      0.00000
   66. PRN_0434 AntOffest Z   (m)                2.42000      0.00000      0.00000
Eph.  2006  1 15 11 PRN_0434         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.42000

   67. PRN_0535 AntOffest X   (m)                0.27900      0.00000      0.00000
   68. PRN_0535 AntOffest Y   (m)                             0.00000      0.00000
   69. PRN_0535 AntOffest Z   (m)                2.62200      0.00000      0.00000
Eph.  2006  1 15 11 PRN_0535         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.62200

   70. PRN_0636 AntOffest X   (m)                0.27900      0.00000      0.00000
   71. PRN_0636 AntOffest Y   (m)                             0.00000      0.00000
   72. PRN_0636 AntOffest Z   (m)                2.87860      0.00000      0.00000
Eph.  2006  1 15 11 PRN_0636         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.87860

   73. PRN_0737 AntOffest X   (m)                0.27900      0.00000      0.00000
   74. PRN_0737 AntOffest Y   (m)                             0.00000      0.00000
   75. PRN_0737 AntOffest Z   (m)                2.35220      0.00000      0.00000
Eph.  2006  1 15 11 PRN_0737         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.35220

   76. PRN_0838 AntOffest X   (m)                0.27900      0.00000      0.00000
   77. PRN_0838 AntOffest Y   (m)                             0.00000      0.00000
   78. PRN_0838 AntOffest Z   (m)                2.57810      0.00000      0.00000
Eph.  2006  1 15 11 PRN_0838         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.57810

   79. PRN_0939 AntOffest X   (m)                0.27900      0.00000      0.00000
   80. PRN_0939 AntOffest Y   (m)                             0.00000      0.00000
   81. PRN_0939 AntOffest Z   (m)                2.46140      0.00000      0.00000
Eph.  2006  1 15 11 PRN_0939         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.46140

   82. PRN_1040 AntOffest X   (m)                0.27900      0.00000      0.00000
   83. PRN_1040 AntOffest Y   (m)                             0.00000      0.00000
   84. PRN_1040 AntOffest Z   (m)                2.54650      0.00000      0.00000
Eph.  2006  1 15 11 PRN_1040         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.54650

   85. PRN_1146 AntOffest X   (m)                             0.00000      0.00000
   86. PRN_1146 AntOffest Y   (m)                             0.00000      0.00000
   87. PRN_1146 AntOffest Z   (m)                1.14130      0.00000      0.00000
Eph.  2006  1 15 11 PRN_1146         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.14130

   88. PRN_1343 AntOffest X   (m)                             0.00000      0.00000
   89. PRN_1343 AntOffest Y   (m)                             0.00000      0.00000
   90. PRN_1343 AntOffest Z   (m)                1.38950      0.00000      0.00000
Eph.  2006  1 15 11 PRN_1343         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.38950

   91. PRN_1441 AntOffest X   (m)                             0.00000      0.00000
   92. PRN_1441 AntOffest Y   (m)                             0.00000      0.00000
   93. PRN_1441 AntOffest Z   (m)                1.34540      0.00000      0.00000
Eph.  2006  1 15 11 PRN_1441         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.34540

   94. PRN_1515 AntOffest X   (m)                0.27900      0.00000      0.00000
   95. PRN_1515 AntOffest Y   (m)                             0.00000      0.00000
   96. PRN_1515 AntOffest Z   (m)                2.46860      0.00000      0.00000
Eph.  2006  1 15 11 PRN_1515         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.46860

   97. PRN_1656 AntOffest X   (m)                             0.00000      0.00000
   98. PRN_1656 AntOffest Y   (m)                             0.00000      0.00000
   99. PRN_1656 AntOffest Z   (m)                1.50640      0.00000      0.00000
Eph.  2006  1 15 11 PRN_1656         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.50640

  100. PRN_1753 AntOffest X   (m)                             0.00000      0.00000
  101. PRN_1753 AntOffest Y   (m)                             0.00000      0.00000
  102. PRN_1753 AntOffest Z   (m)                0.82710      0.00000      0.00000
Eph.  2006  1 15 11 PRN_1753         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.82710

  103. PRN_1854 AntOffest X   (m)                             0.00000      0.00000
  104. PRN_1854 AntOffest Y   (m)                             0.00000      0.00000
  105. PRN_1854 AntOffest Z   (m)                1.29090      0.00000      0.00000
Eph.  2006  1 15 11 PRN_1854         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.29090

  106. PRN_1959 AntOffest X   (m)                             0.00000      0.00000
  107. PRN_1959 AntOffest Y   (m)                             0.00000      0.00000
  108. PRN_1959 AntOffest Z   (m)                0.84960      0.00000      0.00000
Eph.  2006  1 15 11 PRN_1959         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.84960

  109. PRN_2051 AntOffest X   (m)                             0.00000      0.00000
  110. PRN_2051 AntOffest Y   (m)                             0.00000      0.00000
  111. PRN_2051 AntOffest Z   (m)                1.34360      0.00000      0.00000
Eph.  2006  1 15 11 PRN_2051         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.34360

  112. PRN_2145 AntOffest X   (m)                             0.00000      0.00000
  113. PRN_2145 AntOffest Y   (m)                             0.00000      0.00000
  114. PRN_2145 AntOffest Z   (m)                1.40540      0.00000      0.00000
Eph.  2006  1 15 11 PRN_2145         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.40540

  115. PRN_2247 AntOffest X   (m)                             0.00000      0.00000
  116. PRN_2247 AntOffest Y   (m)                             0.00000      0.00000
  117. PRN_2247 AntOffest Z   (m)                0.90580      0.00000      0.00000
Eph.  2006  1 15 11 PRN_2247         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.90580

  118. PRN_2360 AntOffest X   (m)                             0.00000      0.00000
  119. PRN_2360 AntOffest Y   (m)                             0.00000      0.00000
  120. PRN_2360 AntOffest Z   (m)                0.80820      0.00000      0.00000
Eph.  2006  1 15 11 PRN_2360         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.80820

  121. PRN_2424 AntOffest X   (m)                0.27900      0.00000      0.00000
  122. PRN_2424 AntOffest Y   (m)                             0.00000      0.00000
  123. PRN_2424 AntOffest Z   (m)                2.60380      0.00000      0.00000
Eph.  2006  1 15 11 PRN_2424         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.60380

  124. PRN_2525 AntOffest X   (m)                0.27900      0.00000      0.00000
  125. PRN_2525 AntOffest Y   (m)                             0.00000      0.00000
  126. PRN_2525 AntOffest Z   (m)                2.48900      0.00000      0.00000
Eph.  2006  1 15 11 PRN_2525         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.48900

  127. PRN_2626 AntOffest X   (m)                0.27900      0.00000      0.00000
  128. PRN_2626 AntOffest Y   (m)                             0.00000      0.00000
  129. PRN_2626 AntOffest Z   (m)                2.45940      0.00000      0.00000
Eph.  2006  1 15 11 PRN_2626         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.45940

  130. PRN_2727 AntOffest X   (m)                0.27900      0.00000      0.00000
  131. PRN_2727 AntOffest Y   (m)                             0.00000      0.00000
  132. PRN_2727 AntOffest Z   (m)                2.63340      0.00000      0.00000
Eph.  2006  1 15 11 PRN_2727         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.63340

  133. PRN_2844 AntOffest X   (m)                             0.00000      0.00000
  134. PRN_2844 AntOffest Y   (m)                             0.00000      0.00000
  135. PRN_2844 AntOffest Z   (m)                1.04280      0.00000      0.00000
Eph.  2006  1 15 11 PRN_2844         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.04280

  136. PRN_2929 AntOffest X   (m)                0.27900      0.00000      0.00000
  137. PRN_2929 AntOffest Y   (m)                             0.00000      0.00000
  138. PRN_2929 AntOffest Z   (m)                2.51430      0.00000      0.00000
Eph.  2006  1 15 11 PRN_2929         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.51430

  139. PRN_3030 AntOffest X   (m)                0.27900      0.00000      0.00000
  140. PRN_3030 AntOffest Y   (m)                             0.00000      0.00000
  141. PRN_3030 AntOffest Z   (m)                2.61270      0.00000      0.00000
Eph.  2006  1 15 11 PRN_3030         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.61270

  142. X-pole position        (mas)             49.50983     -0.01017      0.04250
  143. Y-pole position        (mas)            380.07182     -0.04018      0.04534

  144. UT1-AT                 (ms)          -32665.89929      0.00571      0.00160
      Pole/UT1 correlations: XY, XU, YU          0.5383     0.0526     0.2512

IERS  MJD      Xpole   Ypole  UT1-UTC    LOD  Xsig  Ysig   UTsig  LODsig  Nr Nf Nt    Xrt    Yrt  Xrtsig  Yrtsig XYcorr XUTcor YUTcor
IERS             (10**-6")       (0.1 usec)    (10**-6")     (0.1 usec)              (10**-6"/d)    (10**-6"/d)
IERS53750.50   49510  380072  3341007    130    42    45      16       0  18 13 29    744    -66      0      0    0.538  0.053  0.251


