Globk Analysis

 +++++++++++++++++++++++++++++++++++++
 + GLORG                 Version 5.19 +
 +++++++++++++++++++++++++++++++++++++


 Stabilization with  20.0% constant,  80.0% site dependent weighting.
 Delete sites with   3.0-sigma condition.
 Height variance factor      10.00 Position,     10.00 Velocity
 For Position: Min dH sigma 0.0050 m;    Min RMS 0.0030 m,    Min dNE sigma 0.00050 m
 For Velocity: Min dH sigma 0.0050 m/yr; Min RMS 0.0030 m/yr, Min dNE sigma 0.00010 m/yr
 Sigma Ratio to allow use: Position   3.00 Velocity   3.00

====================================================================================================
 Starting Position stabilization iteration   1 L0601141200_thss.glx
 For   18 sites in origin, min/max height sigma       7.83     10.80 mm; Median        8.94 mm, Tol      15.00 mm L0601141200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)    -1.52232 +-    0.90147 Iter  1 L0601141200_thss.glx
 Y Rotation  (mas)    -0.60276 +-    0.93217 Iter  1 L0601141200_thss.glx
 Z Rotation  (mas)    -2.45436 +-    1.00855 Iter  1 L0601141200_thss.glx
 X Translation (m)    -0.08639 +-    0.02773 Iter  1 L0601141200_thss.glx
 Y Translation (m)     0.01338 +-    0.02703 Iter  1 L0601141200_thss.glx
 Z Translation (m)    -0.03659 +-    0.02885 Iter  1 L0601141200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   1.00  REYK_GPS   1.00  CRO1_GPS   1.00  AREQ_GPS   1.00  YELL_GPS   1.00  TRAK_GPS   1.00 
HOB2_GPS   1.00  TOW2_GPS   1.00  GUAM_GPS   1.00  USUD_GPS   1.00  DAV1_GPS   1.00  POL2_GPS   1.00 
KERG_GPS   1.00  KIRU_GPS   1.00  MATE_GPS   1.00  WTZR_GPS   1.00  NYAL_GPS   1.00  ZIMM_GPS   1.00 
 For   54 Position Iter  1 Pre RMS    0.0858 m; Post RMS   0.07549 m L0601141200_thss.glx
 For   18 sites in origin, min/max NE sigma       1.38      3.85 mm; Median        2.24 mm, Tol       2.56 mm L0601141200_thss.glx
Deleting AREQ_GPS Position error   0.5788 m, relative variance     2.02 Nsigma     5.39

====================================================================================================
 Starting Position stabilization iteration   2 L0601141200_thss.glx
 For   17 sites in origin, min/max height sigma       7.83     10.68 mm; Median        8.81 mm, Tol      15.00 mm L0601141200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)     0.29419 +-    0.07022 Iter  2 L0601141200_thss.glx
 Y Rotation  (mas)     0.10986 +-    0.07858 Iter  2 L0601141200_thss.glx
 Z Rotation  (mas)     0.06295 +-    0.07869 Iter  2 L0601141200_thss.glx
 X Translation (m)     0.00041 +-    0.00229 Iter  2 L0601141200_thss.glx
 Y Translation (m)    -0.00776 +-    0.00213 Iter  2 L0601141200_thss.glx
 Z Translation (m)     0.01737 +-    0.00217 Iter  2 L0601141200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   0.81  REYK_GPS   0.81  CRO1_GPS   1.00  YELL_GPS   0.88  TRAK_GPS   1.00  HOB2_GPS   1.01 
TOW2_GPS   1.07  GUAM_GPS   1.22  USUD_GPS   1.05  DAV1_GPS   1.19  POL2_GPS   0.92  KERG_GPS   1.32 
KIRU_GPS   0.82  MATE_GPS   0.83  WTZR_GPS   0.78  NYAL_GPS   0.77  ZIMM_GPS   0.76 
 For   51 Position Iter  2 Pre RMS    0.0105 m; Post RMS   0.00547 m L0601141200_thss.glx
 For   17 sites in origin, min/max NE sigma       1.09      3.84 mm; Median        1.88 mm, Tol       2.40 mm L0601141200_thss.glx
Deleting REYK_GPS Position error   0.0167 m, relative variance     0.66 Nsigma     3.76
Deleting YELL_GPS Position error   0.0163 m, relative variance     0.77 Nsigma     3.40
Deleting USUD_GPS Position error   0.0231 m, relative variance     1.21 Nsigma     3.84

====================================================================================================
 Starting Position stabilization iteration   3 L0601141200_thss.glx
 For   14 sites in origin, min/max height sigma       7.95     10.68 mm; Median        8.94 mm, Tol      15.00 mm L0601141200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)     0.26276 +-    0.04827 Iter  3 L0601141200_thss.glx
 Y Rotation  (mas)     0.06885 +-    0.05815 Iter  3 L0601141200_thss.glx
 Z Rotation  (mas)     0.09592 +-    0.06000 Iter  3 L0601141200_thss.glx
 X Translation (m)     0.00121 +-    0.00165 Iter  3 L0601141200_thss.glx
 Y Translation (m)    -0.00727 +-    0.00146 Iter  3 L0601141200_thss.glx
 Z Translation (m)     0.01882 +-    0.00162 Iter  3 L0601141200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   0.77  CRO1_GPS   1.13  TRAK_GPS   1.03  HOB2_GPS   0.96  TOW2_GPS   1.09  GUAM_GPS   1.32 
DAV1_GPS   1.29  POL2_GPS   0.90  KERG_GPS   1.49  KIRU_GPS   0.81  MATE_GPS   0.78  WTZR_GPS   0.74 
NYAL_GPS   0.76  ZIMM_GPS   0.71 
 For   42 Position Iter  3 Pre RMS    0.0102 m; Post RMS   0.00357 m L0601141200_thss.glx
 For   14 sites in origin, min/max NE sigma       0.98      3.96 mm; Median        1.85 mm, Tol       2.62 mm L0601141200_thss.glx
Deleting TRAK_GPS Position error   0.0112 m, relative variance     1.05 Nsigma     3.06
Deleting GUAM_GPS Position error   0.0186 m, relative variance     1.84 Nsigma     3.84
Deleting POL2_GPS Position error   0.0100 m, relative variance     0.79 Nsigma     3.17

====================================================================================================
 Starting Position stabilization iteration   4 L0601141200_thss.glx
 For   11 sites in origin, min/max height sigma       8.22     10.34 mm; Median        9.08 mm, Tol      15.00 mm L0601141200_thss.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)     0.26212 +-    0.03573 Iter  4 L0601141200_thss.glx
 Y Rotation  (mas)     0.03201 +-    0.04883 Iter  4 L0601141200_thss.glx
 Z Rotation  (mas)     0.15157 +-    0.05738 Iter  4 L0601141200_thss.glx
 X Translation (m)     0.00189 +-    0.00128 Iter  4 L0601141200_thss.glx
 Y Translation (m)    -0.00732 +-    0.00106 Iter  4 L0601141200_thss.glx
 Z Translation (m)     0.01805 +-    0.00140 Iter  4 L0601141200_thss.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
VILL_GPS   0.75  CRO1_GPS   1.12  HOB2_GPS   0.87  TOW2_GPS   1.03  DAV1_GPS   1.30  KERG_GPS   1.50 
KIRU_GPS   0.79  MATE_GPS   0.75  WTZR_GPS   0.71  NYAL_GPS   0.76  ZIMM_GPS   0.69 
 For   33 Position Iter  4 Pre RMS    0.0103 m; Post RMS   0.00252 m L0601141200_thss.glx
 For   11 sites in origin, min/max NE sigma       0.92      3.79 mm; Median        1.42 mm, Tol       1.50 mm L0601141200_thss.glx
 Removing DAV1_GPS from orgin condition, NE sigma       3.19 mm, Ratio Tol  3.000 L0601141200_thss.glx
 Removing KERG_GPS from orgin condition, NE sigma       3.79 mm, Ratio Tol  3.000 L0601141200_thss.glx
Rotating into local coordinates for equates
 Checking covariance matrix after equate and force
Globk Analysis


---------------------------------------------------------
 GLOBK Ver 5.29, Global solution
---------------------------------------------------------

 Solution commenced with: 2006/ 1/14  0: 0    (2006.0356)
 Solution ended with    : 2006/ 1/14 23:59    (2006.0384)
 Solution refers to     : 2006/ 1/14 11:59    (2006.0370) [Seconds tag  45.000]
 Satellite IC epoch     : 2006/ 1/14 12: 0  0.00
 GPS System Information : Time GPST Frame J2000 Precession IAU76 Radiation model BERNE Nutation IAU00 Gravity EGM08 EarthRad NONE  AntThrust NONE 
 MODELS Used in Analysis: SD-WOB  | SD-UT1  | IERS10  | E-Tide  | K1-Tide | PoleTide| OC-Load | MPT2010 |  
 ATM Delay Models Used  : GP25    | GP25    | GP25    | GP25    | 2nd Order Ion     | NONE    | UNKNOWN | 
 Reference Frame        : IGb08           
 Run time               : 2015/12/17 15:14 46.00

 There were         1 exps from          1 global files in the solution
 There were       246056 data used,       0 data not used and       246056 data total
 There were          144 global parameters estimated
 There were    18 Sites,   18 Used Sites,    0 radio sources, and   29 Satellites

 The  prefit chi**2 for      54 input parameters is     0.000

 LIST file      : L0601141200_thss.glx
 COMMON file    :  
 GLOBK CMD file : globk_comb.cmd
 GLORG CMD file : glorg_comb.cmd
 APRIORI file   : ../tables/itrf08_comb.apr
 APRIORI file   : ../tables/itrf08_comb.apr (glorg)
 NUTATION file  :  
 PLANETARY file :  
 SD ORIENT file :  
 PMU file       :  
 BACK SOLN file :  
 OUTGLOBAL file :  
 SVS EPHEM file :  
 SVS MARKOV file:  

* RENAME REPORT (RNRP option)
*   Sites             dN        sN       dE       sE     dU         sU  Units Compare date  EQ Dist EQ Name
* EARTHQUAKE LOG FITS
*  Sites             dN        sN       dE       sE     dU         sU   mm

 Summary of GLOBK command file globk_comb.cmd
-------------------------------------------------------------------------------
* GLOBK command file to generate daily time series and to combine
* h-files over 2 to 30 days.
* For combination, set COMB as a globk command-line option to
* invoke the saving of the output h-file
* Last edited by rwk 130701
* << column 1 must be blank if not comment >>
* This group of commands must appear before any others:
 srt_file @.srt
 srt_dir +1
# Optionally add a second eq_file for analysis-specific renames
* End commands that must appear first
* ITRF2008 augmented by now-defunct sites and recent IGS solutions;
# matched to itrf08_comb.eq
 apr_file ../tables/itrf08_comb.apr
# Optionally add additional apr files for other sites
* Set maximum chi2, prefit coordinate difference (m), and rotation (mas) for an h-file to be used;
 max_chii 13 3 100
# increase tolerances to include all files for diagnostics
# Not necessary unless combining h-files with different a priori EOP
 in_pmu ../tables/pmu.usno
* Invoke glorg
 org_cmd glorg_comb.cmd
* Print file options
 crt_opt NOPR
 prt_opt NOPR GDLF CMDS MIDP
 org_opt PSUM CMDS GDLF MIDP FIXA RNRP
# sh_glred will name the glorg print files
* Coordinate parameters to be estimated and a priori constraints
 apr_neu  all 10 10 10  0 0 0
* Rotation parameters to be estimated and a priori constraints
 apr_wob  5 5 0 0
 apr_ut1  5 0
# If combining with global h-files, allow EOPS to change
# between days
# EOP tight if translation-only stabilization in glorg
* Write out a combined H-file
# Can substitute your analysis name for 'COMB' in the file name below
COMB out_glb  H------_COMB.GLX
* Optionally put a uselist and/or sig_neu and mar_neu reweight in a source file
* Turn off quake log estimates if in the eq_file
 free_log -1
* Remove scratch files for repeatability runs
  del_scra yes
* Correct the pole tide when not compatible with GAMIT
  app_ptid all
* If orbits free in GAMIT (RELAX) and you want them fixed, use:
* but if you are combining with globk h-files, better to leave them
* on but, if the models are incompatible, turn off radiation-pressure parameters,
* When using MIT GLX files which have satellite phase center positions
* estimated use:
  apr_svan all  F F F     ! Fix antenna offset to IGS apriori values.
-------------------------------------------------------------------------------

 Summary of GLORG command file glorg_comb.cmd
-------------------------------------------------------------------------------
* Glorg command file for daily repeatabilities or combinations
* Last edited by rwk 130701
* Parameters to be estimated
 pos_org  xtran ytran ztran xrot yrot zrot
#   or if translation-only
* Downweight of height relative to horizontal (default is 10)
#   Heavy downweight if reference frame robust and heights suspect
* Controls for removing sites from the stabilization
#   Vary these to make the stabilization more robust or more precise
 stab_it 4 0.8 3.0
* A priori coordinates
#  ITRF2008 may be replaced by an apr file from a priori velocity solution
 apr_file ../tables/itrf08_comb.apr
* List of stabilization sites
#   This should match the well-determined sites in the apr_file
 stab_site clear
 source ../tables/igb08_hierarchy.stab_site
SOURCE ># Sites in IGb08 network hierarchy from ftp://igs-rf.ign.fr/pub/IGb08/IGb08_core.txt
SOURCE ># Created with core2stab_site.sh by Mike Floyd on 2014-08-08
SOURCE > stab_site AREQ
SOURCE > stab_site CRO1
SOURCE > stab_site DAV1
SOURCE > stab_site GUAM
SOURCE > stab_site HOB2
SOURCE > stab_site KERG
SOURCE > stab_site KIRU
SOURCE > stab_site MATE
SOURCE > stab_site NYAL
SOURCE > stab_site POL2
SOURCE > stab_site REYK
SOURCE > stab_site TOW2
SOURCE > stab_site TRAK
SOURCE > stab_site USUD
SOURCE > stab_site VILL
SOURCE > stab_site WTZR
SOURCE > stab_site YELL
SOURCE > stab_site ZIMM
SOURCE > 
SOURCE > 
-------------------------------------------------------------------------------

 EXPERIMENT LIST from L0601141200_thss.srt
     #  Name                               SCALE Diag PPM  Forw Chi2 Back Chi2 Status
     1 ../glbf/h0601141200_thss.glx     1.000000   0.000     0.000    -1.000   USED        

 SUMMARY POSITION ESTIMATES FROM GLOBK Ver 5.29        
    Long.       Lat.        dE adj.   dN adj.   dE +-     dN +-   RHO        dH adj.   dH +-  SITE
    (deg)      (deg)         (mm)      (mm)      (mm)      (mm)               (mm)      (mm)
  356.04802   40.44359       2.48      3.31      0.77      0.92 -0.020       13.86      3.53 VILL_GPS*
  338.04451   64.13878     -14.65      8.39      1.14      1.34 -0.019      -25.51      4.12 REYK_GPS 
  295.41568   17.75690      -4.61     -1.36      1.78      2.12  0.544       -2.91      5.93 CRO1_GPS*
  288.50720  -16.46552    -634.20   -441.16      2.89      4.16  0.418      -14.05      8.90 AREQ_GPS 
  245.51930   62.48089       3.53     12.47      1.78      1.94  0.088       20.22      4.11 YELL_GPS 
  242.19657   33.61793      -9.32      9.40      2.47      2.41  0.126       -9.37      5.53 TRAK_GPS 
  147.43873  -42.80471       1.60     -2.86      0.89      1.11  0.267        5.24      5.25 HOB2_GPS*
  147.05569  -19.26928      -0.88     -2.80      1.07      2.14  0.203       10.28      5.55 TOW2_GPS*
  144.86836   13.58933       3.02    -18.40      2.36      3.54 -0.120        4.38      8.90 GUAM_GPS 
  138.36204   36.13311       0.58    -24.74      1.78      3.14 -0.210      -30.79      5.27 USUD_GPS 
   77.97261  -68.57732       7.57      1.96      2.89      1.34  0.188       -4.83      5.40 DAV1_GPS 
   74.69427   42.67977      -0.62      9.49      1.60      1.74 -0.147       -0.15      3.57 POL2_GPS 
   70.25552  -49.35147       0.38      1.78      3.20      2.03 -0.375       13.45      5.96 KERG_GPS 
   20.96845   67.85735      -1.10      3.87      0.93      1.13  0.140        1.82      4.12 KIRU_GPS*
   16.70446   40.64913       0.05      0.52      0.94      0.85 -0.169        2.10      3.13 MATE_GPS*
   12.87891   49.14420      -1.32      0.03      0.75      0.78 -0.024       -5.68      2.96 WTZR_GPS*
   11.86509   78.92958      -0.04     -6.30      0.84      1.07  0.125        2.90      4.23 NYAL_GPS*
    7.46528   46.87710      -0.08     -1.13      0.63      0.67 -0.025        1.94      2.66 ZIMM_GPS*
POS STATISTICS: For    9 RefSites WRMS ENU   1.45   2.76   6.25  mm    NRMS ENU   1.69   2.81   1.68 L0601141200_thss.glx
POS MEANS: For    9 RefSites: East   0.01 +-   0.48 North  -0.37 +-   0.92 Up   2.57 +-   2.08 mm L0601141200_thss.glx

 PARAMETER ESTIMATES FROM GLOBK Vers 5.29        
  #      PARAMETER                            Estimate       Adjustment     Sigma
Int. VILL_GPS  4849833.68541  -335049.02412  4116014.92373   -0.01055    0.02001    0.01155 2005.002
    1. VILL_GPS X coordinate  (m)          4849833.68307      0.00859      0.00271
    2. VILL_GPS Y coordinate  (m)          -335049.00149      0.00189      0.00079
    3. VILL_GPS Z coordinate  (m)          4116014.94718      0.01148      0.00244
Unc. VILL_GPS  4849833.68307  -335049.00149  4116014.94718   -0.01055    0.02001    0.01155 2006.037  0.0027  0.0008  0.0024
Apr. VILL_GPS  4849833.68307  -335049.00149  4116014.94718   -0.01055    0.02001    0.01155 2006.037  0.0027  0.0008  0.0024  -1.0000 -1.0000 -1.0000
Loc.   VILL_GPS N coordinate  (m)          4502160.23159      0.00331      0.00092
Loc.   VILL_GPS E coordinate  (m)         30163503.97016      0.00248      0.00077
Loc.   VILL_GPS U coordinate  (m)              647.34285      0.01386      0.00353
     NE,NU,EU position correlations         -0.0200       0.0775      -0.0035
pbo. VILL_GPS ----------------  2006 01 14 11 59 53749.4998   4849833.68307  -335049.00149  4116014.94718 0.00271 0.00079 0.00244 -0.216  0.871 -0.215 |    40.4435934759  356.0480210517  647.34285      8.3     9.1    0.00353 |   4502160.23159 30163503.97016  647.34285 0.00092 0.00077 0.00353 -0.020  0.078 -0.004

Int. REYK_GPS  2587384.32846 -1043033.51334  5716564.04602   -0.01961   -0.00176    0.00895 2005.002
    4. REYK_GPS X coordinate  (m)          2587384.28529     -0.02285      0.00201
    5. REYK_GPS Y coordinate  (m)         -1043033.52175     -0.00659      0.00123
    6. REYK_GPS Z coordinate  (m)          5716564.03605     -0.01925      0.00381
Unc. REYK_GPS  2587384.28529 -1043033.52175  5716564.03605   -0.01961   -0.00176    0.00895 2006.037  0.0020  0.0012  0.0038
Apr. REYK_GPS  2587384.28529 -1043033.52175  5716564.03605   -0.01961   -0.00176    0.00895 2006.037  0.0020  0.0012  0.0038  -1.0000 -1.0000 -1.0000
Loc.   REYK_GPS N coordinate  (m)          7139896.81324      0.00839      0.00134
Loc.   REYK_GPS E coordinate  (m)         16413892.67542     -0.01465      0.00114
Loc.   REYK_GPS U coordinate  (m)               93.02366     -0.02551      0.00412
     NE,NU,EU position correlations         -0.0190       0.1074       0.1289
pbo. REYK_GPS ----------------  2006 01 14 11 59 53749.4998   2587384.28529 -1043033.52175  5716564.03605 0.00201 0.00123 0.00381 -0.331  0.706 -0.344 |    64.1387843437  338.0445140588   93.02366     12.0    23.4    0.00412 |   7139896.81324 16413892.67542   93.02366 0.00134 0.00114 0.00412 -0.019  0.107  0.129

Int. CRO1_GPS  2607771.21531 -5488076.69905  1932767.78997    0.00742    0.00906    0.01252 2005.002
    7. CRO1_GPS X coordinate  (m)          2607771.21782     -0.00518      0.00295
    8. CRO1_GPS Y coordinate  (m)         -5488076.68951      0.00015      0.00499
    9. CRO1_GPS Z coordinate  (m)          1932767.80077     -0.00218      0.00304
Unc. CRO1_GPS  2607771.21782 -5488076.68951  1932767.80077    0.00742    0.00906    0.01252 2006.037  0.0029  0.0050  0.0030
Apr. CRO1_GPS  2607771.21782 -5488076.68951  1932767.80077    0.00742    0.00906    0.01252 2006.037  0.0029  0.0050  0.0030  -1.0000 -1.0000 -1.0000
Loc.   CRO1_GPS N coordinate  (m)          1976688.88012     -0.00136      0.00212
Loc.   CRO1_GPS E coordinate  (m)         31319027.49288     -0.00461      0.00178
Loc.   CRO1_GPS U coordinate  (m)              -31.95390     -0.00291      0.00593
     NE,NU,EU position correlations          0.5443       0.2617       0.1266
pbo. CRO1_GPS ----------------  2006 01 14 11 59 53749.4998   2607771.21782 -5488076.68951  1932767.80077 0.00295 0.00499 0.00304 -0.747  0.792 -0.621 |    17.7568983296  295.4156802594  -31.95390     19.1    16.7    0.00593 |   1976688.88012 31319027.49288  -31.95390 0.00212 0.00178 0.00593  0.544  0.262  0.127

Int. AREQ_GPS  1942826.82329 -5804070.23825 -1796893.84451    0.01247    0.00007    0.01400 2005.002
   10. AREQ_GPS X coordinate  (m)          1942826.19109     -0.64513      0.00457
   11. AREQ_GPS Y coordinate  (m)         -5804070.30885     -0.07068      0.00845
   12. AREQ_GPS Z coordinate  (m)         -1796894.24934     -0.41934      0.00357
Unc. AREQ_GPS  1942826.19109 -5804070.30885 -1796894.24934    0.01247    0.00007    0.01400 2006.037  0.0046  0.0084  0.0036
Apr. AREQ_GPS  1942826.19109 -5804070.30885 -1796894.24934    0.01247    0.00007    0.01400 2006.037  0.0046  0.0084  0.0036  -1.0000 -1.0000 -1.0000
Loc.   AREQ_GPS N coordinate  (m)         -1832932.95751     -0.44116      0.00416
Loc.   AREQ_GPS E coordinate  (m)         30799610.93168     -0.63420      0.00289
Loc.   AREQ_GPS U coordinate  (m)             2488.89721     -0.01405      0.00890
     NE,NU,EU position correlations          0.4184       0.4734       0.2701
pbo. AREQ_GPS ----------------  2006 01 14 11 59 53749.4998   1942826.19109 -5804070.30885 -1796894.24934 0.00457 0.00845 0.00357 -0.756  0.129  0.092 |   -16.4655169050  288.5072033883 2488.89721     37.4    27.1    0.00890 |  -1832932.95751 30799610.93168 2488.89721 0.00416 0.00289 0.00890  0.418  0.473  0.270

Int. YELL_GPS -1224452.50143 -2689216.10746  5633638.27862   -0.02082   -0.00441   -0.00093 1997.002
   13. YELL_GPS X coordinate  (m)         -1224452.68567      0.00390      0.00174
   14. YELL_GPS Y coordinate  (m)         -2689216.14727      0.00004      0.00229
   15. YELL_GPS Z coordinate  (m)          5633638.29392      0.02370      0.00395
Unc. YELL_GPS -1224452.68567 -2689216.14727  5633638.29392   -0.02082   -0.00441   -0.00093 2006.037  0.0017  0.0023  0.0039
Apr. YELL_GPS -1224452.68567 -2689216.14727  5633638.29392   -0.02082   -0.00441   -0.00093 2006.037  0.0017  0.0023  0.0039  -1.0000 -1.0000 -1.0000
Loc.   YELL_GPS N coordinate  (m)          6955341.28123      0.01247      0.00194
Loc.   YELL_GPS E coordinate  (m)         12628197.28057      0.00353      0.00178
Loc.   YELL_GPS U coordinate  (m)              180.92368      0.02022      0.00411
     NE,NU,EU position correlations          0.0880       0.2300       0.2629
pbo. YELL_GPS ----------------  2006 01 14 11 59 53749.4998  -1224452.68567 -2689216.14727  5633638.29392 0.00174 0.00229 0.00395  0.078 -0.018 -0.524 |    62.4808937920  245.5192981338  180.92368     17.5    34.7    0.00411 |   6955341.28123 12628197.28057  180.92368 0.00194 0.00178 0.00411  0.088  0.230  0.263

Int. TRAK_GPS -2480029.24905 -4703110.82031  3511298.59513   -0.02924    0.02645    0.01537 2005.002
   16. TRAK_GPS X coordinate  (m)         -2480029.28153     -0.00218      0.00266
   17. TRAK_GPS Y coordinate  (m)         -4703110.77705      0.01585      0.00467
   18. TRAK_GPS Z coordinate  (m)          3511298.61373      0.00268      0.00369
Unc. TRAK_GPS -2480029.28153 -4703110.77705  3511298.61373   -0.02924    0.02645    0.01537 2006.037  0.0027  0.0047  0.0037
Apr. TRAK_GPS -2480029.28153 -4703110.77705  3511298.61373   -0.02924    0.02645    0.01537 2006.037  0.0027  0.0047  0.0037  -1.0000 -1.0000 -1.0000
Loc.   TRAK_GPS N coordinate  (m)          3742331.39631      0.00940      0.00241
Loc.   TRAK_GPS E coordinate  (m)         22451843.43760     -0.00932      0.00247
Loc.   TRAK_GPS U coordinate  (m)              115.53369     -0.00937      0.00553
     NE,NU,EU position correlations          0.1264       0.0219       0.3183
pbo. TRAK_GPS ----------------  2006 01 14 11 59 53749.4998  -2480029.28153 -4703110.77705  3511298.61373 0.00266 0.00467 0.00369  0.407 -0.273 -0.672 |    33.6179349155  242.1965658107  115.53369     21.7    26.7    0.00553 |   3742331.39631 22451843.43760  115.53369 0.00241 0.00247 0.00553  0.126  0.022  0.318

Int. HOB2_GPS -3950071.67350  2522415.25416 -4311638.02559   -0.03974    0.00862    0.04074 2005.002
   19. HOB2_GPS X coordinate  (m)         -3950071.71716     -0.00248      0.00322
   20. HOB2_GPS Y coordinate  (m)          2522415.26277     -0.00032      0.00230
   21. HOB2_GPS Z coordinate  (m)         -4311637.98902     -0.00565      0.00372
Unc. HOB2_GPS -3950071.71716  2522415.26277 -4311637.98902   -0.03974    0.00862    0.04074 2006.037  0.0032  0.0023  0.0037
Apr. HOB2_GPS -3950071.71716  2522415.26277 -4311637.98902   -0.03974    0.00862    0.04074 2006.037  0.0032  0.0023  0.0037  -1.0000 -1.0000 -1.0000
Loc.   HOB2_GPS N coordinate  (m)         -4764998.76474     -0.00286      0.00111
Loc.   HOB2_GPS E coordinate  (m)         12041419.15811      0.00160      0.00089
Loc.   HOB2_GPS U coordinate  (m)               41.06335      0.00524      0.00525
     NE,NU,EU position correlations          0.2665      -0.0992      -0.1865
pbo. HOB2_GPS ----------------  2006 01 14 11 59 53749.4998  -3950071.71716  2522415.26277 -4311637.98902 0.00322 0.00230 0.00372 -0.890  0.888 -0.903 |   -42.8047121918  147.4387345305   41.06335     10.0    10.8    0.00525 |  -4764998.76474 12041419.15811   41.06335 0.00111 0.00089 0.00525  0.267 -0.099 -0.187

Int. TOW2_GPS -5054582.94073  3275504.33760 -2091539.27586   -0.03094   -0.01432    0.05283 2005.002
   22. TOW2_GPS X coordinate  (m)         -5054582.97969     -0.00690      0.00427
   23. TOW2_GPS Y coordinate  (m)          3275504.32828      0.00552      0.00284
   24. TOW2_GPS Z coordinate  (m)         -2091539.22713     -0.00602      0.00321
Unc. TOW2_GPS -5054582.97969  3275504.32828 -2091539.22713   -0.03094   -0.01432    0.05283 2006.037  0.0043  0.0028  0.0032
Apr. TOW2_GPS -5054582.97969  3275504.32828 -2091539.22713   -0.03094   -0.01432    0.05283 2006.037  0.0043  0.0028  0.0032  -1.0000 -1.0000 -1.0000
Loc.   TOW2_GPS N coordinate  (m)         -2145046.38796     -0.00280      0.00214
Loc.   TOW2_GPS E coordinate  (m)         15453122.46567     -0.00088      0.00107
Loc.   TOW2_GPS U coordinate  (m)               88.12971      0.01028      0.00555
     NE,NU,EU position correlations          0.2031      -0.3928       0.0087
pbo. TOW2_GPS ----------------  2006 01 14 11 59 53749.4998  -5054582.97969  3275504.32828 -2091539.22713 0.00427 0.00284 0.00321 -0.897  0.706 -0.743 |   -19.2692795545  147.0556883447   88.12971     19.2    10.2    0.00555 |  -2145046.38796 15453122.46567   88.12971 0.00214 0.00107 0.00555  0.203 -0.393  0.009

Int. GUAM_GPS -5071312.73778  3568363.55234  1488904.35997    0.00611    0.00737    0.00522 2005.002
   25. GUAM_GPS X coordinate  (m)         -5071312.74018     -0.00873      0.00761
   26. GUAM_GPS Y coordinate  (m)          3568363.56243      0.00245      0.00499
   27. GUAM_GPS Z coordinate  (m)          1488904.34851     -0.01687      0.00380
Unc. GUAM_GPS -5071312.74018  3568363.56243  1488904.34851    0.00611    0.00737    0.00522 2006.037  0.0076  0.0050  0.0038
Apr. GUAM_GPS -5071312.74018  3568363.56243  1488904.34851    0.00611    0.00737    0.00522 2006.037  0.0076  0.0050  0.0038  -1.0000 -1.0000 -1.0000
Loc.   GUAM_GPS N coordinate  (m)          1512757.23114     -0.01840      0.00354
Loc.   GUAM_GPS E coordinate  (m)         15675134.98059      0.00302      0.00236
Loc.   GUAM_GPS U coordinate  (m)              201.92682      0.00438      0.00890
     NE,NU,EU position correlations         -0.1199      -0.1205       0.2180
pbo. GUAM_GPS ----------------  2006 01 14 11 59 53749.4998  -5071312.74018  3568363.56243  1488904.34851 0.00761 0.00499 0.00380 -0.847 -0.334  0.352 |    13.5893294189  144.8683609836  201.92682     31.8    21.8    0.00890 |   1512757.23114 15675134.98059  201.92682 0.00354 0.00236 0.00890 -0.120 -0.120  0.218

Int. USUD_GPS -3855263.02241  3427432.54860  3741020.34317   -0.00468    0.00390   -0.00211 2005.002
   28. USUD_GPS X coordinate  (m)         -3855263.01987      0.00739      0.00393
   29. USUD_GPS Y coordinate  (m)          3427432.54530     -0.00735      0.00298
   30. USUD_GPS Z coordinate  (m)          3741020.30288     -0.03810      0.00406
Unc. USUD_GPS -3855263.01987  3427432.54530  3741020.30288   -0.00468    0.00390   -0.00211 2006.037  0.0039  0.0030  0.0041
Apr. USUD_GPS -3855263.01987  3427432.54530  3741020.30288   -0.00468    0.00390   -0.00211 2006.037  0.0039  0.0030  0.0041  -1.0000 -1.0000 -1.0000
Loc.   USUD_GPS N coordinate  (m)          4022319.45250     -0.02474      0.00314
Loc.   USUD_GPS E coordinate  (m)         12439689.09837      0.00058      0.00178
Loc.   USUD_GPS U coordinate  (m)             1508.60905     -0.03079      0.00527
     NE,NU,EU position correlations         -0.2099       0.0283       0.2014
pbo. USUD_GPS ----------------  2006 01 14 11 59 53749.4998  -3855263.01987  3427432.54530  3741020.30288 0.00393 0.00298 0.00406 -0.740 -0.413  0.466 |    36.1331104179  138.3620435820 1508.60905     28.2    19.8    0.00527 |   4022319.45250 12439689.09837 1508.60905 0.00314 0.00178 0.00527 -0.210  0.028  0.201

Int. DAV1_GPS   486854.55811  2285099.25423 -5914955.68461    0.00161   -0.00585   -0.00068 2005.002
   31. DAV1_GPS X coordinate  (m)           486854.55239     -0.00739      0.00264
   32. DAV1_GPS Y coordinate  (m)          2285099.24979      0.00162      0.00270
   33. DAV1_GPS Z coordinate  (m)         -5914955.68011      0.00521      0.00501
Unc. DAV1_GPS   486854.55239  2285099.24979 -5914955.68011    0.00161   -0.00585   -0.00068 2006.037  0.0026  0.0027  0.0050
Apr. DAV1_GPS   486854.55239  2285099.24979 -5914955.68011    0.00161   -0.00585   -0.00068 2006.037  0.0026  0.0027  0.0050  -1.0000 -1.0000 -1.0000
Loc.   DAV1_GPS N coordinate  (m)         -7633992.68323      0.00196      0.00134
Loc.   DAV1_GPS E coordinate  (m)          3170252.89043      0.00757      0.00289
Loc.   DAV1_GPS U coordinate  (m)               44.38197     -0.00483      0.00540
     NE,NU,EU position correlations          0.1877       0.0726       0.4396
pbo. DAV1_GPS ----------------  2006 01 14 11 59 53749.4998    486854.55239  2285099.24979 -5914955.68011 0.00264 0.00270 0.00501 -0.483  0.299 -0.799 |   -68.5773230620   77.9726133410   44.38197     12.1    71.1    0.00540 |  -7633992.68323  3170252.89043   44.38197 0.00134 0.00289 0.00540  0.188  0.073  0.440

Int. POL2_GPS  1239971.36992  4530790.09428  4302578.81606   -0.02731    0.00533    0.00479 2005.002
   34. POL2_GPS X coordinate  (m)          1239971.34050     -0.00112      0.00182
   35. POL2_GPS Y coordinate  (m)          4530790.09335     -0.00646      0.00231
   36. POL2_GPS Z coordinate  (m)          4302578.82792      0.00690      0.00311
Unc. POL2_GPS  1239971.34050  4530790.09335  4302578.82792   -0.02731    0.00533    0.00479 2006.037  0.0018  0.0023  0.0031
Apr. POL2_GPS  1239971.34050  4530790.09335  4302578.82792   -0.02731    0.00533    0.00479 2006.037  0.0018  0.0023  0.0031  -1.0000 -1.0000 -1.0000
Loc.   POL2_GPS N coordinate  (m)          4751090.28155      0.00949      0.00174
Loc.   POL2_GPS E coordinate  (m)          6112787.08043     -0.00062      0.00160
Loc.   POL2_GPS U coordinate  (m)             1714.20919     -0.00015      0.00357
     NE,NU,EU position correlations         -0.1472       0.3557      -0.3150
pbo. POL2_GPS ----------------  2006 01 14 11 59 53749.4998   1239971.34050  4530790.09335  4302578.82792 0.00182 0.00231 0.00311  0.429  0.491  0.619 |    42.6797701615   74.6942653693 1714.20919     15.7    19.5    0.00357 |   4751090.28155  6112787.08043 1714.20919 0.00174 0.00160 0.00357 -0.147  0.356 -0.315

Int. KERG_GPS  1406337.28912  3918161.09296 -4816167.35661   -0.00527   -0.00015   -0.00151 2005.002
   37. KERG_GPS X coordinate  (m)          1406337.28673      0.00307      0.00292
   38. KERG_GPS Y coordinate  (m)          3918161.10248      0.00968      0.00383
   39. KERG_GPS Z coordinate  (m)         -4816167.36719     -0.00901      0.00517
Unc. KERG_GPS  1406337.28673  3918161.10248 -4816167.36719   -0.00527   -0.00015   -0.00151 2006.037  0.0029  0.0038  0.0052
Apr. KERG_GPS  1406337.28673  3918161.10248 -4816167.36719   -0.00527   -0.00015   -0.00151 2006.037  0.0029  0.0038  0.0052  -1.0000 -1.0000 -1.0000
Loc.   KERG_GPS N coordinate  (m)         -5493780.15736      0.00178      0.00203
Loc.   KERG_GPS E coordinate  (m)          5094560.97332      0.00038      0.00320
Loc.   KERG_GPS U coordinate  (m)               73.02165      0.01345      0.00596
     NE,NU,EU position correlations         -0.3754      -0.3863       0.4019
pbo. KERG_GPS ----------------  2006 01 14 11 59 53749.4998   1406337.28673  3918161.10248 -4816167.36719 0.00292 0.00383 0.00517 -0.141  0.128 -0.833 |   -49.3514668295   70.2555221126   73.02165     18.3    44.1    0.00596 |  -5493780.15736  5094560.97332   73.02165 0.00203 0.00320 0.00596 -0.375 -0.386  0.402

Int. KIRU_GPS  2251420.79504   862817.22093  5885476.70247   -0.01574    0.01076    0.01142 2005.002
   40. KIRU_GPS X coordinate  (m)          2251420.77642     -0.00231      0.00178
   41. KIRU_GPS Y coordinate  (m)           862817.23002     -0.00206      0.00096
   42. KIRU_GPS Z coordinate  (m)          5885476.71746      0.00316      0.00388
Unc. KIRU_GPS  2251420.77642   862817.23002  5885476.71746   -0.01574    0.01076    0.01142 2006.037  0.0018  0.0010  0.0039
Apr. KIRU_GPS  2251420.77642   862817.23002  5885476.71746   -0.01574    0.01076    0.01142 2006.037  0.0018  0.0010  0.0039  -1.0000 -1.0000 -1.0000
Loc.   KIRU_GPS N coordinate  (m)          7553845.84095      0.00387      0.00113
Loc.   KIRU_GPS E coordinate  (m)           879764.88292     -0.00110      0.00093
Loc.   KIRU_GPS U coordinate  (m)              390.98193      0.00182      0.00412
     NE,NU,EU position correlations          0.1402       0.0897      -0.1538
pbo. KIRU_GPS ----------------  2006 01 14 11 59 53749.4998   2251420.77642   862817.23002  5885476.71746 0.00178 0.00096 0.00388  0.305  0.730  0.377 |    67.8573517281   20.9684476158  390.98193     10.1    22.2    0.00412 |   7553845.84095   879764.88292  390.98193 0.00113 0.00093 0.00412  0.140  0.090 -0.154

Int. MATE_GPS  4641949.55683  1393045.42466  4133287.46435   -0.01829    0.01899    0.01495 2005.002
   43. MATE_GPS X coordinate  (m)          4641949.53907      0.00119      0.00236
   44. MATE_GPS Y coordinate  (m)          1393045.44475      0.00041      0.00110
   45. MATE_GPS Z coordinate  (m)          4133287.48160      0.00176      0.00215
Unc. MATE_GPS  4641949.53907  1393045.44475  4133287.48160   -0.01829    0.01899    0.01495 2006.037  0.0024  0.0011  0.0021
Apr. MATE_GPS  4641949.53907  1393045.44475  4133287.48160   -0.01829    0.01899    0.01495 2006.037  0.0024  0.0011  0.0021  -1.0000 -1.0000 -1.0000
Loc.   MATE_GPS N coordinate  (m)          4525040.66006      0.00052      0.00085
Loc.   MATE_GPS E coordinate  (m)          1410869.02931      0.00005      0.00094
Loc.   MATE_GPS U coordinate  (m)              535.65319      0.00210      0.00313
     NE,NU,EU position correlations         -0.1691       0.0245      -0.1092
pbo. MATE_GPS ----------------  2006 01 14 11 59 53749.4998   4641949.53907  1393045.44475  4133287.48160 0.00236 0.00110 0.00215  0.482  0.864  0.419 |    40.6491318619   16.7044596840  535.65319      7.7    11.1    0.00313 |   4525040.66006  1410869.02931  535.65319 0.00085 0.00094 0.00313 -0.169  0.025 -0.109

Int. WTZR_GPS  4075580.55298   931853.79721  4801568.13598   -0.01605    0.01713    0.01009 2005.002
   46. WTZR_GPS X coordinate  (m)          4075580.53299     -0.00336      0.00201
   47. WTZR_GPS Y coordinate  (m)           931853.81284     -0.00212      0.00082
   48. WTZR_GPS Z coordinate  (m)          4801568.14218     -0.00426      0.00229
Unc. WTZR_GPS  4075580.53299   931853.81284  4801568.14218   -0.01605    0.01713    0.01009 2006.037  0.0020  0.0008  0.0023
Apr. WTZR_GPS  4075580.53299   931853.81284  4801568.14218   -0.01605    0.01713    0.01009 2006.037  0.0020  0.0008  0.0023  -1.0000 -1.0000 -1.0000
Loc.   WTZR_GPS N coordinate  (m)          5470707.16431      0.00003      0.00078
Loc.   WTZR_GPS E coordinate  (m)           937828.67940     -0.00132      0.00075
Loc.   WTZR_GPS U coordinate  (m)              666.02220     -0.00568      0.00296
     NE,NU,EU position correlations         -0.0239      -0.0024      -0.1169
pbo. WTZR_GPS ----------------  2006 01 14 11 59 53749.4998   4075580.53299   931853.81284  4801568.14218 0.00201 0.00082 0.00229  0.385  0.868  0.374 |    49.1441986065   12.8789100308  666.02220      7.0    10.3    0.00296 |   5470707.16431   937828.67940  666.02220 0.00078 0.00075 0.00296 -0.024 -0.002 -0.117

Int. NYAL_GPS  1202430.53162   252626.70891  6237767.61729   -0.01430    0.00750    0.01103 2005.002
   49. NYAL_GPS X coordinate  (m)          1202430.52341      0.00660      0.00130
   50. NYAL_GPS Y coordinate  (m)           252626.71803      0.00135      0.00082
   51. NYAL_GPS Z coordinate  (m)          6237767.63035      0.00163      0.00417
Unc. NYAL_GPS  1202430.52341   252626.71803  6237767.63035   -0.01430    0.00750    0.01103 2006.037  0.0013  0.0008  0.0042
Apr. NYAL_GPS  1202430.52341   252626.71803  6237767.63035   -0.01430    0.00750    0.01103 2006.037  0.0013  0.0008  0.0042  -1.0000 -1.0000 -1.0000
Loc.   NYAL_GPS N coordinate  (m)          8786401.19715     -0.00630      0.00107
Loc.   NYAL_GPS E coordinate  (m)           253597.00942     -0.00004      0.00084
Loc.   NYAL_GPS U coordinate  (m)               78.52541      0.00290      0.00423
     NE,NU,EU position correlations          0.1255       0.0708      -0.1006
pbo. NYAL_GPS ----------------  2006 01 14 11 59 53749.4998   1202430.52341   252626.71803  6237767.63035 0.00130 0.00082 0.00417  0.028  0.532  0.080 |    78.9295848780   11.8650870132   78.52541      9.7    39.1    0.00423 |   8786401.19715   253597.00942   78.52541 0.00107 0.00084 0.00423  0.125  0.071 -0.101

Int. ZIMM_GPS  4331297.06286   567555.87751  4633133.93566   -0.01353    0.01807    0.01205 2005.002
   52. ZIMM_GPS X coordinate  (m)          4331297.05098      0.00215      0.00187
   53. ZIMM_GPS Y coordinate  (m)           567555.89643      0.00020      0.00064
   54. ZIMM_GPS Z coordinate  (m)          4633133.94878      0.00063      0.00200
Unc. ZIMM_GPS  4331297.05098   567555.89643  4633133.94878   -0.01353    0.01807    0.01205 2006.037  0.0019  0.0006  0.0020
Apr. ZIMM_GPS  4331297.05098   567555.89643  4633133.94878   -0.01353    0.01807    0.01205 2006.037  0.0019  0.0006  0.0020  -1.0000 -1.0000 -1.0000
Loc.   ZIMM_GPS N coordinate  (m)          5218334.64335     -0.00113      0.00067
Loc.   ZIMM_GPS E coordinate  (m)           568072.18872     -0.00008      0.00063
Loc.   ZIMM_GPS U coordinate  (m)              956.33518      0.00194      0.00266
     NE,NU,EU position correlations         -0.0247       0.0259      -0.1384
pbo. ZIMM_GPS ----------------  2006 01 14 11 59 53749.4998   4331297.05098   567555.89643  4633133.94878 0.00187 0.00064 0.00200  0.213  0.879  0.198 |    46.8770976777    7.4652770493  956.33518      6.1     8.3    0.00266 |   5218334.64335   568072.18872  956.33518 0.00067 0.00063 0.00266 -0.025  0.026 -0.138

Eph. #IC  6  14 12  0  0                    GPST J2000 IAU76 BERNE
   55. PRN_0132 AntOffest X   (m)                0.27900      0.00000      0.00000
   56. PRN_0132 AntOffest Y   (m)                             0.00000      0.00000
   57. PRN_0132 AntOffest Z   (m)                2.38080      0.00000      0.00000
Eph.  2006  1 14 11 PRN_0132         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.38080

   58. PRN_0261 AntOffest X   (m)                             0.00000      0.00000
   59. PRN_0261 AntOffest Y   (m)                             0.00000      0.00000
   60. PRN_0261 AntOffest Z   (m)                0.77860      0.00000      0.00000
Eph.  2006  1 14 11 PRN_0261         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.77860

   61. PRN_0333 AntOffest X   (m)                0.27900      0.00000      0.00000
   62. PRN_0333 AntOffest Y   (m)                             0.00000      0.00000
   63. PRN_0333 AntOffest Z   (m)                2.79260      0.00000      0.00000
Eph.  2006  1 14 11 PRN_0333         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.79260

   64. PRN_0434 AntOffest X   (m)                0.27900      0.00000      0.00000
   65. PRN_0434 AntOffest Y   (m)                             0.00000      0.00000
   66. PRN_0434 AntOffest Z   (m)                2.42000      0.00000      0.00000
Eph.  2006  1 14 11 PRN_0434         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.42000

   67. PRN_0535 AntOffest X   (m)                0.27900      0.00000      0.00000
   68. PRN_0535 AntOffest Y   (m)                             0.00000      0.00000
   69. PRN_0535 AntOffest Z   (m)                2.62200      0.00000      0.00000
Eph.  2006  1 14 11 PRN_0535         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.62200

   70. PRN_0636 AntOffest X   (m)                0.27900      0.00000      0.00000
   71. PRN_0636 AntOffest Y   (m)                             0.00000      0.00000
   72. PRN_0636 AntOffest Z   (m)                2.87860      0.00000      0.00000
Eph.  2006  1 14 11 PRN_0636         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.87860

   73. PRN_0737 AntOffest X   (m)                0.27900      0.00000      0.00000
   74. PRN_0737 AntOffest Y   (m)                             0.00000      0.00000
   75. PRN_0737 AntOffest Z   (m)                2.35220      0.00000      0.00000
Eph.  2006  1 14 11 PRN_0737         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.35220

   76. PRN_0838 AntOffest X   (m)                0.27900      0.00000      0.00000
   77. PRN_0838 AntOffest Y   (m)                             0.00000      0.00000
   78. PRN_0838 AntOffest Z   (m)                2.57810      0.00000      0.00000
Eph.  2006  1 14 11 PRN_0838         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.57810

   79. PRN_0939 AntOffest X   (m)                0.27900      0.00000      0.00000
   80. PRN_0939 AntOffest Y   (m)                             0.00000      0.00000
   81. PRN_0939 AntOffest Z   (m)                2.46140      0.00000      0.00000
Eph.  2006  1 14 11 PRN_0939         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.46140

   82. PRN_1040 AntOffest X   (m)                0.27900      0.00000      0.00000
   83. PRN_1040 AntOffest Y   (m)                             0.00000      0.00000
   84. PRN_1040 AntOffest Z   (m)                2.54650      0.00000      0.00000
Eph.  2006  1 14 11 PRN_1040         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.54650

   85. PRN_1146 AntOffest X   (m)                             0.00000      0.00000
   86. PRN_1146 AntOffest Y   (m)                             0.00000      0.00000
   87. PRN_1146 AntOffest Z   (m)                1.14130      0.00000      0.00000
Eph.  2006  1 14 11 PRN_1146         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.14130

   88. PRN_1343 AntOffest X   (m)                             0.00000      0.00000
   89. PRN_1343 AntOffest Y   (m)                             0.00000      0.00000
   90. PRN_1343 AntOffest Z   (m)                1.38950      0.00000      0.00000
Eph.  2006  1 14 11 PRN_1343         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.38950

   91. PRN_1441 AntOffest X   (m)                             0.00000      0.00000
   92. PRN_1441 AntOffest Y   (m)                             0.00000      0.00000
   93. PRN_1441 AntOffest Z   (m)                1.34540      0.00000      0.00000
Eph.  2006  1 14 11 PRN_1441         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.34540

   94. PRN_1515 AntOffest X   (m)                0.27900      0.00000      0.00000
   95. PRN_1515 AntOffest Y   (m)                             0.00000      0.00000
   96. PRN_1515 AntOffest Z   (m)                2.46860      0.00000      0.00000
Eph.  2006  1 14 11 PRN_1515         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.46860

   97. PRN_1656 AntOffest X   (m)                             0.00000      0.00000
   98. PRN_1656 AntOffest Y   (m)                             0.00000      0.00000
   99. PRN_1656 AntOffest Z   (m)                1.50640      0.00000      0.00000
Eph.  2006  1 14 11 PRN_1656         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.50640

  100. PRN_1753 AntOffest X   (m)                             0.00000      0.00000
  101. PRN_1753 AntOffest Y   (m)                             0.00000      0.00000
  102. PRN_1753 AntOffest Z   (m)                0.82710      0.00000      0.00000
Eph.  2006  1 14 11 PRN_1753         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.82710

  103. PRN_1854 AntOffest X   (m)                             0.00000      0.00000
  104. PRN_1854 AntOffest Y   (m)                             0.00000      0.00000
  105. PRN_1854 AntOffest Z   (m)                1.29090      0.00000      0.00000
Eph.  2006  1 14 11 PRN_1854         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.29090

  106. PRN_1959 AntOffest X   (m)                             0.00000      0.00000
  107. PRN_1959 AntOffest Y   (m)                             0.00000      0.00000
  108. PRN_1959 AntOffest Z   (m)                0.84960      0.00000      0.00000
Eph.  2006  1 14 11 PRN_1959         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.84960

  109. PRN_2051 AntOffest X   (m)                             0.00000      0.00000
  110. PRN_2051 AntOffest Y   (m)                             0.00000      0.00000
  111. PRN_2051 AntOffest Z   (m)                1.34360      0.00000      0.00000
Eph.  2006  1 14 11 PRN_2051         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.34360

  112. PRN_2145 AntOffest X   (m)                             0.00000      0.00000
  113. PRN_2145 AntOffest Y   (m)                             0.00000      0.00000
  114. PRN_2145 AntOffest Z   (m)                1.40540      0.00000      0.00000
Eph.  2006  1 14 11 PRN_2145         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.40540

  115. PRN_2247 AntOffest X   (m)                             0.00000      0.00000
  116. PRN_2247 AntOffest Y   (m)                             0.00000      0.00000
  117. PRN_2247 AntOffest Z   (m)                0.90580      0.00000      0.00000
Eph.  2006  1 14 11 PRN_2247         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.90580

  118. PRN_2360 AntOffest X   (m)                             0.00000      0.00000
  119. PRN_2360 AntOffest Y   (m)                             0.00000      0.00000
  120. PRN_2360 AntOffest Z   (m)                0.80820      0.00000      0.00000
Eph.  2006  1 14 11 PRN_2360         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.80820

  121. PRN_2424 AntOffest X   (m)                0.27900      0.00000      0.00000
  122. PRN_2424 AntOffest Y   (m)                             0.00000      0.00000
  123. PRN_2424 AntOffest Z   (m)                2.60380      0.00000      0.00000
Eph.  2006  1 14 11 PRN_2424         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.60380

  124. PRN_2525 AntOffest X   (m)                0.27900      0.00000      0.00000
  125. PRN_2525 AntOffest Y   (m)                             0.00000      0.00000
  126. PRN_2525 AntOffest Z   (m)                2.48900      0.00000      0.00000
Eph.  2006  1 14 11 PRN_2525         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.48900

  127. PRN_2626 AntOffest X   (m)                0.27900      0.00000      0.00000
  128. PRN_2626 AntOffest Y   (m)                             0.00000      0.00000
  129. PRN_2626 AntOffest Z   (m)                2.45940      0.00000      0.00000
Eph.  2006  1 14 11 PRN_2626         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.45940

  130. PRN_2727 AntOffest X   (m)                0.27900      0.00000      0.00000
  131. PRN_2727 AntOffest Y   (m)                             0.00000      0.00000
  132. PRN_2727 AntOffest Z   (m)                2.63340      0.00000      0.00000
Eph.  2006  1 14 11 PRN_2727         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.63340

  133. PRN_2844 AntOffest X   (m)                             0.00000      0.00000
  134. PRN_2844 AntOffest Y   (m)                             0.00000      0.00000
  135. PRN_2844 AntOffest Z   (m)                1.04280      0.00000      0.00000
Eph.  2006  1 14 11 PRN_2844         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.04280

  136. PRN_2929 AntOffest X   (m)                0.27900      0.00000      0.00000
  137. PRN_2929 AntOffest Y   (m)                             0.00000      0.00000
  138. PRN_2929 AntOffest Z   (m)                2.51430      0.00000      0.00000
Eph.  2006  1 14 11 PRN_2929         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.51430

  139. PRN_3030 AntOffest X   (m)                0.27900      0.00000      0.00000
  140. PRN_3030 AntOffest Y   (m)                             0.00000      0.00000
  141. PRN_3030 AntOffest Z   (m)                2.61270      0.00000      0.00000
Eph.  2006  1 14 11 PRN_3030         0.0000         0.0000         0.0000        0.00000        0.00000        0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.27900   0.00000   2.61270

  142. X-pole position        (mas)             49.08628      0.23528      0.06335
  143. Y-pole position        (mas)            380.31308      0.02108      0.05854

  144. UT1-AT                 (ms)          -32665.93218      0.00982      0.00220
      Pole/UT1 correlations: XY, XU, YU          0.6697     0.0636     0.1754

IERS  MJD      Xpole   Ypole  UT1-UTC    LOD  Xsig  Ysig   UTsig  LODsig  Nr Nf Nt    Xrt    Yrt  Xrtsig  Yrtsig XYcorr XUTcor YUTcor
IERS             (10**-6")       (0.1 usec)    (10**-6")     (0.1 usec)              (10**-6"/d)    (10**-6"/d)
IERS53749.50   49086  380313  3340678   -890    63    59      22       0  18  9 29    540   -275      0      0    0.670  0.064  0.175


